const COMMON = {
  'en-US': {
    save:'Save', saveChanges:'Save Changes', cancel:'Cancel', close:'Close', delete:'Delete', edit:'Edit', add:'Add', create:'Create', update:'Update', remove:'Remove', search:'Search', filter:'Filter', clear:'Clear', apply:'Apply', confirm:'Confirm', continue:'Continue', back:'Back', next:'Next', previous:'Previous', actions:'Actions', status:'Status', date:'Date', startDate:'Start Date', endDate:'End Date', name:'Name', description:'Description', code:'Code', type:'Type', project:'Project', projects:'Projects', location:'Location', locations:'Locations', user:'User', users:'Users', role:'Role', active:'Active', inactive:'Inactive', open:'Open', closed:'Closed', ready:'Ready', notReady:'Not Ready', loading:'Loading...', saving:'Saving...', noData:'No data available', yes:'Yes', no:'No', all:'All', none:'None', select:'Select', selected:'Selected', settings:'Settings', organization:'Organization', workspace:'Workspace', workPackage:'Work Package', constraint:'Constraint', constraints:'Constraints', workforce:'Workforce', activity:'Activity', activities:'Activities', milestone:'Milestone', summary:'Summary', task:'Task', duration:'Duration', progress:'Progress', quantity:'Quantity', unit:'Unit', responsible:'Responsible', priority:'Priority', notes:'Notes', information:'Information', materials:'Materials', labor:'Labor', equipment:'Equipment', external:'External', space:'Space'
  },
  'pt-BR': {
    save:'Salvar', saveChanges:'Salvar Alterações', cancel:'Cancelar', close:'Fechar', delete:'Excluir', edit:'Editar', add:'Adicionar', create:'Criar', update:'Atualizar', remove:'Remover', search:'Pesquisar', filter:'Filtrar', clear:'Limpar', apply:'Aplicar', confirm:'Confirmar', continue:'Continuar', back:'Voltar', next:'Próximo', previous:'Anterior', actions:'Ações', status:'Status', date:'Data', startDate:'Data de Início', endDate:'Data de Término', name:'Nome', description:'Descrição', code:'Código', type:'Tipo', project:'Projeto', projects:'Projetos', location:'Localização', locations:'Localizações', user:'Usuário', users:'Usuários', role:'Função', active:'Ativo', inactive:'Inativo', open:'Aberto', closed:'Encerrado', ready:'Pronto', notReady:'Não Pronto', loading:'Carregando...', saving:'Salvando...', noData:'Nenhum dado disponível', yes:'Sim', no:'Não', all:'Todos', none:'Nenhum', select:'Selecionar', selected:'Selecionado', settings:'Configurações', organization:'Organização', workspace:'Workspace', workPackage:'Pacote de Trabalho', constraint:'Restrição', constraints:'Restrições', workforce:'Força de Trabalho', activity:'Atividade', activities:'Atividades', milestone:'Marco', summary:'Resumo', task:'Tarefa', duration:'Duração', progress:'Progresso', quantity:'Quantidade', unit:'Unidade', responsible:'Responsável', priority:'Prioridade', notes:'Observações', information:'Informações', materials:'Materiais', labor:'Mão de Obra', equipment:'Equipamentos', external:'Externo', space:'Espaço'
  },
  es: {
    save:'Guardar', saveChanges:'Guardar Cambios', cancel:'Cancelar', close:'Cerrar', delete:'Eliminar', edit:'Editar', add:'Agregar', create:'Crear', update:'Actualizar', remove:'Eliminar', search:'Buscar', filter:'Filtrar', clear:'Limpiar', apply:'Aplicar', confirm:'Confirmar', continue:'Continuar', back:'Volver', next:'Siguiente', previous:'Anterior', actions:'Acciones', status:'Estado', date:'Fecha', startDate:'Fecha de Inicio', endDate:'Fecha de Finalización', name:'Nombre', description:'Descripción', code:'Código', type:'Tipo', project:'Proyecto', projects:'Proyectos', location:'Ubicación', locations:'Ubicaciones', user:'Usuario', users:'Usuarios', role:'Rol', active:'Activo', inactive:'Inactivo', open:'Abierto', closed:'Cerrado', ready:'Listo', notReady:'No Listo', loading:'Cargando...', saving:'Guardando...', noData:'No hay datos disponibles', yes:'Sí', no:'No', all:'Todos', none:'Ninguno', select:'Seleccionar', selected:'Seleccionado', settings:'Configuración', organization:'Organización', workspace:'Workspace', workPackage:'Paquete de Trabajo', constraint:'Restricción', constraints:'Restricciones', workforce:'Fuerza Laboral', activity:'Actividad', activities:'Actividades', milestone:'Hito', summary:'Resumen', task:'Tarea', duration:'Duración', progress:'Progreso', quantity:'Cantidad', unit:'Unidad', responsible:'Responsable', priority:'Prioridad', notes:'Notas', information:'Información', materials:'Materiales', labor:'Mano de Obra', equipment:'Equipos', external:'Externo', space:'Espacio'
  }
}

export function commonText(locale, key, vars = {}) {
  let value = COMMON[locale]?.[key] ?? COMMON['en-US'][key] ?? key
  for (const [name, replacement] of Object.entries(vars)) value = String(value).replaceAll(`{${name}}`, replacement)
  return value
}

export function commonCopy(locale) {
  return COMMON[locale] ?? COMMON['en-US']
}
