export const fieldopWorkforceMessages = {
  'en-US': {
    tabs:{liveAttendance:'Live Attendance',workerRegistry:'Worker Registry',projectAssignments:'Project Assignments',timecards:'Timecards',auditTrail:'Audit Trail'},
    timecards:{title:'Timecards',subtitle:'Attendance sessions, labor hours and exception review.',workersWithAttendance:'Workers With Attendance',totalLabor:'Total Labor',exceptions:'Exceptions',correctAttendance:'Correct Attendance',reviewException:'Review Exception',resolutionAction:'Resolution Action',saveCorrection:'Save Correction',loading:'Loading timecards...',empty:'No attendance sessions found.',project:'Project',worker:'Worker',date:'Date',checkIn:'Check-In',checkOut:'Check-Out',hours:'Hours',status:'Status',notes:'Notes',cancel:'Cancel',saving:'Saving...',close:'Close'},
    audit:{title:'Attendance Audit Trail',subtitle:'Immutable field events behind attendance, corrections and timecard decisions.',auditEvents:'Audit Events',workers:'Workers',manualAdjustments:'Manual Adjustments',gpsEvidence:'GPS Evidence',selectedDay:'selected day',withRecordedEvents:'with recorded events',auditedCorrections:'audited corrections',geolocatedEvents:'geolocated events',selectProject:'Select project',loading:'Loading audit trail...',empty:'No attendance events recorded for this project and date.',time:'Time',worker:'Worker',event:'Event',methodSource:'Method / Source',geofence:'Geofence',session:'Session',evidence:'Evidence',view:'View',evidenceTitle:'Audit Event Evidence',recordedBy:'Recorded By',createdAt:'Created At',gpsAccuracy:'GPS Accuracy',notes:'Notes',metadata:'Metadata',close:'Close'}
  },
  'pt-BR': {
    tabs:{liveAttendance:'Presença ao Vivo',workerRegistry:'Cadastro de Trabalhadores',projectAssignments:'Alocações em Projetos',timecards:'Cartões de Ponto',auditTrail:'Trilha de Auditoria'},
    timecards:{title:'Cartões de Ponto',subtitle:'Sessões de presença, horas de trabalho e análise de exceções.',workersWithAttendance:'Trabalhadores com Presença',totalLabor:'Total de Horas',exceptions:'Exceções',correctAttendance:'Corrigir Presença',reviewException:'Analisar Exceção',resolutionAction:'Ação de Resolução',saveCorrection:'Salvar Correção',loading:'Carregando cartões de ponto...',empty:'Nenhuma sessão de presença encontrada.',project:'Projeto',worker:'Trabalhador',date:'Data',checkIn:'Entrada',checkOut:'Saída',hours:'Horas',status:'Status',notes:'Observações',cancel:'Cancelar',saving:'Salvando...',close:'Fechar'},
    audit:{title:'Trilha de Auditoria de Presença',subtitle:'Eventos de campo imutáveis por trás da presença, correções e decisões dos cartões de ponto.',auditEvents:'Eventos de Auditoria',workers:'Trabalhadores',manualAdjustments:'Ajustes Manuais',gpsEvidence:'Evidências de GPS',selectedDay:'dia selecionado',withRecordedEvents:'com eventos registrados',auditedCorrections:'correções auditadas',geolocatedEvents:'eventos geolocalizados',selectProject:'Selecionar projeto',loading:'Carregando trilha de auditoria...',empty:'Nenhum evento de presença registrado para este projeto e data.',time:'Horário',worker:'Trabalhador',event:'Evento',methodSource:'Método / Origem',geofence:'Geofence',session:'Sessão',evidence:'Evidência',view:'Visualizar',evidenceTitle:'Evidência do Evento de Auditoria',recordedBy:'Registrado Por',createdAt:'Criado Em',gpsAccuracy:'Precisão do GPS',notes:'Observações',metadata:'Metadados',close:'Fechar'}
  },
  es: {
    tabs:{liveAttendance:'Asistencia en Vivo',workerRegistry:'Registro de Trabajadores',projectAssignments:'Asignaciones a Proyectos',timecards:'Tarjetas de Tiempo',auditTrail:'Registro de Auditoría'},
    timecards:{title:'Tarjetas de Tiempo',subtitle:'Sesiones de asistencia, horas de trabajo y revisión de excepciones.',workersWithAttendance:'Trabajadores con Asistencia',totalLabor:'Trabajo Total',exceptions:'Excepciones',correctAttendance:'Corregir Asistencia',reviewException:'Revisar Excepción',resolutionAction:'Acción de Resolución',saveCorrection:'Guardar Corrección',loading:'Cargando tarjetas de tiempo...',empty:'No se encontraron sesiones de asistencia.',project:'Proyecto',worker:'Trabajador',date:'Fecha',checkIn:'Entrada',checkOut:'Salida',hours:'Horas',status:'Estado',notes:'Notas',cancel:'Cancelar',saving:'Guardando...',close:'Cerrar'},
    audit:{title:'Registro de Auditoría de Asistencia',subtitle:'Eventos de campo inmutables detrás de la asistencia, correcciones y decisiones de las tarjetas de tiempo.',auditEvents:'Eventos de Auditoría',workers:'Trabajadores',manualAdjustments:'Ajustes Manuales',gpsEvidence:'Evidencia GPS',selectedDay:'día seleccionado',withRecordedEvents:'con eventos registrados',auditedCorrections:'correcciones auditadas',geolocatedEvents:'eventos geolocalizados',selectProject:'Seleccionar proyecto',loading:'Cargando registro de auditoría...',empty:'No hay eventos de asistencia registrados para este proyecto y fecha.',time:'Hora',worker:'Trabajador',event:'Evento',methodSource:'Método / Origen',geofence:'Geocerca',session:'Sesión',evidence:'Evidencia',view:'Ver',evidenceTitle:'Evidencia del Evento de Auditoría',recordedBy:'Registrado Por',createdAt:'Creado En',gpsAccuracy:'Precisión GPS',notes:'Notas',metadata:'Metadatos',close:'Cerrar'}
  }
}

export function getFieldopWorkforceMessages(locale='en-US') {
  return fieldopWorkforceMessages[locale] || fieldopWorkforceMessages['en-US']
}
