export const fieldopWorkforceMessages = {
  'en-US': {
    tabs:{liveAttendance:'Live Attendance',workerRegistry:'Worker Registry',projectAssignments:'Project Assignments',timecards:'Timecards',auditTrail:'Audit Trail'},
    timecards:{title:'Timecards',subtitle:"Daily attendance totals, corrections and exception resolution against the project's allowed working time.",workersWithAttendance:'Workers With Attendance',totalLabor:'Total Labor',exceptions:'Exceptions',openSessions:'Open Sessions',selectedDay:'selected day',closedSessions:'closed sessions',unresolvedTimecards:'unresolved timecards',notCheckedOut:'not checked out',selectProject:'Select project',loading:'Loading timecards...',empty:'No attendance recorded for this project and date.',worker:'Worker',firstIn:'First In',lastOut:'Last Out',worked:'Worked',allowed:'Allowed',variance:'Variance',sessions:'Sessions',status:'Status',action:'Action',notConfigured:'Not configured',openSession:'Open Session',exception:'Exception',corrected:'Corrected',withinAllowance:'Within Allowance',edit:'Edit',viewResolution:'View Resolution',reviewException:'Review Exception',correctAttendance:'Correct Attendance',correctionHelp:'Adjust this attendance session. RitsuFlow preserves the original punch events and records the correction as an immutable manual adjustment.',checkIn:'Check-In',checkOut:'Check-Out',correctionReason:'Correction Reason',correctionPlaceholder:'Explain why this attendance record is being corrected.',flaggedAttendance:'Flagged attendance',cancel:'Cancel',saving:'Saving...',saveCorrection:'Save Correction',attendanceException:'Attendance Exception',exceptionHelp:'Review the exception, document the decision and close the operational loop.',currentStatus:'Current Status',detectedNotes:'Detected Notes',resolutionAction:'Resolution Action',accept:'Accept',reject:'Reject',dismiss:'Dismiss',reviewResolutionNotes:'Review / Resolution Notes',reviewPlaceholder:'Document what was reviewed and why.',resolution:'Resolution',resolutionNotes:'Resolution Notes',close:'Close',markReviewed:'Mark Reviewed',resolveException:'Resolve Exception',recordedException:'Recorded Exception',errorLoad:'Unable to load timecards.',errorReason:'Enter a correction reason of at least 3 characters.',errorCheckIn:'Check-In is required.',errorCheckOut:'Check-Out is required for a corrected closed session.',errorOrder:'Check-Out cannot occur before Check-In.',errorCorrection:'Unable to correct the attendance session.',errorReview:'Unable to mark the exception as reviewed.',errorResolve:'Unable to resolve the attendance exception.'},
    audit:{title:'Attendance Audit Trail',subtitle:'Immutable field events behind attendance, corrections and timecard decisions.',auditEvents:'Audit Events',workers:'Workers',manualAdjustments:'Manual Adjustments',gpsEvidence:'GPS Evidence',selectedDay:'selected day',withRecordedEvents:'with recorded events',auditedCorrections:'audited corrections',geolocatedEvents:'geolocated events',selectProject:'Select project',loading:'Loading audit trail...',empty:'No attendance events recorded for this project and date.',time:'Time',worker:'Worker',event:'Event',methodSource:'Method / Source',geofence:'Geofence',session:'Session',evidence:'Evidence',view:'View',evidenceTitle:'Audit Event Evidence',recordedBy:'Recorded By',createdAt:'Created At',gpsAccuracy:'GPS Accuracy',notes:'Notes',metadata:'Metadata',close:'Close'}
  },
  'pt-BR': {
    tabs:{liveAttendance:'Presença ao Vivo',workerRegistry:'Cadastro de Trabalhadores',projectAssignments:'Alocações em Projetos',timecards:'Cartões de Ponto',auditTrail:'Trilha de Auditoria'},
    timecards:{title:'Cartões de Ponto',subtitle:'Totais diários de presença, correções e resolução de exceções em relação ao tempo de trabalho permitido no projeto.',workersWithAttendance:'Trabalhadores com Presença',totalLabor:'Total de Horas',exceptions:'Exceções',openSessions:'Sessões Abertas',selectedDay:'dia selecionado',closedSessions:'sessões encerradas',unresolvedTimecards:'cartões com pendências',notCheckedOut:'sem registro de saída',selectProject:'Selecionar projeto',loading:'Carregando cartões de ponto...',empty:'Nenhuma presença registrada para este projeto e data.',worker:'Trabalhador',firstIn:'Primeira Entrada',lastOut:'Última Saída',worked:'Trabalhado',allowed:'Permitido',variance:'Variação',sessions:'Sessões',status:'Status',action:'Ação',notConfigured:'Não configurado',openSession:'Sessão Aberta',exception:'Exceção',corrected:'Corrigido',withinAllowance:'Dentro do Permitido',edit:'Editar',viewResolution:'Ver Resolução',reviewException:'Analisar Exceção',correctAttendance:'Corrigir Presença',correctionHelp:'Ajuste esta sessão de presença. O RitsuFlow preserva os registros originais e registra a correção como um ajuste manual imutável.',checkIn:'Entrada',checkOut:'Saída',correctionReason:'Motivo da Correção',correctionPlaceholder:'Explique por que este registro de presença está sendo corrigido.',flaggedAttendance:'Presença sinalizada',cancel:'Cancelar',saving:'Salvando...',saveCorrection:'Salvar Correção',attendanceException:'Exceção de Presença',exceptionHelp:'Analise a exceção, documente a decisão e feche o ciclo operacional.',currentStatus:'Status Atual',detectedNotes:'Observações Detectadas',resolutionAction:'Ação de Resolução',accept:'Aceitar',reject:'Rejeitar',dismiss:'Descartar',reviewResolutionNotes:'Observações da Análise / Resolução',reviewPlaceholder:'Documente o que foi analisado e o motivo.',resolution:'Resolução',resolutionNotes:'Observações da Resolução',close:'Fechar',markReviewed:'Marcar como Analisada',resolveException:'Resolver Exceção',recordedException:'Exceção Registrada',errorLoad:'Não foi possível carregar os cartões de ponto.',errorReason:'Informe um motivo de correção com pelo menos 3 caracteres.',errorCheckIn:'A entrada é obrigatória.',errorCheckOut:'A saída é obrigatória para uma sessão encerrada corrigida.',errorOrder:'A saída não pode ocorrer antes da entrada.',errorCorrection:'Não foi possível corrigir a sessão de presença.',errorReview:'Não foi possível marcar a exceção como analisada.',errorResolve:'Não foi possível resolver a exceção de presença.'},
    audit:{title:'Trilha de Auditoria de Presença',subtitle:'Eventos de campo imutáveis por trás da presença, correções e decisões dos cartões de ponto.',auditEvents:'Eventos de Auditoria',workers:'Trabalhadores',manualAdjustments:'Ajustes Manuais',gpsEvidence:'Evidências de GPS',selectedDay:'dia selecionado',withRecordedEvents:'com eventos registrados',auditedCorrections:'correções auditadas',geolocatedEvents:'eventos geolocalizados',selectProject:'Selecionar projeto',loading:'Carregando trilha de auditoria...',empty:'Nenhum evento de presença registrado para este projeto e data.',time:'Horário',worker:'Trabalhador',event:'Evento',methodSource:'Método / Origem',geofence:'Geofence',session:'Sessão',evidence:'Evidência',view:'Visualizar',evidenceTitle:'Evidência do Evento de Auditoria',recordedBy:'Registrado Por',createdAt:'Criado Em',gpsAccuracy:'Precisão do GPS',notes:'Observações',metadata:'Metadados',close:'Fechar'}
  },
  es: {
    tabs:{liveAttendance:'Asistencia en Vivo',workerRegistry:'Registro de Trabajadores',projectAssignments:'Asignaciones a Proyectos',timecards:'Tarjetas de Tiempo',auditTrail:'Registro de Auditoría'},
    timecards:{title:'Tarjetas de Tiempo',subtitle:'Totales diarios de asistencia, correcciones y resolución de excepciones frente al tiempo de trabajo permitido del proyecto.',workersWithAttendance:'Trabajadores con Asistencia',totalLabor:'Trabajo Total',exceptions:'Excepciones',openSessions:'Sesiones Abiertas',selectedDay:'día seleccionado',closedSessions:'sesiones cerradas',unresolvedTimecards:'tarjetas pendientes',notCheckedOut:'sin salida registrada',selectProject:'Seleccionar proyecto',loading:'Cargando tarjetas de tiempo...',empty:'No hay asistencia registrada para este proyecto y fecha.',worker:'Trabajador',firstIn:'Primera Entrada',lastOut:'Última Salida',worked:'Trabajado',allowed:'Permitido',variance:'Variación',sessions:'Sesiones',status:'Estado',action:'Acción',notConfigured:'No configurado',openSession:'Sesión Abierta',exception:'Excepción',corrected:'Corregido',withinAllowance:'Dentro de lo Permitido',edit:'Editar',viewResolution:'Ver Resolución',reviewException:'Revisar Excepción',correctAttendance:'Corregir Asistencia',correctionHelp:'Ajuste esta sesión de asistencia. RitsuFlow conserva los registros originales y registra la corrección como un ajuste manual inmutable.',checkIn:'Entrada',checkOut:'Salida',correctionReason:'Motivo de Corrección',correctionPlaceholder:'Explique por qué se corrige este registro de asistencia.',flaggedAttendance:'Asistencia señalada',cancel:'Cancelar',saving:'Guardando...',saveCorrection:'Guardar Corrección',attendanceException:'Excepción de Asistencia',exceptionHelp:'Revise la excepción, documente la decisión y cierre el ciclo operativo.',currentStatus:'Estado Actual',detectedNotes:'Notas Detectadas',resolutionAction:'Acción de Resolución',accept:'Aceptar',reject:'Rechazar',dismiss:'Descartar',reviewResolutionNotes:'Notas de Revisión / Resolución',reviewPlaceholder:'Documente qué se revisó y por qué.',resolution:'Resolución',resolutionNotes:'Notas de Resolución',close:'Cerrar',markReviewed:'Marcar Revisada',resolveException:'Resolver Excepción',recordedException:'Excepción Registrada',errorLoad:'No se pudieron cargar las tarjetas de tiempo.',errorReason:'Ingrese un motivo de corrección de al menos 3 caracteres.',errorCheckIn:'La entrada es obligatoria.',errorCheckOut:'La salida es obligatoria para una sesión cerrada corregida.',errorOrder:'La salida no puede ocurrir antes de la entrada.',errorCorrection:'No se pudo corregir la sesión de asistencia.',errorReview:'No se pudo marcar la excepción como revisada.',errorResolve:'No se pudo resolver la excepción de asistencia.'},
    audit:{title:'Registro de Auditoría de Asistencia',subtitle:'Eventos de campo inmutables detrás de la asistencia, correcciones y decisiones de las tarjetas de tiempo.',auditEvents:'Eventos de Auditoría',workers:'Trabajadores',manualAdjustments:'Ajustes Manuales',gpsEvidence:'Evidencia GPS',selectedDay:'día seleccionado',withRecordedEvents:'con eventos registrados',auditedCorrections:'correcciones auditadas',geolocatedEvents:'eventos geolocalizados',selectProject:'Seleccionar proyecto',loading:'Cargando registro de auditoría...',empty:'No hay eventos de asistencia registrados para este proyecto y fecha.',time:'Hora',worker:'Trabajador',event:'Evento',methodSource:'Método / Origen',geofence:'Geocerca',session:'Sesión',evidence:'Evidencia',view:'Ver',evidenceTitle:'Evidencia del Evento de Auditoría',recordedBy:'Registrado Por',createdAt:'Creado En',gpsAccuracy:'Precisión GPS',notes:'Notas',metadata:'Metadatos',close:'Cerrar'}
  }
}

export function getFieldopWorkforceMessages(locale='en-US') {
  return fieldopWorkforceMessages[locale] || fieldopWorkforceMessages['en-US']
}
