const copy = {
  'en-US': {
    unexpectedError: 'An unexpected error occurred.', duplicateLocation: 'A location with the same identifying information already exists.', connectedRecord: 'This record is connected to other project information and cannot be changed.', invalidRules: 'One or more values do not satisfy the location structure rules.', permissionDenied: 'Your account does not have permission to perform this action.', operationFailed: 'The requested operation could not be completed.',
    locationTypes: { building: 'Building', floor: 'Division / Floor', zone: 'Zone / Area', area: 'Area', room: 'Room', custom: 'Custom' }, location: 'Location', project: 'Project', enterLocationName: 'Enter a location name.', ownParent: 'A location cannot be its own parent.', searchPlaceholder: 'Search locations...', addLocation: '+ Location', edit: 'Edit', delete: 'Delete', cancel: 'Cancel', save: 'Save', create: 'Create', saving: 'Saving...', name: 'Name', type: 'Type', parent: 'Parent', noParent: 'No parent', environmentType: 'Environment Type', sequence: 'Sequence', quantity: 'Quantity', actions: 'Actions', unassigned: 'Unassigned',
    locationStructure: 'Location Structure', locationStructureHelp: 'Build the project location hierarchy and organize production areas for location-based planning and control.', noLocations: 'No locations have been created yet.', createFirstLocation: '+ Create first Location', noProductionLocations: 'No production locations in this group.', scopeQuantities: 'Scope Quantities', noAllocatedScope: 'No allocated scope quantities for this location.',
    added: '{name} was added to the location structure.', updated: '{name} was updated.', deleted: '{name} was deleted from the location structure.', deleteSingle: 'Delete {name}? This action cannot be undone.', deleteTree: 'Delete {name}? This will also delete {count} contained {locationWord}. This action cannot be undone.', containedLocation: 'location', containedLocations: 'locations', deleteFailed: 'The location structure could not be deleted.', editLocation: 'Edit Location', createLocation: 'Create Location',
    building: 'Building', floor: 'Division / Floor', zone: 'Zone / Area', area: 'Area', room: 'Room', custom: 'Custom'
  },
  'pt-BR': {
    unexpectedError: 'Ocorreu um erro inesperado.', duplicateLocation: 'Já existe uma localização com as mesmas informações de identificação.', connectedRecord: 'Este registro está conectado a outras informações do projeto e não pode ser alterado.', invalidRules: 'Um ou mais valores não atendem às regras da estrutura de localizações.', permissionDenied: 'Sua conta não tem permissão para executar esta ação.', operationFailed: 'Não foi possível concluir a operação solicitada.',
    locationTypes: { building: 'Edifício', floor: 'Divisão / Pavimento', zone: 'Zona / Área', area: 'Área', room: 'Ambiente', custom: 'Personalizado' }, location: 'Localização', project: 'Projeto', enterLocationName: 'Informe o nome da localização.', ownParent: 'Uma localização não pode ser seu próprio nível pai.', searchPlaceholder: 'Pesquisar localizações...', addLocation: '+ Localização', edit: 'Editar', delete: 'Excluir', cancel: 'Cancelar', save: 'Salvar', create: 'Criar', saving: 'Salvando...', name: 'Nome', type: 'Tipo', parent: 'Nível Pai', noParent: 'Sem nível pai', environmentType: 'Tipo de Ambiente', sequence: 'Sequência', quantity: 'Quantidade', actions: 'Ações', unassigned: 'Não atribuído',
    locationStructure: 'Estrutura de Localizações', locationStructureHelp: 'Construa a hierarquia de localizações do projeto e organize as áreas de produção para o planejamento e controle baseados em localização.', noLocations: 'Nenhuma localização foi criada ainda.', createFirstLocation: '+ Criar primeira Localização', noProductionLocations: 'Nenhuma localização de produção neste grupo.', scopeQuantities: 'Quantidades de Escopo', noAllocatedScope: 'Não há quantidades de escopo alocadas para esta localização.',
    added: '{name} foi adicionada à estrutura de localizações.', updated: '{name} foi atualizada.', deleted: '{name} foi excluída da estrutura de localizações.', deleteSingle: 'Excluir {name}? Esta ação não pode ser desfeita.', deleteTree: 'Excluir {name}? Isso também excluirá {count} {locationWord} contida(s). Esta ação não pode ser desfeita.', containedLocation: 'localização', containedLocations: 'localizações', deleteFailed: 'Não foi possível excluir a estrutura de localizações.', editLocation: 'Editar Localização', createLocation: 'Criar Localização',
    building: 'Edifício', floor: 'Divisão / Pavimento', zone: 'Zona / Área', area: 'Área', room: 'Ambiente', custom: 'Personalizado'
  },
  es: {
    unexpectedError: 'Ocurrió un error inesperado.', duplicateLocation: 'Ya existe una ubicación con la misma información de identificación.', connectedRecord: 'Este registro está conectado con otra información del proyecto y no puede modificarse.', invalidRules: 'Uno o más valores no cumplen las reglas de la estructura de ubicaciones.', permissionDenied: 'Tu cuenta no tiene permiso para realizar esta acción.', operationFailed: 'No se pudo completar la operación solicitada.',
    locationTypes: { building: 'Edificio', floor: 'División / Piso', zone: 'Zona / Área', area: 'Área', room: 'Ambiente', custom: 'Personalizado' }, location: 'Ubicación', project: 'Proyecto', enterLocationName: 'Ingresa el nombre de la ubicación.', ownParent: 'Una ubicación no puede ser su propio nivel padre.', searchPlaceholder: 'Buscar ubicaciones...', addLocation: '+ Ubicación', edit: 'Editar', delete: 'Eliminar', cancel: 'Cancelar', save: 'Guardar', create: 'Crear', saving: 'Guardando...', name: 'Nombre', type: 'Tipo', parent: 'Nivel Padre', noParent: 'Sin nivel padre', environmentType: 'Tipo de Ambiente', sequence: 'Secuencia', quantity: 'Cantidad', actions: 'Acciones', unassigned: 'Sin asignar',
    locationStructure: 'Estructura de Ubicaciones', locationStructureHelp: 'Construye la jerarquía de ubicaciones del proyecto y organiza las áreas de producción para la planificación y el control basados en ubicación.', noLocations: 'Todavía no se han creado ubicaciones.', createFirstLocation: '+ Crear primera Ubicación', noProductionLocations: 'No hay ubicaciones de producción en este grupo.', scopeQuantities: 'Cantidades de Alcance', noAllocatedScope: 'No hay cantidades de alcance asignadas a esta ubicación.',
    added: '{name} fue agregada a la estructura de ubicaciones.', updated: '{name} fue actualizada.', deleted: '{name} fue eliminada de la estructura de ubicaciones.', deleteSingle: '¿Eliminar {name}? Esta acción no se puede deshacer.', deleteTree: '¿Eliminar {name}? Esto también eliminará {count} {locationWord} contenida(s). Esta acción no se puede deshacer.', containedLocation: 'ubicación', containedLocations: 'ubicaciones', deleteFailed: 'No se pudo eliminar la estructura de ubicaciones.', editLocation: 'Editar Ubicación', createLocation: 'Crear Ubicación',
    building: 'Edificio', floor: 'División / Piso', zone: 'Zona / Área', area: 'Área', room: 'Ambiente', custom: 'Personalizado'
  }
}

export function getLocationWorkspaceCopy(locale = 'en-US') {
  return copy[locale] || copy['en-US']
}

export function interpolateLocationCopy(value, variables = {}) {
  return String(value || '').replace(/\{(\w+)\}/g, (_, key) => variables[key] ?? '')
}
