const copy = {
  'en-US': {
    portfolioEyebrow: 'PLANNING & PRODUCTION CONTROL', portfolioTitle: 'Master Plan', portfolioHelp: 'Select a project to access its Master Plan.', portfolioEmpty: 'No projects are available for Master Plan.', projectCover: 'PROJECT COVER', unassigned: 'UNASSIGNED', projectLabel: 'PROJECT', clientNotAssigned: 'Client not assigned', locationNotAssigned: 'Location not assigned', overallProgress: 'Overall Progress', productionDataUnavailable: 'Production Control data not available yet.', productionNotStarted: 'Production scope available. Field production has not started yet.', openProject: 'Open Project', projectImageSuffix: 'project', completedScopeItems: (completed, total) => `${completed} of ${total} scope items completed.`, scopeItemsInProgress: (count) => `${count} scope item${count === 1 ? '' : 's'} in progress.`,
    masterPlanLabel: 'MASTER PLAN', activityHeader: 'ACTIVITY', locationsWord: 'locations', activitiesWord: 'activities', rowIdLabel: 'Row ID', updateScenarioTitle: 'Update current scenario', duplicateScenarioTitle: 'Create a copy of this scenario'
  },
  'pt-BR': {
    portfolioEyebrow: 'PLANEJAMENTO E CONTROLE DA PRODUÇÃO', portfolioTitle: 'Plano Mestre', portfolioHelp: 'Selecione um projeto para acessar seu Plano Mestre.', portfolioEmpty: 'Nenhum projeto está disponível para o Plano Mestre.', projectCover: 'CAPA DO PROJETO', unassigned: 'NÃO ATRIBUÍDO', projectLabel: 'PROJETO', clientNotAssigned: 'Cliente não atribuído', locationNotAssigned: 'Localização não atribuída', overallProgress: 'Progresso Geral', productionDataUnavailable: 'Dados do Controle da Produção ainda não estão disponíveis.', productionNotStarted: 'O escopo de produção está disponível. A produção em campo ainda não foi iniciada.', openProject: 'Abrir Projeto', projectImageSuffix: 'projeto', completedScopeItems: (completed, total) => `${completed} de ${total} itens de escopo concluídos.`, scopeItemsInProgress: (count) => `${count} ${count === 1 ? 'item de escopo em andamento' : 'itens de escopo em andamento'}.`,
    masterPlanLabel: 'PLANO MESTRE', activityHeader: 'ATIVIDADE', locationsWord: 'localizações', activitiesWord: 'atividades', rowIdLabel: 'ID da Linha', updateScenarioTitle: 'Atualizar cenário atual', duplicateScenarioTitle: 'Criar uma cópia deste cenário'
  },
  es: {
    portfolioEyebrow: 'PLANIFICACIÓN Y CONTROL DE PRODUCCIÓN', portfolioTitle: 'Plan Maestro', portfolioHelp: 'Selecciona un proyecto para acceder a su Plan Maestro.', portfolioEmpty: 'No hay proyectos disponibles para el Plan Maestro.', projectCover: 'PORTADA DEL PROYECTO', unassigned: 'NO ASIGNADO', projectLabel: 'PROYECTO', clientNotAssigned: 'Cliente no asignado', locationNotAssigned: 'Ubicación no asignada', overallProgress: 'Progreso General', productionDataUnavailable: 'Los datos de Control de Producción aún no están disponibles.', productionNotStarted: 'El alcance de producción está disponible. La producción en campo aún no ha comenzado.', openProject: 'Abrir Proyecto', projectImageSuffix: 'proyecto', completedScopeItems: (completed, total) => `${completed} de ${total} ítems de alcance completados.`, scopeItemsInProgress: (count) => `${count} ${count === 1 ? 'ítem de alcance en progreso' : 'ítems de alcance en progreso'}.`,
    masterPlanLabel: 'PLAN MAESTRO', activityHeader: 'ACTIVIDAD', locationsWord: 'ubicaciones', activitiesWord: 'actividades', rowIdLabel: 'ID de Fila', updateScenarioTitle: 'Actualizar escenario actual', duplicateScenarioTitle: 'Crear una copia de este escenario'
  }
}

export function getMasterPlanPortfolioCopy(locale = 'en-US') {
  return copy[locale] || copy['en-US']
}
