const copy = {
  'en-US': {
    unexpectedError: 'An unexpected error occurred.', duplicate: 'Production Parameters already exist for this Scope Item.', invalidProjectInfo: 'This production parameter is connected to invalid project information.', invalidRules: 'The production parameter does not satisfy the project rules.', permissionDenied: 'Your account does not have permission to perform this action.', operationFailed: 'The requested operation could not be completed.',
    scopeItems: 'Scope Items', activeProjectScope: 'Active project scope', configured: 'Configured', configuredDetail: 'Productivity + workforce defined', pending: 'Pending', pendingDetail: 'Parameters still to define', title: 'Production Parameters', description: 'Define one project-wide production parameter set for each Scope Item. These values form the calculation database used later to derive raw activity durations from allocated quantities. Takt standardization is intentionally handled in the planning stage, not here.', searchPlaceholder: 'Search Work Packages or Scope Items...', searchAria: 'Search Production Parameters', noScopeItems: 'No Scope Items available.', noScopeItemsHelp: 'Define the project Scope before establishing Production Parameters.',
    workPackage: 'Work Package', scopeItem: 'Scope Item', unit: 'Unit', productivity: 'Productivity', basis: 'Basis', effectiveWorkforce: 'Effective Workforce', productionCapacity: 'Production Capacity', workerDay: 'Worker-day', workerHour: 'Worker-hour', crewDay: 'Crew-day', crewHour: 'Crew-hour', saving: 'Saving...', save: 'Save', clear: 'Clear',
    cleared: '{name} production parameters were cleared.', saved: '{name} production parameters were saved.', productivityGreaterThanZero: 'Enter a Productivity greater than zero for {name}.', workforceGreaterThanZero: 'Enter an Effective Workforce greater than zero for {name}.'
  },
  'pt-BR': {
    unexpectedError: 'Ocorreu um erro inesperado.', duplicate: 'Já existem Parâmetros de Produção para este Item de Escopo.', invalidProjectInfo: 'Este parâmetro de produção está conectado a informações inválidas do projeto.', invalidRules: 'O parâmetro de produção não atende às regras do projeto.', permissionDenied: 'Sua conta não tem permissão para executar esta ação.', operationFailed: 'Não foi possível concluir a operação solicitada.',
    scopeItems: 'Itens de Escopo', activeProjectScope: 'Escopo ativo do projeto', configured: 'Configurados', configuredDetail: 'Produtividade + mão de obra definidas', pending: 'Pendentes', pendingDetail: 'Parâmetros ainda a definir', title: 'Parâmetros de Produção', description: 'Defina um conjunto de parâmetros de produção para todo o projeto para cada Item de Escopo. Esses valores formam a base de cálculo utilizada posteriormente para determinar as durações brutas das atividades a partir das quantidades alocadas. A padronização por Takt é tratada intencionalmente na etapa de planejamento, e não aqui.', searchPlaceholder: 'Pesquisar Pacotes de Trabalho ou Itens de Escopo...', searchAria: 'Pesquisar Parâmetros de Produção', noScopeItems: 'Nenhum Item de Escopo disponível.', noScopeItemsHelp: 'Defina o Escopo do projeto antes de estabelecer os Parâmetros de Produção.',
    workPackage: 'Pacote de Trabalho', scopeItem: 'Item de Escopo', unit: 'Unidade', productivity: 'Produtividade', basis: 'Base', effectiveWorkforce: 'Mão de Obra Efetiva', productionCapacity: 'Capacidade de Produção', workerDay: 'Trabalhador-dia', workerHour: 'Trabalhador-hora', crewDay: 'Equipe-dia', crewHour: 'Equipe-hora', saving: 'Salvando...', save: 'Salvar', clear: 'Limpar',
    cleared: 'Os parâmetros de produção de {name} foram removidos.', saved: 'Os parâmetros de produção de {name} foram salvos.', productivityGreaterThanZero: 'Informe uma Produtividade maior que zero para {name}.', workforceGreaterThanZero: 'Informe uma Mão de Obra Efetiva maior que zero para {name}.'
  },
  es: {
    unexpectedError: 'Ocurrió un error inesperado.', duplicate: 'Ya existen Parámetros de Producción para este Ítem de Alcance.', invalidProjectInfo: 'Este parámetro de producción está conectado con información inválida del proyecto.', invalidRules: 'El parámetro de producción no cumple las reglas del proyecto.', permissionDenied: 'Tu cuenta no tiene permiso para realizar esta acción.', operationFailed: 'No se pudo completar la operación solicitada.',
    scopeItems: 'Ítems de Alcance', activeProjectScope: 'Alcance activo del proyecto', configured: 'Configurados', configuredDetail: 'Productividad + mano de obra definidas', pending: 'Pendientes', pendingDetail: 'Parámetros aún por definir', title: 'Parámetros de Producción', description: 'Define un conjunto de parámetros de producción para todo el proyecto para cada Ítem de Alcance. Estos valores forman la base de cálculo utilizada posteriormente para determinar las duraciones brutas de las actividades a partir de las cantidades asignadas. La estandarización por Takt se gestiona intencionalmente en la etapa de planificación, no aquí.', searchPlaceholder: 'Buscar Paquetes de Trabajo o Ítems de Alcance...', searchAria: 'Buscar Parámetros de Producción', noScopeItems: 'No hay Ítems de Alcance disponibles.', noScopeItemsHelp: 'Define el Alcance del proyecto antes de establecer los Parámetros de Producción.',
    workPackage: 'Paquete de Trabajo', scopeItem: 'Ítem de Alcance', unit: 'Unidad', productivity: 'Productividad', basis: 'Base', effectiveWorkforce: 'Mano de Obra Efectiva', productionCapacity: 'Capacidad de Producción', workerDay: 'Trabajador-día', workerHour: 'Trabajador-hora', crewDay: 'Equipo-día', crewHour: 'Equipo-hora', saving: 'Guardando...', save: 'Guardar', clear: 'Limpiar',
    cleared: 'Los parámetros de producción de {name} fueron eliminados.', saved: 'Los parámetros de producción de {name} fueron guardados.', productivityGreaterThanZero: 'Ingresa una Productividad mayor que cero para {name}.', workforceGreaterThanZero: 'Ingresa una Mano de Obra Efectiva mayor que cero para {name}.'
  }
}

export function getProductionParametersCopy(locale = 'en-US') {
  return copy[locale] || copy['en-US']
}

export function interpolateProductionParametersCopy(value, variables = {}) {
  return String(value || '').replace(/\{(\w+)\}/g, (_, key) => variables[key] ?? '')
}
