const PROJECT_FORM = {
  'en-US': {
    clientName:'Client', contractValue:'Contract value', planning:'Planning', active:'Active', onHold:'On hold', completed:'Completed', archived:'Archived', cancel:'Cancel',
    formDescription:'Define the project identity, presentation, commercial references, planned dates, and geographic information.', identityHelp:'Core information used throughout the planning workflow.', clientPlaceholder:'Client or owner',
    coverHelp:'Define the project image used in Daily Reports, project cards, dashboards, and project workspaces.', loadingCover:'Loading project image...', noCover:'No project cover', noCoverHelp:'Add a field or construction image to visually identify this project.', coverPhoto:'Project cover photo', coverRequirements:'Recommended: landscape orientation. JPEG, PNG, WebP, HEIC or HEIF. Maximum file size 20 MB.', createBeforeCover:'Create the project first. After creation, return to Project Setup to add its cover image.',
    contractHelp:'Optional project references and planned boundaries.', locationHelp:'Geographic information used for project identification and reporting.', addressPlaceholder:'Street and number', countryHelp:'Use the two-letter ISO country code.',
    geofenceHelp:'Define the jobsite reference point and allowed radius used to validate Attendance Check-In and Check-Out locations.', latitudeHelp:'Decimal degrees between -90 and 90.', longitudeHelp:'Decimal degrees between -180 and 180.', geofenceRadiusHelp:'Maximum allowed distance from the reference point, in meters.', gpsAccuracyHelp:'Maximum acceptable device GPS accuracy, in meters. Leave blank to disable the project-specific accuracy threshold.', geofenceToggleHelp:'When enabled, RitsuFlow will compare worker GPS coordinates with this project reference point during Check-In and Check-Out.', geofenceEnabled:'Attendance Geofence is enabled. Check-In and Check-Out location validation will use the configured coordinates and radius.', geofenceDisabled:'Attendance Geofence is disabled. Attendance can continue without project distance validation until this setting is enabled.',
    createFirstCover:'Create the project first. You can then add its cover photo from Project Setup.', coverTypeInvalid:'Use a JPEG, PNG, WebP, HEIC, or HEIF image.', coverTooLarge:'The project cover image cannot exceed 20 MB.', coverLoadError:'The current project cover could not be displayed.', coverUploaded:'Project cover updated successfully.', coverRemoved:'Project cover removed.', unableUploadCover:'The project cover could not be uploaded.', unableRemoveCover:'The project cover could not be removed.', removeCoverConfirm:'Remove the project cover photo?',
    invalidContractValue:'Contract value must be a valid non-negative number.', invalidDates:'Planned finish date cannot be earlier than the planned start date.', invalidLatitude:'Reference latitude must be a valid number between -90 and 90.', invalidLongitude:'Reference longitude must be a valid number between -180 and 180.', invalidGeofenceRadius:'Geofence radius must be a positive whole number of meters.', invalidGpsAccuracy:'Maximum GPS accuracy must be a positive whole number of meters.', geofenceRequired:'Reference latitude, reference longitude, and geofence radius are required before Attendance Geofence can be enabled.', duplicateCode:'This project code is already in use. Choose another code.', unableSave:'The project could not be saved.', projectCoverAlt:'{name} cover'
  },
  'pt-BR': {
    clientName:'Cliente', contractValue:'Valor do contrato', planning:'Planejamento', active:'Ativo', onHold:'Em espera', completed:'Concluído', archived:'Arquivado', cancel:'Cancelar',
    formDescription:'Defina a identidade, apresentação, referências comerciais, datas planejadas e informações geográficas do projeto.', identityHelp:'Informações essenciais utilizadas em todo o fluxo de planejamento.', clientPlaceholder:'Cliente ou proprietário',
    coverHelp:'Defina a imagem do projeto utilizada nos Relatórios Diários, cards, dashboards e workspaces do projeto.', loadingCover:'Carregando imagem do projeto...', noCover:'Sem capa do projeto', noCoverHelp:'Adicione uma imagem de campo ou da construção para identificar visualmente este projeto.', coverPhoto:'Foto de capa do projeto', coverRequirements:'Recomendado: orientação horizontal. JPEG, PNG, WebP, HEIC ou HEIF. Tamanho máximo de 20 MB.', createBeforeCover:'Crie o projeto primeiro. Após a criação, retorne à Configuração do Projeto para adicionar a imagem de capa.',
    contractHelp:'Referências opcionais do projeto e limites planejados.', locationHelp:'Informações geográficas utilizadas para identificação e relatórios do projeto.', addressPlaceholder:'Rua e número', countryHelp:'Use o código ISO de duas letras do país.',
    geofenceHelp:'Defina o ponto de referência da obra e o raio permitido para validar as localizações de Check-In e Check-Out de Presença.', latitudeHelp:'Graus decimais entre -90 e 90.', longitudeHelp:'Graus decimais entre -180 e 180.', geofenceRadiusHelp:'Distância máxima permitida do ponto de referência, em metros.', gpsAccuracyHelp:'Precisão máxima aceitável do GPS do dispositivo, em metros. Deixe em branco para desabilitar o limite específico do projeto.', geofenceToggleHelp:'Quando habilitada, o RitsuFlow comparará as coordenadas GPS do trabalhador com o ponto de referência deste projeto durante o Check-In e Check-Out.', geofenceEnabled:'A Geofence de Presença está habilitada. A validação de localização no Check-In e Check-Out usará as coordenadas e o raio configurados.', geofenceDisabled:'A Geofence de Presença está desabilitada. A presença pode continuar sem validação de distância do projeto até que esta configuração seja habilitada.',
    createFirstCover:'Crie o projeto primeiro. Depois você poderá adicionar a foto de capa pela Configuração do Projeto.', coverTypeInvalid:'Use uma imagem JPEG, PNG, WebP, HEIC ou HEIF.', coverTooLarge:'A imagem de capa do projeto não pode exceder 20 MB.', coverLoadError:'A capa atual do projeto não pôde ser exibida.', coverUploaded:'Capa do projeto atualizada com sucesso.', coverRemoved:'Capa do projeto removida.', unableUploadCover:'Não foi possível enviar a capa do projeto.', unableRemoveCover:'Não foi possível remover a capa do projeto.', removeCoverConfirm:'Remover a foto de capa do projeto?',
    invalidContractValue:'O valor do contrato deve ser um número válido e não negativo.', invalidDates:'A data de término planejada não pode ser anterior à data de início planejada.', invalidLatitude:'A latitude de referência deve ser um número válido entre -90 e 90.', invalidLongitude:'A longitude de referência deve ser um número válido entre -180 e 180.', invalidGeofenceRadius:'O raio da geofence deve ser um número inteiro positivo de metros.', invalidGpsAccuracy:'A precisão máxima do GPS deve ser um número inteiro positivo de metros.', geofenceRequired:'Latitude de referência, longitude de referência e raio da geofence são obrigatórios antes de habilitar a Geofence de Presença.', duplicateCode:'Este código de projeto já está em uso. Escolha outro código.', unableSave:'Não foi possível salvar o projeto.', projectCoverAlt:'Capa de {name}'
  },
  es: {
    clientName:'Cliente', contractValue:'Valor del contrato', planning:'Planificación', active:'Activo', onHold:'En espera', completed:'Completado', archived:'Archivado', cancel:'Cancelar',
    formDescription:'Defina la identidad, presentación, referencias comerciales, fechas planificadas e información geográfica del proyecto.', identityHelp:'Información esencial utilizada en todo el flujo de planificación.', clientPlaceholder:'Cliente o propietario',
    coverHelp:'Defina la imagen del proyecto utilizada en Informes Diarios, tarjetas, paneles y espacios de trabajo del proyecto.', loadingCover:'Cargando imagen del proyecto...', noCover:'Sin portada del proyecto', noCoverHelp:'Agregue una imagen de campo o construcción para identificar visualmente este proyecto.', coverPhoto:'Foto de portada del proyecto', coverRequirements:'Recomendado: orientación horizontal. JPEG, PNG, WebP, HEIC o HEIF. Tamaño máximo de 20 MB.', createBeforeCover:'Cree primero el proyecto. Después de crearlo, vuelva a Configuración del Proyecto para agregar su imagen de portada.',
    contractHelp:'Referencias opcionales del proyecto y límites planificados.', locationHelp:'Información geográfica utilizada para identificación e informes del proyecto.', addressPlaceholder:'Calle y número', countryHelp:'Use el código ISO de dos letras del país.',
    geofenceHelp:'Defina el punto de referencia de la obra y el radio permitido para validar las ubicaciones de Check-In y Check-Out de Asistencia.', latitudeHelp:'Grados decimales entre -90 y 90.', longitudeHelp:'Grados decimales entre -180 y 180.', geofenceRadiusHelp:'Distancia máxima permitida desde el punto de referencia, en metros.', gpsAccuracyHelp:'Precisión máxima aceptable del GPS del dispositivo, en metros. Déjelo en blanco para desactivar el límite específico del proyecto.', geofenceToggleHelp:'Cuando está habilitada, RitsuFlow comparará las coordenadas GPS del trabajador con el punto de referencia de este proyecto durante el Check-In y Check-Out.', geofenceEnabled:'La Geocerca de Asistencia está habilitada. La validación de ubicación en Check-In y Check-Out utilizará las coordenadas y el radio configurados.', geofenceDisabled:'La Geocerca de Asistencia está deshabilitada. La asistencia puede continuar sin validación de distancia del proyecto hasta que se habilite esta configuración.',
    createFirstCover:'Cree primero el proyecto. Luego podrá agregar su foto de portada desde Configuración del Proyecto.', coverTypeInvalid:'Use una imagen JPEG, PNG, WebP, HEIC o HEIF.', coverTooLarge:'La imagen de portada del proyecto no puede superar los 20 MB.', coverLoadError:'No se pudo mostrar la portada actual del proyecto.', coverUploaded:'Portada del proyecto actualizada correctamente.', coverRemoved:'Portada del proyecto eliminada.', unableUploadCover:'No se pudo subir la portada del proyecto.', unableRemoveCover:'No se pudo eliminar la portada del proyecto.', removeCoverConfirm:'¿Eliminar la foto de portada del proyecto?',
    invalidContractValue:'El valor del contrato debe ser un número válido no negativo.', invalidDates:'La fecha de finalización planificada no puede ser anterior a la fecha de inicio planificada.', invalidLatitude:'La latitud de referencia debe ser un número válido entre -90 y 90.', invalidLongitude:'La longitud de referencia debe ser un número válido entre -180 y 180.', invalidGeofenceRadius:'El radio de la geocerca debe ser un número entero positivo de metros.', invalidGpsAccuracy:'La precisión máxima del GPS debe ser un número entero positivo de metros.', geofenceRequired:'La latitud de referencia, longitud de referencia y radio de geocerca son obligatorios antes de habilitar la Geocerca de Asistencia.', duplicateCode:'Este código de proyecto ya está en uso. Elija otro código.', unableSave:'No se pudo guardar el proyecto.', projectCoverAlt:'Portada de {name}'
  }
}

export function projectFormCopy(locale = 'en-US') {
  const copy = PROJECT_FORM[locale] ?? PROJECT_FORM['en-US']
  return (key, vars = {}) => {
    let value = copy[key] ?? PROJECT_FORM['en-US'][key] ?? key
    for (const [name, replacement] of Object.entries(vars)) value = String(value).replaceAll(`{${name}}`, String(replacement))
    return value
  }
}

export function projectFormDictionary(locale = 'en-US') {
  return PROJECT_FORM[locale] ?? PROJECT_FORM['en-US']
}
