const PROJECT_FORM = {
  'en-US': {
    clientName:'Client name', contractValue:'Contract value', planning:'Planning', onHold:'On hold', saveChanges:'Save changes', saving:'Saving...', projectUpdated:'Project updated successfully.', projectCreated:'Project created successfully.', unableSave:'Unable to save the project: {error}', codeRequired:'Project code is required.', nameRequired:'Project name is required.', invalidContractValue:'Contract value must be a valid number.', invalidLatitude:'Latitude must be between -90 and 90.', invalidLongitude:'Longitude must be between -180 and 180.', invalidGeofenceRadius:'Geofence radius must be a positive number.', invalidGpsAccuracy:'Maximum GPS accuracy must be a positive number.', coverRequirements:'JPEG, PNG, WebP, HEIC or HEIF. Maximum file size: 20 MB.', coverTooLarge:'The selected image exceeds the 20 MB limit.', coverTypeInvalid:'Select a JPEG, PNG, WebP, HEIC or HEIF image.', coverUploaded:'Project cover uploaded successfully.', coverRemoved:'Project cover removed successfully.', unableUploadCover:'Unable to upload the project cover: {error}', unableRemoveCover:'Unable to remove the project cover: {error}', removeCoverConfirm:'Remove the current project cover?', latitudeHelp:'Decimal degrees from -90 to 90.', longitudeHelp:'Decimal degrees from -180 to 180.', geofenceRadiusHelp:'Allowed distance from the project reference point, in meters.', gpsAccuracyHelp:'GPS readings less accurate than this value can be rejected.', geofenceHelp:'When enabled, attendance check-in can validate the worker position against this project location.', optional:'Optional', meters:'meters', projectDetails:'Project details', geographicInformation:'Geographic information'
  },
  'pt-BR': {
    clientName:'Nome do cliente', contractValue:'Valor do contrato', planning:'Planejamento', onHold:'Em espera', saveChanges:'Salvar alterações', saving:'Salvando...', projectUpdated:'Projeto atualizado com sucesso.', projectCreated:'Projeto criado com sucesso.', unableSave:'Não foi possível salvar o projeto: {error}', codeRequired:'O código do projeto é obrigatório.', nameRequired:'O nome do projeto é obrigatório.', invalidContractValue:'O valor do contrato deve ser um número válido.', invalidLatitude:'A latitude deve estar entre -90 e 90.', invalidLongitude:'A longitude deve estar entre -180 e 180.', invalidGeofenceRadius:'O raio da geofence deve ser um número positivo.', invalidGpsAccuracy:'A precisão máxima do GPS deve ser um número positivo.', coverRequirements:'JPEG, PNG, WebP, HEIC ou HEIF. Tamanho máximo do arquivo: 20 MB.', coverTooLarge:'A imagem selecionada excede o limite de 20 MB.', coverTypeInvalid:'Selecione uma imagem JPEG, PNG, WebP, HEIC ou HEIF.', coverUploaded:'Capa do projeto enviada com sucesso.', coverRemoved:'Capa do projeto removida com sucesso.', unableUploadCover:'Não foi possível enviar a capa do projeto: {error}', unableRemoveCover:'Não foi possível remover a capa do projeto: {error}', removeCoverConfirm:'Remover a capa atual do projeto?', latitudeHelp:'Graus decimais de -90 a 90.', longitudeHelp:'Graus decimais de -180 a 180.', geofenceRadiusHelp:'Distância permitida do ponto de referência do projeto, em metros.', gpsAccuracyHelp:'Leituras de GPS com precisão inferior a este valor podem ser rejeitadas.', geofenceHelp:'Quando habilitada, a marcação de presença pode validar a posição do trabalhador em relação à localização deste projeto.', optional:'Opcional', meters:'metros', projectDetails:'Detalhes do projeto', geographicInformation:'Informações geográficas'
  },
  es: {
    clientName:'Nombre del cliente', contractValue:'Valor del contrato', planning:'Planificación', onHold:'En espera', saveChanges:'Guardar cambios', saving:'Guardando...', projectUpdated:'Proyecto actualizado correctamente.', projectCreated:'Proyecto creado correctamente.', unableSave:'No se pudo guardar el proyecto: {error}', codeRequired:'El código del proyecto es obligatorio.', nameRequired:'El nombre del proyecto es obligatorio.', invalidContractValue:'El valor del contrato debe ser un número válido.', invalidLatitude:'La latitud debe estar entre -90 y 90.', invalidLongitude:'La longitud debe estar entre -180 y 180.', invalidGeofenceRadius:'El radio de la geocerca debe ser un número positivo.', invalidGpsAccuracy:'La precisión máxima del GPS debe ser un número positivo.', coverRequirements:'JPEG, PNG, WebP, HEIC o HEIF. Tamaño máximo del archivo: 20 MB.', coverTooLarge:'La imagen seleccionada supera el límite de 20 MB.', coverTypeInvalid:'Seleccione una imagen JPEG, PNG, WebP, HEIC o HEIF.', coverUploaded:'Portada del proyecto subida correctamente.', coverRemoved:'Portada del proyecto eliminada correctamente.', unableUploadCover:'No se pudo subir la portada del proyecto: {error}', unableRemoveCover:'No se pudo eliminar la portada del proyecto: {error}', removeCoverConfirm:'¿Eliminar la portada actual del proyecto?', latitudeHelp:'Grados decimales de -90 a 90.', longitudeHelp:'Grados decimales de -180 a 180.', geofenceRadiusHelp:'Distancia permitida desde el punto de referencia del proyecto, en metros.', gpsAccuracyHelp:'Las lecturas GPS menos precisas que este valor pueden rechazarse.', geofenceHelp:'Cuando está habilitada, la marcación de asistencia puede validar la posición del trabajador respecto a la ubicación de este proyecto.', optional:'Opcional', meters:'metros', projectDetails:'Detalles del proyecto', geographicInformation:'Información geográfica'
  }
}

export function projectFormCopy(locale = 'en-US') {
  const copy = PROJECT_FORM[locale] ?? PROJECT_FORM['en-US']
  return (key, vars = {}) => {
    let value = copy[key] ?? PROJECT_FORM['en-US'][key] ?? key
    for (const [name, replacement] of Object.entries(vars)) value = String(value).replaceAll(`{${name}}`, String(replacement))
    return value
  }
}

export function projectFormDictionary(locale = 'en-US') {
  return PROJECT_FORM[locale] ?? PROJECT_FORM['en-US']
}
