const copy = {
  'en-US': {
    unexpectedError: 'An unexpected error occurred.', duplicateQuantity: 'A quantity record with the same identifying information already exists.', connectedQuantity: 'This quantity is connected to other project information and cannot be changed.', invalidAllocationRules: 'The quantity does not satisfy the project allocation rules.', permissionDenied: 'Your account does not have permission to perform this action.', operationFailed: 'The requested operation could not be completed.',
    locationTypes: { building: 'Building', floor: 'Floor', zone: 'Zone', area: 'Area', room: 'Room', custom: 'Custom' }, location: 'Location', type: 'Type', division: 'Division', zone: 'Zone', scope: 'Scope',
    title: 'Scope Allocation Matrix', description: "Distribute each Scope Item quantity across the project's production locations. Scope Quantity remains authoritative and the reconciliation above updates after each saved allocation.", searchPlaceholder: 'Search locations or Scope Items...', filterDivision: 'Filter allocation matrix by division', allDivisions: 'All divisions',
    noScopeItems: 'No Scope Items available.', noScopeItemsHelp: 'Define the project Scope Breakdown Structure before allocating quantities.', noLocations: 'No production locations available.', noLocationsHelp: 'Define the physical production hierarchy before allocating Scope Item quantities.',
    quantityCleared: 'Allocation quantity was cleared.', quantityUpdated: 'Allocation quantity was updated.', quantitySaved: 'Allocation quantity was saved.', invalidQuantity: 'Enter a valid quantity greater than or equal to zero.', saving: 'Saving...',
    quantification: 'Quantification by Division / Zone', quantificationHelp: 'Review allocated quantities summarized by Division and Zone.', showQuantification: 'Show Quantification', hideQuantification: 'Hide Quantification', scopeItem: 'Scope Item', total: 'Total', allocated: 'Allocated', remaining: 'Remaining', status: 'Status', reconciled: 'Reconciled', overAllocated: 'Over allocated', underAllocated: 'Under allocated', noAllocation: 'No allocation',
  },
  'pt-BR': {
    unexpectedError: 'Ocorreu um erro inesperado.', duplicateQuantity: 'Já existe um registro de quantidade com as mesmas informações de identificação.', connectedQuantity: 'Esta quantidade está conectada a outras informações do projeto e não pode ser alterada.', invalidAllocationRules: 'A quantidade não atende às regras de alocação do projeto.', permissionDenied: 'Sua conta não tem permissão para executar esta ação.', operationFailed: 'Não foi possível concluir a operação solicitada.',
    locationTypes: { building: 'Edifício', floor: 'Pavimento', zone: 'Zona', area: 'Área', room: 'Ambiente', custom: 'Personalizado' }, location: 'Localização', type: 'Tipo', division: 'Divisão', zone: 'Zona', scope: 'Escopo',
    title: 'Matriz de Alocação do Escopo', description: 'Distribua a quantidade de cada Item de Escopo entre as localizações de produção do projeto. A Quantidade de Escopo permanece como referência oficial e a reconciliação acima é atualizada após cada alocação salva.', searchPlaceholder: 'Pesquisar localizações ou Itens de Escopo...', filterDivision: 'Filtrar matriz de alocação por divisão', allDivisions: 'Todas as divisões',
    noScopeItems: 'Nenhum Item de Escopo disponível.', noScopeItemsHelp: 'Defina a Estrutura Analítica do Escopo do projeto antes de alocar quantidades.', noLocations: 'Nenhuma localização de produção disponível.', noLocationsHelp: 'Defina a hierarquia física de produção antes de alocar as quantidades dos Itens de Escopo.',
    quantityCleared: 'A quantidade alocada foi removida.', quantityUpdated: 'A quantidade alocada foi atualizada.', quantitySaved: 'A quantidade alocada foi salva.', invalidQuantity: 'Informe uma quantidade válida, maior ou igual a zero.', saving: 'Salvando...',
    quantification: 'Quantificação por Divisão / Zona', quantificationHelp: 'Revise as quantidades alocadas resumidas por Divisão e Zona.', showQuantification: 'Mostrar Quantificação', hideQuantification: 'Ocultar Quantificação', scopeItem: 'Item de Escopo', total: 'Total', allocated: 'Alocado', remaining: 'Restante', status: 'Status', reconciled: 'Reconciliado', overAllocated: 'Alocação excedida', underAllocated: 'Alocação insuficiente', noAllocation: 'Sem alocação',
  },
  es: {
    unexpectedError: 'Ocurrió un error inesperado.', duplicateQuantity: 'Ya existe un registro de cantidad con la misma información de identificación.', connectedQuantity: 'Esta cantidad está conectada con otra información del proyecto y no puede modificarse.', invalidAllocationRules: 'La cantidad no cumple las reglas de asignación del proyecto.', permissionDenied: 'Tu cuenta no tiene permiso para realizar esta acción.', operationFailed: 'No se pudo completar la operación solicitada.',
    locationTypes: { building: 'Edificio', floor: 'Piso', zone: 'Zona', area: 'Área', room: 'Ambiente', custom: 'Personalizado' }, location: 'Ubicación', type: 'Tipo', division: 'División', zone: 'Zona', scope: 'Alcance',
    title: 'Matriz de Asignación del Alcance', description: 'Distribuye la cantidad de cada Ítem de Alcance entre las ubicaciones de producción del proyecto. La Cantidad de Alcance permanece como referencia oficial y la conciliación anterior se actualiza después de cada asignación guardada.', searchPlaceholder: 'Buscar ubicaciones o Ítems de Alcance...', filterDivision: 'Filtrar matriz de asignación por división', allDivisions: 'Todas las divisiones',
    noScopeItems: 'No hay Ítems de Alcance disponibles.', noScopeItemsHelp: 'Define la Estructura de Desglose del Alcance del proyecto antes de asignar cantidades.', noLocations: 'No hay ubicaciones de producción disponibles.', noLocationsHelp: 'Define la jerarquía física de producción antes de asignar las cantidades de los Ítems de Alcance.',
    quantityCleared: 'La cantidad asignada fue eliminada.', quantityUpdated: 'La cantidad asignada fue actualizada.', quantitySaved: 'La cantidad asignada fue guardada.', invalidQuantity: 'Ingresa una cantidad válida, mayor o igual a cero.', saving: 'Guardando...',
    quantification: 'Cuantificación por División / Zona', quantificationHelp: 'Revisa las cantidades asignadas resumidas por División y Zona.', showQuantification: 'Mostrar Cuantificación', hideQuantification: 'Ocultar Cuantificación', scopeItem: 'Ítem de Alcance', total: 'Total', allocated: 'Asignado', remaining: 'Restante', status: 'Estado', reconciled: 'Conciliado', overAllocated: 'Asignación excedida', underAllocated: 'Asignación insuficiente', noAllocation: 'Sin asignación',
  },
}

export function getQuantityAllocationCopy(locale = 'en-US') {
  return copy[locale] || copy['en-US']
}
