const copy = {
  'en-US': {
    unexpectedError: 'An unexpected error occurred.', duplicateRecord: 'A record with the same identifying information already exists.', referencedRecord: 'This record is already referenced by other project information and cannot be deleted.', invalidScopeRules: 'One or more values do not satisfy the project scope rules.', permissionDenied: 'Your account does not have permission to perform this action.', operationFailed: 'The requested operation could not be completed.',
    workPackages: 'Work Packages', activeScopeGroups: 'Active scope groups', scopeItems: 'Scope Items', projectDeliverables: 'Project deliverables', packageAssignment: 'Package Assignment', scopeItemsClassified: 'Scope Items classified', scopeCost: 'Scope Cost', scopeDefinition: 'Scope Definition', complete: 'Complete', incomplete: 'Incomplete', ready: 'READY', actionRequired: 'ACTION REQUIRED', projectScope: 'Project Scope', projectScopeHelp: 'Define Work Packages and the Scope Items contained within each package. Work Packages represent scope. Planning buffers and time lags are managed by the scheduling model rather than the Scope Breakdown Structure.', addWorkPackage: '+ Work Package', addScopeItem: '+ Scope Item', startSbs: 'Start the Scope Breakdown Structure.', startSbsHelp: 'Create the first Work Package, then add the Scope Items that define what the project must deliver.', createFirstWorkPackage: '+ Create first Work Package', noScopeItemsAssigned: 'No Scope Items have been assigned to this Work Package.', scopeItem: 'Scope Item', unit: 'Unit', scopeQuantity: 'Scope Quantity', unitCost: 'Unit Cost', totalCost: 'Total Cost', status: 'Status', actions: 'Actions', noCode: 'No code', edit: 'Edit', archive: 'Archive', delete: 'Delete', deleting: 'Deleting...', addScopeItemButton: '+ Add Scope Item', unassigned: 'Unassigned', saving: 'Saving...', cancel: 'Cancel', save: 'Save', create: 'Create', description: 'Description', code: 'Code', customUnit: 'Custom unit', selectWorkPackage: 'Select a Work Package', other: 'Other',
    wpCodeThreeLetters: 'Work Package code must contain exactly three letters.', enterWpDescription: 'Enter a Work Package description.', enterScopeDescription: 'Enter a Scope Item description.', enterCustomUnit: 'Enter a custom unit.', invalidQuantity: 'Enter a valid Scope Quantity greater than or equal to zero.', invalidUnitCost: 'Enter a valid Unit Cost greater than or equal to zero.', duplicateScopeDescription: 'A Scope Item with this description already exists in the project.', duplicateScopeCode: 'A Scope Item with this code already exists in the project.', assignedNotice: 'Scope Item was assigned to its Work Package.', deleteWpTitle: 'Delete Work Package', reassignBeforeDelete: 'Reassign Scope Items before deleting this Work Package.'
  },
  'pt-BR': {
    unexpectedError: 'Ocorreu um erro inesperado.', duplicateRecord: 'Já existe um registro com as mesmas informações de identificação.', referencedRecord: 'Este registro já é referenciado por outras informações do projeto e não pode ser excluído.', invalidScopeRules: 'Um ou mais valores não atendem às regras de escopo do projeto.', permissionDenied: 'Sua conta não tem permissão para executar esta ação.', operationFailed: 'Não foi possível concluir a operação solicitada.',
    workPackages: 'Pacotes de Trabalho', activeScopeGroups: 'Grupos de escopo ativos', scopeItems: 'Itens de Escopo', projectDeliverables: 'Entregáveis do projeto', packageAssignment: 'Classificação por Pacote', scopeItemsClassified: 'Itens de Escopo classificados', scopeCost: 'Custo do Escopo', scopeDefinition: 'Definição do Escopo', complete: 'Completo', incomplete: 'Incompleto', ready: 'PRONTO', actionRequired: 'AÇÃO NECESSÁRIA', projectScope: 'Escopo do Projeto', projectScopeHelp: 'Defina os Pacotes de Trabalho e os Itens de Escopo contidos em cada pacote. Os Pacotes de Trabalho representam o escopo. Buffers de planejamento e defasagens de tempo são gerenciados pelo modelo de programação, e não pela Estrutura Analítica do Escopo.', addWorkPackage: '+ Pacote de Trabalho', addScopeItem: '+ Item de Escopo', startSbs: 'Inicie a Estrutura Analítica do Escopo.', startSbsHelp: 'Crie o primeiro Pacote de Trabalho e depois adicione os Itens de Escopo que definem o que o projeto deve entregar.', createFirstWorkPackage: '+ Criar primeiro Pacote de Trabalho', noScopeItemsAssigned: 'Nenhum Item de Escopo foi atribuído a este Pacote de Trabalho.', scopeItem: 'Item de Escopo', unit: 'Unidade', scopeQuantity: 'Quantidade de Escopo', unitCost: 'Custo Unitário', totalCost: 'Custo Total', status: 'Status', actions: 'Ações', noCode: 'Sem código', edit: 'Editar', archive: 'Arquivar', delete: 'Excluir', deleting: 'Excluindo...', addScopeItemButton: '+ Adicionar Item de Escopo', unassigned: 'Não atribuído', saving: 'Salvando...', cancel: 'Cancelar', save: 'Salvar', create: 'Criar', description: 'Descrição', code: 'Código', customUnit: 'Unidade personalizada', selectWorkPackage: 'Selecione um Pacote de Trabalho', other: 'Outra',
    wpCodeThreeLetters: 'O código do Pacote de Trabalho deve conter exatamente três letras.', enterWpDescription: 'Informe uma descrição para o Pacote de Trabalho.', enterScopeDescription: 'Informe uma descrição para o Item de Escopo.', enterCustomUnit: 'Informe uma unidade personalizada.', invalidQuantity: 'Informe uma Quantidade de Escopo válida, maior ou igual a zero.', invalidUnitCost: 'Informe um Custo Unitário válido, maior ou igual a zero.', duplicateScopeDescription: 'Já existe um Item de Escopo com esta descrição no projeto.', duplicateScopeCode: 'Já existe um Item de Escopo com este código no projeto.', assignedNotice: 'O Item de Escopo foi atribuído ao seu Pacote de Trabalho.', deleteWpTitle: 'Excluir Pacote de Trabalho', reassignBeforeDelete: 'Reatribua os Itens de Escopo antes de excluir este Pacote de Trabalho.'
  },
  es: {
    unexpectedError: 'Ocurrió un error inesperado.', duplicateRecord: 'Ya existe un registro con la misma información de identificación.', referencedRecord: 'Este registro ya está referenciado por otra información del proyecto y no puede eliminarse.', invalidScopeRules: 'Uno o más valores no cumplen las reglas de alcance del proyecto.', permissionDenied: 'Tu cuenta no tiene permiso para realizar esta acción.', operationFailed: 'No se pudo completar la operación solicitada.',
    workPackages: 'Paquetes de Trabajo', activeScopeGroups: 'Grupos de alcance activos', scopeItems: 'Ítems de Alcance', projectDeliverables: 'Entregables del proyecto', packageAssignment: 'Clasificación por Paquete', scopeItemsClassified: 'Ítems de Alcance clasificados', scopeCost: 'Costo del Alcance', scopeDefinition: 'Definición del Alcance', complete: 'Completo', incomplete: 'Incompleto', ready: 'LISTO', actionRequired: 'ACCIÓN REQUERIDA', projectScope: 'Alcance del Proyecto', projectScopeHelp: 'Define los Paquetes de Trabajo y los Ítems de Alcance contenidos en cada paquete. Los Paquetes de Trabajo representan el alcance. Los buffers de planificación y los desfases de tiempo se gestionan mediante el modelo de programación y no mediante la Estructura de Desglose del Alcance.', addWorkPackage: '+ Paquete de Trabajo', addScopeItem: '+ Ítem de Alcance', startSbs: 'Inicia la Estructura de Desglose del Alcance.', startSbsHelp: 'Crea el primer Paquete de Trabajo y luego agrega los Ítems de Alcance que definen lo que el proyecto debe entregar.', createFirstWorkPackage: '+ Crear primer Paquete de Trabajo', noScopeItemsAssigned: 'No se han asignado Ítems de Alcance a este Paquete de Trabajo.', scopeItem: 'Ítem de Alcance', unit: 'Unidad', scopeQuantity: 'Cantidad de Alcance', unitCost: 'Costo Unitario', totalCost: 'Costo Total', status: 'Estado', actions: 'Acciones', noCode: 'Sin código', edit: 'Editar', archive: 'Archivar', delete: 'Eliminar', deleting: 'Eliminando...', addScopeItemButton: '+ Agregar Ítem de Alcance', unassigned: 'Sin asignar', saving: 'Guardando...', cancel: 'Cancelar', save: 'Guardar', create: 'Crear', description: 'Descripción', code: 'Código', customUnit: 'Unidad personalizada', selectWorkPackage: 'Selecciona un Paquete de Trabajo', other: 'Otra',
    wpCodeThreeLetters: 'El código del Paquete de Trabajo debe contener exactamente tres letras.', enterWpDescription: 'Ingresa una descripción para el Paquete de Trabajo.', enterScopeDescription: 'Ingresa una descripción para el Ítem de Alcance.', enterCustomUnit: 'Ingresa una unidad personalizada.', invalidQuantity: 'Ingresa una Cantidad de Alcance válida, mayor o igual a cero.', invalidUnitCost: 'Ingresa un Costo Unitario válido, mayor o igual a cero.', duplicateScopeDescription: 'Ya existe un Ítem de Alcance con esta descripción en el proyecto.', duplicateScopeCode: 'Ya existe un Ítem de Alcance con este código en el proyecto.', assignedNotice: 'El Ítem de Alcance fue asignado a su Paquete de Trabajo.', deleteWpTitle: 'Eliminar Paquete de Trabajo', reassignBeforeDelete: 'Reasigna los Ítems de Alcance antes de eliminar este Paquete de Trabajo.'
  }
}

export function getScopeWorkspaceCopy(locale = 'en-US') {
  return copy[locale] || copy['en-US']
}

export function interpolateScopeCopy(value, variables = {}) {
  return String(value || '').replace(/\{(\w+)\}/g, (_, key) => variables[key] ?? '')
}
