const copy = {
  'en-US': {
    fieldManagement:'Field Management',title:'Workforce Registry',description:'Manage the master worker records available for project assignments, attendance and workforce reporting.',addWorker:'+ Add Worker',totalWorkers:'Total Workers',active:'Active',inactive:'Inactive',workers:'Workers',loadingWorkforce:'Loading workforce...',noWorkers:'No workers registered',noWorkersHelp:'Add the first worker to start the Field Management registry.',fieldId:'Field ID',employeeNumber:'Employee No.',worker:'Worker',company:'Company',trade:'Trade',role:'Role',status:'Status',unableDetermineOrganization:'Unable to determine the active organization for Field Management.',unableLoadRegistry:'Unable to load the workforce registry.',activeOrganizationMissing:'The active organization could not be determined.',firstNameRequired:'First Name is required.',lastNameRequired:'Last Name is required.',companyRequired:'Company is required.',tradeRequired:'Trade is required.',roleRequired:'Role is required.',workerRegistered:(fieldId)=>`Worker registered successfully. Field ID: ${fieldId}`,unableRegisterWorker:'Unable to register the worker.',addWorkerTitle:'Add Worker',close:'Close',identity:'Identity',employment:'Employment',companyEmployeeNumber:'Company Employee Number',firstName:'First Name',middleName:'Middle Name',lastName:'Last Name',selectCompany:'Select company',selectTrade:'Select trade',selectRole:'Select role',cancel:'Cancel',saving:'Saving...',registerWorker:'Register Worker'
  },
  'pt-BR': {
    fieldManagement:'Gestão de Campo',title:'Cadastro da Força de Trabalho',description:'Gerencie os registros mestres dos trabalhadores disponíveis para alocações em projetos, presença e relatórios da força de trabalho.',addWorker:'+ Adicionar Trabalhador',totalWorkers:'Total de Trabalhadores',active:'Ativo',inactive:'Inativo',workers:'Trabalhadores',loadingWorkforce:'Carregando força de trabalho...',noWorkers:'Nenhum trabalhador cadastrado',noWorkersHelp:'Adicione o primeiro trabalhador para iniciar o cadastro da Gestão de Campo.',fieldId:'ID de Campo',employeeNumber:'Nº do Funcionário',worker:'Trabalhador',company:'Empresa',trade:'Especialidade',role:'Função',status:'Status',unableDetermineOrganization:'Não foi possível determinar a organização ativa para a Gestão de Campo.',unableLoadRegistry:'Não foi possível carregar o cadastro da força de trabalho.',activeOrganizationMissing:'Não foi possível determinar a organização ativa.',firstNameRequired:'O nome é obrigatório.',lastNameRequired:'O sobrenome é obrigatório.',companyRequired:'A empresa é obrigatória.',tradeRequired:'A especialidade é obrigatória.',roleRequired:'A função é obrigatória.',workerRegistered:(fieldId)=>`Trabalhador cadastrado com sucesso. ID de Campo: ${fieldId}`,unableRegisterWorker:'Não foi possível cadastrar o trabalhador.',addWorkerTitle:'Adicionar Trabalhador',close:'Fechar',identity:'Identificação',employment:'Vínculo de Trabalho',companyEmployeeNumber:'Número do Funcionário na Empresa',firstName:'Nome',middleName:'Nome do Meio',lastName:'Sobrenome',selectCompany:'Selecione a empresa',selectTrade:'Selecione a especialidade',selectRole:'Selecione a função',cancel:'Cancelar',saving:'Salvando...',registerWorker:'Cadastrar Trabalhador'
  },
  es: {
    fieldManagement:'Gestión de Campo',title:'Registro de Fuerza Laboral',description:'Gestiona los registros maestros de trabajadores disponibles para asignaciones de proyectos, asistencia e informes de fuerza laboral.',addWorker:'+ Agregar Trabajador',totalWorkers:'Total de Trabajadores',active:'Activo',inactive:'Inactivo',workers:'Trabajadores',loadingWorkforce:'Cargando fuerza laboral...',noWorkers:'No hay trabajadores registrados',noWorkersHelp:'Agrega el primer trabajador para iniciar el registro de Gestión de Campo.',fieldId:'ID de Campo',employeeNumber:'N.º de Empleado',worker:'Trabajador',company:'Empresa',trade:'Especialidad',role:'Rol',status:'Estado',unableDetermineOrganization:'No se pudo determinar la organización activa para Gestión de Campo.',unableLoadRegistry:'No se pudo cargar el registro de fuerza laboral.',activeOrganizationMissing:'No se pudo determinar la organización activa.',firstNameRequired:'El nombre es obligatorio.',lastNameRequired:'El apellido es obligatorio.',companyRequired:'La empresa es obligatoria.',tradeRequired:'La especialidad es obligatoria.',roleRequired:'El rol es obligatorio.',workerRegistered:(fieldId)=>`Trabajador registrado correctamente. ID de Campo: ${fieldId}`,unableRegisterWorker:'No se pudo registrar al trabajador.',addWorkerTitle:'Agregar Trabajador',close:'Cerrar',identity:'Identificación',employment:'Empleo',companyEmployeeNumber:'Número de Empleado de la Empresa',firstName:'Nombre',middleName:'Segundo Nombre',lastName:'Apellido',selectCompany:'Selecciona la empresa',selectTrade:'Selecciona la especialidad',selectRole:'Selecciona el rol',cancel:'Cancelar',saving:'Guardando...',registerWorker:'Registrar Trabajador'
  }
}
export function getWorkforceCopy(locale='en-US'){return copy[locale]||copy['en-US']}
export function getWorkforceStatusLabel(status,locale='en-US'){const t=getWorkforceCopy(locale);if(status==='active')return t.active;if(status==='inactive')return t.inactive;return status||'—'}
