'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { supabase } from '../../../lib/supabase'
import styles from './workforce.module.css'
import TimecardsPanel from './TimecardsPanel'

const nav=[['⌂','Portfolio Overview','/fieldop'],['□','Projects','/fieldop/projects'],['♙','Workforce','/fieldop/workforce'],['⌖','Operations','#'],['△','Occurrences','#'],['▥','Reports','/fieldop/reports/daily'],['⚙','Settings','#']]
const tabs=['Live Attendance','Worker Registry','Project Assignments','Timecards']
const workerInitial={companyEmployeeNumber:'',firstName:'',middleName:'',lastName:'',companyId:'',tradeId:'',roleId:'',status:'active'}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const assignmentInitial=()=>({workerId:'',projectId:'',companyId:'',tradeId:'',roleId:'',crewId:'',startDate:today(),endDate:'',status:'active'})

export default function FieldOpWorkforcePage(){
  const [activeTab,setActiveTab]=useState('Live Attendance')
  const [sessions,setSessions]=useState([]),[workers,setWorkers]=useState([]),[companies,setCompanies]=useState([]),[trades,setTrades]=useState([]),[roles,setRoles]=useState([])
  const [projects,setProjects]=useState([]),[crews,setCrews]=useState([]),[assignments,setAssignments]=useState([])
  const [organizationId,setOrganizationId]=useState(null)
  const [loading,setLoading]=useState(true),[registryLoading,setRegistryLoading]=useState(true),[assignmentLoading,setAssignmentLoading]=useState(true),[saving,setSaving]=useState(false)
  const [error,setError]=useState(''),[registryError,setRegistryError]=useState(''),[assignmentError,setAssignmentError]=useState(''),[formError,setFormError]=useState('')
  const [query,setQuery]=useState(''),[showAddWorker,setShowAddWorker]=useState(false),[showAssignment,setShowAssignment]=useState(false)
  const [form,setForm]=useState(workerInitial),[assignmentForm,setAssignmentForm]=useState(assignmentInitial())

  useEffect(()=>{let alive=true;async function load(){setLoading(true);setError('');try{const {data,error}=await supabase.from('field_attendance_sessions').select('*').is('check_out_at',null).order('check_in_at',{ascending:false});if(error)throw error;if(alive)setSessions(data||[])}catch(e){console.error('FieldOp live attendance:',e);if(alive){setSessions([]);setError('Live attendance could not be loaded.')}}finally{if(alive)setLoading(false)}}load();return()=>{alive=false}},[])

  const loadRegistry=useCallback(async()=>{setRegistryLoading(true);setRegistryError('');try{const [w,c,t,r]=await Promise.all([
    supabase.from('field_workers').select('id,organization_id,field_id,company_employee_number,first_name,middle_name,last_name,default_company_id,default_trade_id,default_role_id,status,field_companies:default_company_id(id,name),field_trades:default_trade_id(id,name),field_roles:default_role_id(id,name)').order('field_id',{ascending:true}),
    supabase.from('field_companies').select('id,organization_id,name,status').eq('status','active').order('name'),supabase.from('field_trades').select('id,organization_id,name,status').eq('status','active').order('name'),supabase.from('field_roles').select('id,organization_id,name,status').eq('status','active').order('name')]);const first=w.error||c.error||t.error||r.error;if(first)throw first;setWorkers(w.data||[]);setCompanies(c.data||[]);setTrades(t.data||[]);setRoles(r.data||[]);const org=w.data?.[0]?.organization_id||c.data?.[0]?.organization_id||t.data?.[0]?.organization_id||r.data?.[0]?.organization_id||null;setOrganizationId(org);if(!org)setRegistryError('Unable to determine the active organization for FieldOp Workforce.')}catch(e){console.error('FieldOp workforce registry:',e);setRegistryError(e?.message||'Unable to load the workforce registry.')}finally{setRegistryLoading(false)}},[])
  useEffect(()=>{loadRegistry()},[loadRegistry])

  const loadAssignments=useCallback(async()=>{setAssignmentLoading(true);setAssignmentError('');try{const [a,p,c]=await Promise.all([
    supabase.from('field_project_assignments').select('id,organization_id,project_id,worker_id,company_id,trade_id,role_id,crew_id,start_date,end_date,status,created_at,field_workers:worker_id(id,field_id,first_name,middle_name,last_name),projects:project_id(id,code,name),field_companies:company_id(id,name),field_trades:trade_id(id,name),field_roles:role_id(id,name),field_crews:crew_id(id,name)').order('created_at',{ascending:false}),
    supabase.from('projects').select('id,organization_id,code,name,status,standard_daily_minutes').order('code'),supabase.from('field_crews').select('id,organization_id,company_id,name,status').eq('status','active').order('name')]);const first=a.error||p.error||c.error;if(first)throw first;setAssignments(a.data||[]);setProjects(p.data||[]);setCrews(c.data||[])}catch(e){console.error('FieldOp assignments:',e);setAssignmentError(e?.message||'Unable to load project assignments.')}finally{setAssignmentLoading(false)}},[])
  useEffect(()=>{loadAssignments()},[loadAssignments])

  const rows=useMemo(()=>sessions.map(s=>({...s,worker:s.worker_name||s.worker_display_name||s.field_worker_name||s.worker_id||'Worker',project:s.project_name||s.project_id||'—',location:s.location_name||s.location||s.field_location_name||'—',workPackage:s.work_package_code||s.work_package||s.activity_name||'—'})),[sessions])
  const q=query.trim().toLowerCase()
  const filtered=useMemo(()=>!q?rows:rows.filter(x=>[x.worker,x.project,x.location,x.workPackage].some(v=>String(v||'').toLowerCase().includes(q))),[rows,q])
  const filteredWorkers=useMemo(()=>!q?workers:workers.filter(w=>[w.field_id,w.company_employee_number,w.first_name,w.middle_name,w.last_name,w.field_companies?.name,w.field_trades?.name,w.field_roles?.name].some(v=>String(v||'').toLowerCase().includes(q))),[workers,q])
  const filteredAssignments=useMemo(()=>!q?assignments:assignments.filter(a=>[workerName(a.field_workers),a.projects?.code,a.projects?.name,a.field_companies?.name,a.field_trades?.name,a.field_roles?.name,a.field_crews?.name,a.status].some(v=>String(v||'').toLowerCase().includes(q))),[assignments,q])
  const longSessions=rows.filter(x=>x.check_in_at&&Date.now()-new Date(x.check_in_at).getTime()>36000000).length,projectsOnSite=new Set(rows.map(x=>x.project_id).filter(Boolean)).size,locationsActive=new Set(rows.map(x=>x.location_id||x.location).filter(Boolean)).size,activeWorkers=workers.filter(w=>w.status==='active').length
  const assignmentCounts={active:assignments.filter(a=>a.status==='active').length,scheduled:assignments.filter(a=>a.status==='scheduled').length,ended:assignments.filter(a=>a.status==='ended').length}
  const availableCrews=crews.filter(c=>!assignmentForm.companyId||c.company_id===assignmentForm.companyId)

  function workerName(w){return w?[w.first_name,w.middle_name,w.last_name].filter(Boolean).join(' '):'—'}
  function hoursOnSite(v){return v?`${Math.max(0,(Date.now()-new Date(v).getTime())/3600000).toFixed(1)} h`:'—'}
  function checkInTime(v){return v?new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'}
  function formatDate(v){if(!v)return '—';const [y,m,d]=v.split('-');return `${m}/${d}/${y}`}
  function openAddWorker(){setForm(workerInitial);setFormError('');setShowAddWorker(true)}
  function closeAddWorker(){if(saving)return;setShowAddWorker(false);setFormError('');setForm(workerInitial)}
  function changeForm(e){const {name,value}=e.target;setForm(x=>({...x,[name]:value}))}
  async function addWorker(e){e.preventDefault();setFormError('');if(!organizationId)return setFormError('The active organization could not be determined.');if(!form.firstName.trim())return setFormError('First Name is required.');if(!form.lastName.trim())return setFormError('Last Name is required.');if(!form.companyId)return setFormError('Company is required.');if(!form.tradeId)return setFormError('Trade is required.');if(!form.roleId)return setFormError('Role is required.');setSaving(true);try{const {error}=await supabase.from('field_workers').insert({organization_id:organizationId,company_employee_number:form.companyEmployeeNumber.trim()||null,first_name:form.firstName.trim(),middle_name:form.middleName.trim()||null,last_name:form.lastName.trim(),default_company_id:form.companyId,default_trade_id:form.tradeId,default_role_id:form.roleId,status:form.status});if(error)throw error;setShowAddWorker(false);setForm(workerInitial);await loadRegistry()}catch(err){setFormError(err?.message||'Unable to register the worker.')}finally{setSaving(false)}}

  function openAssignment(){setFormError('');setAssignmentForm(assignmentInitial());setShowAssignment(true)}
  function closeAssignment(){if(saving)return;setShowAssignment(false);setFormError('');setAssignmentForm(assignmentInitial())}
  function changeAssignment(e){const {name,value}=e.target;if(name==='workerId'){const w=workers.find(x=>x.id===value);setAssignmentForm(x=>({...x,workerId:value,companyId:w?.default_company_id||'',tradeId:w?.default_trade_id||'',roleId:w?.default_role_id||'',crewId:''}));return}if(name==='companyId'){setAssignmentForm(x=>({...x,companyId:value,crewId:''}));return}setAssignmentForm(x=>({...x,[name]:value}))}
  async function createAssignment(e){e.preventDefault();setFormError('');const f=assignmentForm;if(!f.workerId)return setFormError('Worker is required.');if(!f.projectId)return setFormError('Project is required.');if(!f.companyId)return setFormError('Company is required.');if(!f.startDate)return setFormError('Start Date is required.');if(f.endDate&&f.endDate<f.startDate)return setFormError('End Date cannot be earlier than Start Date.');const w=workers.find(x=>x.id===f.workerId),p=projects.find(x=>x.id===f.projectId);if(!w||!p)return setFormError('Unable to determine the selected Worker or Project.');if(w.organization_id!==p.organization_id)return setFormError('Worker and Project must belong to the same organization.');if(assignments.some(a=>a.worker_id===f.workerId&&a.project_id===f.projectId&&['active','scheduled'].includes(a.status)))return setFormError('This worker already has an active or scheduled assignment for the selected project.');setSaving(true);try{const {error}=await supabase.from('field_project_assignments').insert({organization_id:p.organization_id,project_id:f.projectId,worker_id:f.workerId,company_id:f.companyId,trade_id:f.tradeId||null,role_id:f.roleId||null,crew_id:f.crewId||null,start_date:f.startDate,end_date:f.endDate||null,status:f.status});if(error)throw error;setShowAssignment(false);setAssignmentForm(assignmentInitial());await loadAssignments()}catch(err){setFormError(err?.message||'Unable to create the project assignment.')}finally{setSaving(false)}}

  return <main className={styles.shell}><aside className={styles.sidebar}><div className={styles.brand}><Image src="/logo-white.png" alt="RitsuFlow" width={160} height={58} priority/></div><div className={styles.navTitle}>FIELD OPERATIONS</div><nav>{nav.map(([icon,label,href])=><Link key={label} className={label==='Workforce'?styles.active:''} href={href}><i>{icon}</i>{label}</Link>)}</nav><Link href="/workspaces" className={styles.workspaceReturn}>← <span>Workspaces</span></Link></aside><section className={styles.main}><header className={styles.topbar}><div className={styles.search}>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workforce..."/></div><div className={styles.user}><b>EF</b><div><strong>Eduardo Freitas</strong><span>Operations Manager</span></div></div></header><div className={styles.content}>
    <section className={styles.heading}><div><span>FIELDOP / WORKFORCE</span><h1>Workforce</h1><p>People, assignments and live field presence in one operational workspace.</p></div>{activeTab==='Worker Registry'?<button className={styles.primaryAction} onClick={openAddWorker}>+ Add Worker</button>:activeTab==='Project Assignments'?<button className={styles.primaryAction} onClick={openAssignment}>+ New Assignment</button>:null}</section>
    <div className={styles.tabs}>{tabs.map(tab=><button key={tab} className={activeTab===tab?styles.tabActive:''} onClick={()=>setActiveTab(tab)}>{tab}</button>)}</div>
    {activeTab==='Live Attendance'&&<><section className={styles.kpis}><article><span>♙</span><div><small>Workers On Site</small><strong>{rows.length}</strong><em>live attendance</em></div></article><article><span>▣</span><div><small>Projects With Presence</small><strong>{projectsOnSite}</strong><em>active now</em></div></article><article><span>⌖</span><div><small>Active Locations</small><strong>{locationsActive}</strong><em>field locations</em></div></article><article><span>!</span><div><small>Long Open Sessions</small><strong>{longSessions}</strong><em>over 10 hours</em></div></article></section><section className={styles.panel}><div className={styles.panelHead}><div><h2>Live Attendance</h2><p>Who is currently checked in across FieldOp projects.</p></div><span>{filtered.length} on site</span></div>{error&&<div className={styles.error}>{error}</div>}{loading?<div className={styles.empty}><b>Loading live attendance...</b></div>:filtered.length===0?<div className={styles.empty}><b>No workers are currently checked in.</b><span>Live attendance will appear here when field check-ins begin.</span></div>:<div className={styles.tableWrap}><table><thead><tr><th>Worker</th><th>Project</th><th>Location</th><th>Work Package</th><th>Check-In</th><th>Hours On Site</th><th>Status</th></tr></thead><tbody>{filtered.map((x,i)=><tr key={x.id||i}><td><strong>{x.worker}</strong><small>{x.field_id||x.employee_number||''}</small></td><td>{x.project}</td><td>{x.location}</td><td>{x.workPackage}</td><td>{checkInTime(x.check_in_at)}</td><td>{hoursOnSite(x.check_in_at)}</td><td><span className={styles.live}>● On Site</span></td></tr>)}</tbody></table></div>}</section></>}
    {activeTab==='Worker Registry'&&<><section className={styles.kpis}><article><span>♙</span><div><small>Total Workers</small><strong>{workers.length}</strong><em>organization registry</em></div></article><article><span>✓</span><div><small>Active</small><strong>{activeWorkers}</strong><em>available workforce</em></div></article><article><span>○</span><div><small>Inactive</small><strong>{workers.length-activeWorkers}</strong><em>inactive records</em></div></article><article><span>▣</span><div><small>Companies</small><strong>{companies.length}</strong><em>active companies</em></div></article></section><section className={styles.panel}><div className={styles.panelHead}><div><h2>Worker Registry</h2><p>Canonical organization workforce used by FieldOp projects and attendance.</p></div><span>{filteredWorkers.length} workers</span></div>{registryError&&<div className={styles.error}>{registryError}</div>}{registryLoading?<div className={styles.empty}><b>Loading workforce...</b></div>:filteredWorkers.length===0?<div className={styles.empty}><b>No workers registered.</b></div>:<div className={styles.tableWrap}><table><thead><tr><th>Field ID</th><th>Employee No.</th><th>Worker</th><th>Company</th><th>Trade</th><th>Role</th><th>Status</th></tr></thead><tbody>{filteredWorkers.map(w=><tr key={w.id}><td><strong>{w.field_id||'—'}</strong></td><td>{w.company_employee_number||'—'}</td><td><strong>{workerName(w)||'—'}</strong></td><td>{w.field_companies?.name||'—'}</td><td>{w.field_trades?.name||'—'}</td><td>{w.field_roles?.name||'—'}</td><td><span className={w.status==='active'?styles.live:styles.inactive}>{w.status==='active'?'Active':'Inactive'}</span></td></tr>)}</tbody></table></div>}</section></>}
    {activeTab==='Project Assignments'&&<><section className={styles.kpis}><article><span>▣</span><div><small>Total Assignments</small><strong>{assignments.length}</strong><em>all records</em></div></article><article><span>✓</span><div><small>Active</small><strong>{assignmentCounts.active}</strong><em>current assignments</em></div></article><article><span>◷</span><div><small>Scheduled</small><strong>{assignmentCounts.scheduled}</strong><em>future assignments</em></div></article><article><span>○</span><div><small>Ended</small><strong>{assignmentCounts.ended}</strong><em>completed assignments</em></div></article></section><section className={styles.panel}><div className={styles.panelHead}><div><h2>Project Assignments</h2><p>Allocate workers to projects while preserving company, trade, role and crew context.</p></div><span>{filteredAssignments.length} assignments</span></div>{assignmentError&&<div className={styles.error}>{assignmentError}</div>}{assignmentLoading?<div className={styles.empty}><b>Loading project assignments...</b></div>:filteredAssignments.length===0?<div className={styles.empty}><b>No project assignments found.</b></div>:<div className={styles.tableWrap}><table><thead><tr><th>Worker</th><th>Project</th><th>Company</th><th>Trade / Role</th><th>Crew</th><th>Dates</th><th>Status</th></tr></thead><tbody>{filteredAssignments.map(a=><tr key={a.id}><td><strong>{workerName(a.field_workers)}</strong><small>{a.field_workers?.field_id||''}</small></td><td><strong>{a.projects?.code||'—'}</strong><small>{a.projects?.name||''}</small></td><td>{a.field_companies?.name||'—'}</td><td>{a.field_trades?.name||'—'}<small>{a.field_roles?.name||''}</small></td><td>{a.field_crews?.name||'—'}</td><td>{formatDate(a.start_date)}<small>{a.end_date?`to ${formatDate(a.end_date)}`:'Open ended'}</small></td><td><span className={a.status==='active'?styles.live:styles.inactive}>{a.status?.charAt(0).toUpperCase()+a.status?.slice(1)||'—'}</span></td></tr>)}</tbody></table></div>}</section></>}
    {activeTab==='Timecards'&&<TimecardsPanel projects={projects} workers={workers} query={query}/>} 
    <section className={styles.flow}><b>FIELD EXECUTION FLOW</b><div><span>LOCATION</span><i>→</i><span>PEOPLE</span><i>→</i><span>WORK PACKAGE</span><i>→</i><span>EXECUTION</span><i>→</i><span>DAILY REPORT</span></div></section>
  </div></section>
  {showAddWorker&&<div className={styles.modalBackdrop}><section className={styles.modal}><header><div><h2>Add Worker</h2><p>Create a worker directly in the canonical FieldOp registry.</p></div><button onClick={closeAddWorker} aria-label="Close">×</button></header><form onSubmit={addWorker}><div className={styles.formGrid}><label><span>Company Employee Number</span><input name="companyEmployeeNumber" value={form.companyEmployeeNumber} onChange={changeForm}/></label><label><span>First Name *</span><input name="firstName" value={form.firstName} onChange={changeForm}/></label><label><span>Middle Name</span><input name="middleName" value={form.middleName} onChange={changeForm}/></label><label><span>Last Name *</span><input name="lastName" value={form.lastName} onChange={changeForm}/></label><label><span>Company *</span><select name="companyId" value={form.companyId} onChange={changeForm}><option value="">Select company</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Trade *</span><select name="tradeId" value={form.tradeId} onChange={changeForm}><option value="">Select trade</option>{trades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Role *</span><select name="roleId" value={form.roleId} onChange={changeForm}><option value="">Select role</option>{roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Status</span><select name="status" value={form.status} onChange={changeForm}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>{formError&&<div className={styles.error}>{formError}</div>}<footer><button type="button" onClick={closeAddWorker} disabled={saving}>Cancel</button><button className={styles.primaryAction} type="submit" disabled={saving}>{saving?'Saving...':'Register Worker'}</button></footer></form></section></div>}
  {showAssignment&&<div className={styles.modalBackdrop}><section className={styles.modal}><header><div><h2>New Project Assignment</h2><p>Assign a worker to a FieldOp project.</p></div><button onClick={closeAssignment} aria-label="Close">×</button></header><form onSubmit={createAssignment}><div className={styles.formGrid}><label><span>Worker *</span><select name="workerId" value={assignmentForm.workerId} onChange={changeAssignment}><option value="">Select worker</option>{workers.filter(w=>w.status==='active').map(w=><option key={w.id} value={w.id}>{w.field_id} · {workerName(w)}</option>)}</select></label><label><span>Project *</span><select name="projectId" value={assignmentForm.projectId} onChange={changeAssignment}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label><span>Company *</span><select name="companyId" value={assignmentForm.companyId} onChange={changeAssignment}><option value="">Select company</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Trade</span><select name="tradeId" value={assignmentForm.tradeId} onChange={changeAssignment}><option value="">Select trade</option>{trades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Role</span><select name="roleId" value={assignmentForm.roleId} onChange={changeAssignment}><option value="">Select role</option>{roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Crew</span><select name="crewId" value={assignmentForm.crewId} onChange={changeAssignment}><option value="">No crew</option>{availableCrews.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Start Date *</span><input type="date" name="startDate" value={assignmentForm.startDate} onChange={changeAssignment}/></label><label><span>End Date</span><input type="date" name="endDate" value={assignmentForm.endDate} onChange={changeAssignment}/></label><label><span>Status</span><select name="status" value={assignmentForm.status} onChange={changeAssignment}><option value="active">Active</option><option value="scheduled">Scheduled</option><option value="ended">Ended</option></select></label></div>{formError&&<div className={styles.error}>{formError}</div>}<footer><button type="button" onClick={closeAssignment} disabled={saving}>Cancel</button><button className={styles.primaryAction} type="submit" disabled={saving}>{saving?'Saving...':'Create Assignment'}</button></footer></form></section></div>}
  </main>
}