'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../../lib/supabase'
import { useLanguage } from '../../../contexts/LanguageContext'
import { getFieldopWorkforceMessages } from '../../../i18n/fieldopWorkforce'
import styles from './workforce.module.css'

const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const name=w=>w?[w.first_name,w.middle_name,w.last_name].filter(Boolean).join(' ')||'—':'—'
const minutes=v=>{const n=Math.max(0,Math.floor(Number(v)||0));return `${Math.floor(n/60)}h ${String(n%60).padStart(2,'0')}m`}
const localInput=v=>{if(!v)return'';const d=new Date(v),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}

export default function TimecardsPanel({projects=[],workers=[],query=''}){
  const {locale}=useLanguage();const t=getFieldopWorkforceMessages(locale).timecards
  const time=v=>v?new Intl.DateTimeFormat(locale,{hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'
  const [projectId,setProjectId]=useState(''),[date,setDate]=useState(localDate()),[sessions,setSessions]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const [editing,setEditing]=useState(null),[editForm,setEditForm]=useState({checkIn:'',checkOut:'',reason:''}),[saving,setSaving]=useState(false),[editError,setEditError]=useState('')
  const [reviewing,setReviewing]=useState(null),[reviewForm,setReviewForm]=useState({notes:'',action:'accepted'}),[reviewError,setReviewError]=useState('')
  useEffect(()=>{if(!projectId&&projects.length)setProjectId(projects[0].id)},[projects,projectId])
  const load=useCallback(async()=>{if(!projectId||!date){setSessions([]);return}setLoading(true);setError('');try{const {data,error}=await supabase.from('field_attendance_sessions').select('id,worker_id,project_id,work_date,check_in_at,check_out_at,status,worked_minutes,regular_minutes,overtime_minutes,has_exception,exception_code,exception_notes,exception_resolution_status,exception_resolution_action,exception_resolution_notes,exception_resolved_at').eq('project_id',projectId).eq('work_date',date).order('check_in_at',{ascending:true});if(error)throw error;setSessions(data||[])}catch(e){setError(e?.message||t.errorLoad)}finally{setLoading(false)}},[projectId,date,t.errorLoad])
  useEffect(()=>{load()},[load])
  const workerMap=useMemo(()=>new Map(workers.map(w=>[w.id,w])),[workers])
  const selectedProject=projects.find(p=>p.id===projectId)||null
  const cards=useMemo(()=>{const grouped=new Map();sessions.forEach(s=>grouped.set(s.worker_id,[...(grouped.get(s.worker_id)||[]),s]));return [...grouped].map(([workerId,list])=>{const closed=list.filter(s=>s.status==='closed'||s.status==='corrected');const total=closed.reduce((n,s)=>n+(Number(s.worked_minutes)||0),0);const allowed=selectedProject?.standard_daily_minutes??null;const open=list.some(s=>s.status==='open');return{workerId,worker:workerMap.get(workerId),list,total,allowed,variance:allowed==null?null:total-Number(allowed),open,exception:list.some(s=>s.has_exception&&s.exception_resolution_status!=='resolved'),corrected:list.some(s=>s.status==='corrected'),first:list[0]?.check_in_at,last:[...closed].reverse()[0]?.check_out_at}}).sort((a,b)=>name(a.worker).localeCompare(name(b.worker),locale))},[sessions,selectedProject,workerMap,locale])
  const q=query.trim().toLowerCase();const filtered=!q?cards:cards.filter(c=>[name(c.worker),c.worker?.field_id,c.worker?.company_employee_number].some(v=>String(v||'').toLowerCase().includes(q)))
  const labor=cards.reduce((n,c)=>n+c.total,0),exceptions=cards.filter(c=>c.exception).length,open=cards.filter(c=>c.open).length
  function openCorrection(session){setEditing(session);setEditError('');setEditForm({checkIn:localInput(session.check_in_at),checkOut:localInput(session.check_out_at),reason:''})}
  function closeCorrection(){if(saving)return;setEditing(null);setEditError('')}
  async function saveCorrection(e){e.preventDefault();setEditError('');if(!editing)return;if(!editForm.reason.trim()||editForm.reason.trim().length<3)return setEditError(t.errorReason);if(!editForm.checkIn)return setEditError(t.errorCheckIn);if(!editForm.checkOut)return setEditError(t.errorCheckOut);const checkIn=new Date(editForm.checkIn),checkOut=new Date(editForm.checkOut);if(checkOut<checkIn)return setEditError(t.errorOrder);setSaving(true);try{const {error}=await supabase.rpc('field_correct_attendance_session',{p_session_id:editing.id,p_new_check_in_at:checkIn.toISOString(),p_new_check_out_at:checkOut.toISOString(),p_reason:editForm.reason.trim()});if(error)throw error;setEditing(null);await load()}catch(err){setEditError(err?.message||t.errorCorrection)}finally{setSaving(false)}}
  function openReview(session){setReviewing(session);setReviewError('');setReviewForm({notes:session.exception_resolution_notes||'',action:'accepted'})}
  function closeReview(){if(saving)return;setReviewing(null);setReviewError('')}
  async function markReviewed(){if(!reviewing)return;setSaving(true);setReviewError('');try{const {error}=await supabase.rpc('field_review_attendance_exception',{p_session_id:reviewing.id,p_review_notes:reviewForm.notes.trim()||null});if(error)throw error;setReviewing(null);await load()}catch(err){setReviewError(err?.message||t.errorReview)}finally{setSaving(false)}}
  async function resolveException(e){e.preventDefault();if(!reviewing)return;setSaving(true);setReviewError('');try{const {error}=await supabase.rpc('field_resolve_attendance_exception',{p_session_id:reviewing.id,p_resolution_action:reviewForm.action,p_resolution_notes:reviewForm.notes.trim()||null});if(error)throw error;setReviewing(null);await load()}catch(err){setReviewError(err?.message||t.errorResolve)}finally{setSaving(false)}}
  return <>
    <section className={styles.kpis}><article><span>♙</span><div><small>{t.workersWithAttendance}</small><strong>{cards.length}</strong><em>{t.selectedDay}</em></div></article><article><span>◷</span><div><small>{t.totalLabor}</small><strong>{minutes(labor)}</strong><em>{t.closedSessions}</em></div></article><article><span>!</span><div><small>{t.exceptions}</small><strong>{exceptions}</strong><em>{t.unresolvedTimecards}</em></div></article><article><span>○</span><div><small>{t.openSessions}</small><strong>{open}</strong><em>{t.notCheckedOut}</em></div></article></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2>{t.title}</h2><p>{t.subtitle}</p></div><div style={{display:'flex',gap:8}}><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">{t.selectProject}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>{error&&<div className={styles.error}>{error}</div>}{loading?<div className={styles.empty}><b>{t.loading}</b></div>:filtered.length===0?<div className={styles.empty}><b>{t.empty}</b></div>:<div className={styles.tableWrap}><table><thead><tr><th>{t.worker}</th><th>{t.firstIn}</th><th>{t.lastOut}</th><th>{t.worked}</th><th>{t.allowed}</th><th>{t.variance}</th><th>{t.sessions}</th><th>{t.status}</th><th>{t.action}</th></tr></thead><tbody>{filtered.map(c=><tr key={c.workerId}><td><strong>{name(c.worker)}</strong><small>{c.worker?.field_id||c.worker?.company_employee_number||''}</small></td><td>{time(c.first)}</td><td>{time(c.last)}</td><td>{minutes(c.total)}</td><td>{c.allowed==null?t.notConfigured:minutes(c.allowed)}</td><td>{c.variance==null?'—':`${c.variance>0?'+':c.variance<0?'-':''}${minutes(Math.abs(c.variance))}`}</td><td>{c.list.length}</td><td><span className={c.open||c.exception?styles.inactive:styles.live}>{c.open?t.openSession:c.exception?t.exception:c.corrected?t.corrected:t.withinAllowance}</span></td><td>{c.list.map(s=><span key={s.id} style={{whiteSpace:'nowrap'}}><button type="button" onClick={()=>openCorrection(s)} style={{marginRight:6}}>{t.edit} {time(s.check_in_at)}</button>{s.has_exception&&<button type="button" onClick={()=>openReview(s)} style={{marginRight:6}}>{s.exception_resolution_status==='resolved'?t.viewResolution:t.reviewException}</button>}</span>)}</td></tr>)}</tbody></table></div>}</section>
    {editing&&<div className={styles.modalBackdrop}><section className={styles.modal}><header><div><h2>{t.correctAttendance}</h2><p>{t.correctionHelp}</p></div><button onClick={closeCorrection} aria-label={t.close}>×</button></header><form onSubmit={saveCorrection}><div className={styles.formGrid}><label><span>{t.checkIn} *</span><input type="datetime-local" value={editForm.checkIn} onChange={e=>setEditForm(x=>({...x,checkIn:e.target.value}))}/></label><label><span>{t.checkOut} *</span><input type="datetime-local" value={editForm.checkOut} onChange={e=>setEditForm(x=>({...x,checkOut:e.target.value}))}/></label><label style={{gridColumn:'1 / -1'}}><span>{t.correctionReason} *</span><textarea rows="4" value={editForm.reason} onChange={e=>setEditForm(x=>({...x,reason:e.target.value}))} placeholder={t.correctionPlaceholder}/></label></div>{editing.has_exception&&<div className={styles.error}>{t.exception}: {editing.exception_code||t.flaggedAttendance}{editing.exception_notes?` · ${editing.exception_notes}`:''}</div>}{editError&&<div className={styles.error}>{editError}</div>}<footer><button type="button" onClick={closeCorrection} disabled={saving}>{t.cancel}</button><button className={styles.primaryAction} type="submit" disabled={saving}>{saving?t.saving:t.saveCorrection}</button></footer></form></section></div>}
    {reviewing&&<div className={styles.modalBackdrop}><section className={styles.modal}><header><div><h2>{t.attendanceException}</h2><p>{t.exceptionHelp}</p></div><button onClick={closeReview} aria-label={t.close}>×</button></header><form onSubmit={resolveException}><div className={styles.formGrid}><label><span>{t.exception}</span><input value={reviewing.exception_code||t.recordedException} disabled/></label><label><span>{t.currentStatus}</span><input value={reviewing.exception_resolution_status||'open'} disabled/></label><label style={{gridColumn:'1 / -1'}}><span>{t.detectedNotes}</span><textarea rows="2" value={reviewing.exception_notes||''} disabled/></label>{reviewing.exception_resolution_status!=='resolved'&&<><label><span>{t.resolutionAction}</span><select value={reviewForm.action} onChange={e=>setReviewForm(x=>({...x,action:e.target.value}))}><option value="accepted">{t.accept}</option><option value="rejected">{t.reject}</option><option value="dismissed">{t.dismiss}</option></select></label><label style={{gridColumn:'1 / -1'}}><span>{t.reviewResolutionNotes}</span><textarea rows="4" value={reviewForm.notes} onChange={e=>setReviewForm(x=>({...x,notes:e.target.value}))} placeholder={t.reviewPlaceholder}/></label></>}{reviewing.exception_resolution_status==='resolved'&&<><label><span>{t.resolution}</span><input value={reviewing.exception_resolution_action||'—'} disabled/></label><label style={{gridColumn:'1 / -1'}}><span>{t.resolutionNotes}</span><textarea rows="3" value={reviewing.exception_resolution_notes||''} disabled/></label></>}</div>{reviewError&&<div className={styles.error}>{reviewError}</div>}<footer><button type="button" onClick={closeReview} disabled={saving}>{t.close}</button>{reviewing.exception_resolution_status==='open'&&<button type="button" onClick={markReviewed} disabled={saving}>{t.markReviewed}</button>}{reviewing.exception_resolution_status!=='resolved'&&<button className={styles.primaryAction} type="submit" disabled={saving}>{saving?t.saving:t.resolveException}</button>}</footer></form></section></div>}
  </>
}
