'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../../lib/supabase'
import styles from './workforce.module.css'

const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const name=w=>w?[w.first_name,w.middle_name,w.last_name].filter(Boolean).join(' ')||'Unnamed worker':'Unknown worker'
const minutes=v=>{const n=Math.max(0,Math.floor(Number(v)||0));return `${Math.floor(n/60)}h ${String(n%60).padStart(2,'0')}m`}
const time=v=>v?new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'
const localInput=v=>{if(!v)return'';const d=new Date(v),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}

export default function TimecardsPanel({projects=[],workers=[],query=''}){
  const [projectId,setProjectId]=useState(''),[date,setDate]=useState(localDate()),[sessions,setSessions]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const [editing,setEditing]=useState(null),[editForm,setEditForm]=useState({checkIn:'',checkOut:'',reason:''}),[saving,setSaving]=useState(false),[editError,setEditError]=useState('')
  useEffect(()=>{if(!projectId&&projects.length)setProjectId(projects[0].id)},[projects,projectId])
  const load=useCallback(async()=>{if(!projectId||!date){setSessions([]);return}setLoading(true);setError('');try{const {data,error}=await supabase.from('field_attendance_sessions').select('id,worker_id,project_id,work_date,check_in_at,check_out_at,status,worked_minutes,regular_minutes,overtime_minutes,has_exception,exception_code,exception_notes,exception_resolution_status').eq('project_id',projectId).eq('work_date',date).order('check_in_at',{ascending:true});if(error)throw error;setSessions(data||[])}catch(e){setError(e?.message||'Unable to load timecards.')}finally{setLoading(false)}},[projectId,date])
  useEffect(()=>{load()},[load])
  const workerMap=useMemo(()=>new Map(workers.map(w=>[w.id,w])),[workers])
  const selectedProject=projects.find(p=>p.id===projectId)||null
  const cards=useMemo(()=>{const grouped=new Map();sessions.forEach(s=>grouped.set(s.worker_id,[...(grouped.get(s.worker_id)||[]),s]));return [...grouped].map(([workerId,list])=>{const closed=list.filter(s=>s.status==='closed'||s.status==='corrected');const total=closed.reduce((n,s)=>n+(Number(s.worked_minutes)||0),0);const allowed=selectedProject?.standard_daily_minutes??null;const open=list.some(s=>s.status==='open');return{workerId,worker:workerMap.get(workerId),list,total,allowed,variance:allowed==null?null:total-Number(allowed),open,exception:list.some(s=>s.has_exception&&s.exception_resolution_status!=='resolved'),corrected:list.some(s=>s.status==='corrected'),first:list[0]?.check_in_at,last:[...closed].reverse()[0]?.check_out_at}}).sort((a,b)=>name(a.worker).localeCompare(name(b.worker)))},[sessions,selectedProject,workerMap])
  const q=query.trim().toLowerCase();const filtered=!q?cards:cards.filter(c=>[name(c.worker),c.worker?.field_id,c.worker?.company_employee_number].some(v=>String(v||'').toLowerCase().includes(q)))
  const labor=cards.reduce((n,c)=>n+c.total,0),exceptions=cards.filter(c=>c.exception).length,open=cards.filter(c=>c.open).length
  function openCorrection(session){setEditing(session);setEditError('');setEditForm({checkIn:localInput(session.check_in_at),checkOut:localInput(session.check_out_at),reason:''})}
  function closeCorrection(){if(saving)return;setEditing(null);setEditError('')}
  async function saveCorrection(e){e.preventDefault();setEditError('');if(!editing)return;if(!editForm.reason.trim()||editForm.reason.trim().length<3)return setEditError('Enter a correction reason of at least 3 characters.');if(!editForm.checkIn)return setEditError('Check-In is required.');if(!editForm.checkOut)return setEditError('Check-Out is required for a corrected closed session.');const checkIn=new Date(editForm.checkIn),checkOut=new Date(editForm.checkOut);if(checkOut<checkIn)return setEditError('Check-Out cannot occur before Check-In.');setSaving(true);try{const {error}=await supabase.rpc('field_correct_attendance_session',{p_session_id:editing.id,p_new_check_in_at:checkIn.toISOString(),p_new_check_out_at:checkOut.toISOString(),p_reason:editForm.reason.trim()});if(error)throw error;setEditing(null);await load()}catch(err){setEditError(err?.message||'Unable to correct the attendance session.')}finally{setSaving(false)}}
  return <>
    <section className={styles.kpis}><article><span>♙</span><div><small>Workers With Attendance</small><strong>{cards.length}</strong><em>selected day</em></div></article><article><span>◷</span><div><small>Total Labor</small><strong>{minutes(labor)}</strong><em>closed sessions</em></div></article><article><span>!</span><div><small>Exceptions</small><strong>{exceptions}</strong><em>unresolved timecards</em></div></article><article><span>○</span><div><small>Open Sessions</small><strong>{open}</strong><em>not checked out</em></div></article></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2>Timecards</h2><p>Daily attendance totals and variance against the project's allowed working time.</p></div><div style={{display:'flex',gap:8}}><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>{error&&<div className={styles.error}>{error}</div>}{loading?<div className={styles.empty}><b>Loading timecards...</b></div>:filtered.length===0?<div className={styles.empty}><b>No attendance recorded for this project and date.</b></div>:<div className={styles.tableWrap}><table><thead><tr><th>Worker</th><th>First In</th><th>Last Out</th><th>Worked</th><th>Allowed</th><th>Variance</th><th>Sessions</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(c=><tr key={c.workerId}><td><strong>{name(c.worker)}</strong><small>{c.worker?.field_id||c.worker?.company_employee_number||''}</small></td><td>{time(c.first)}</td><td>{time(c.last)}</td><td>{minutes(c.total)}</td><td>{c.allowed==null?'Not configured':minutes(c.allowed)}</td><td>{c.variance==null?'—':`${c.variance>0?'+':c.variance<0?'-':''}${minutes(Math.abs(c.variance))}`}</td><td>{c.list.length}</td><td><span className={c.open||c.exception?styles.inactive:styles.live}>{c.open?'Open Session':c.exception?'Exception':c.corrected?'Corrected':'Within Allowance'}</span></td><td>{c.list.map(s=><button key={s.id} type="button" onClick={()=>openCorrection(s)} style={{marginRight:6}}>Edit {time(s.check_in_at)}</button>)}</td></tr>)}</tbody></table></div>}</section>
    {editing&&<div className={styles.modalBackdrop}><section className={styles.modal}><header><div><h2>Correct Attendance</h2><p>Adjust this attendance session. RitsuFlow preserves the original punch events and records the correction as an immutable manual adjustment.</p></div><button onClick={closeCorrection} aria-label="Close">×</button></header><form onSubmit={saveCorrection}><div className={styles.formGrid}><label><span>Check-In *</span><input type="datetime-local" value={editForm.checkIn} onChange={e=>setEditForm(x=>({...x,checkIn:e.target.value}))}/></label><label><span>Check-Out *</span><input type="datetime-local" value={editForm.checkOut} onChange={e=>setEditForm(x=>({...x,checkOut:e.target.value}))}/></label><label style={{gridColumn:'1 / -1'}}><span>Correction Reason *</span><textarea rows="4" value={editForm.reason} onChange={e=>setEditForm(x=>({...x,reason:e.target.value}))} placeholder="Explain why this attendance record is being corrected."/></label></div>{editing.has_exception&&<div className={styles.error}>Exception: {editing.exception_code||'Flagged attendance'}{editing.exception_notes?` · ${editing.exception_notes}`:''}</div>}{editError&&<div className={styles.error}>{editError}</div>}<footer><button type="button" onClick={closeCorrection} disabled={saving}>Cancel</button><button className={styles.primaryAction} type="submit" disabled={saving}>{saving?'Saving...':'Save Correction'}</button></footer></form></section></div>}
  </>
}
