'use client'

import { useEffect, useMemo, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '../../../../lib/supabase'
import styles from '../../new/new-project.module.css'

const initial={name:'',client_name:'',contract_number:'',status:'planning',country_code:'BR',postal_code:'',address_line:'',address_number:'',neighborhood:'',city:'',state_region:'',latitude:'',longitude:'',contract_value:'',currency_code:'BRL',billing_method:'progress_percent_complete',billing_cycle:'monthly',billing_cutoff_day:'',payment_terms_days:'30',has_retainage:false,retainage_percent:'',retainage_payment_days:'',material_included:false,material_value:'',planned_start_date:'',contractual_term_days:'',success_criteria:''}
const addDays=(d,n)=>{if(!d||n===''||n==null)return'';const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+Number(n));return x.toISOString().slice(0,10)}
const money=(v,c='BRL')=>v!==''&&v!=null?new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v)||0):'—'
const dateOnly=v=>v?String(v).slice(0,10):''
const billingLabels={progress_percent_complete:'Progress / Percent Complete',milestone:'Milestone Based',unit_price:'Unit Price',time_materials:'Time & Materials',fixed_schedule:'Fixed Payment Schedule',other:'Other / Custom'}
const cycleLabels={weekly:'Weekly',biweekly:'Biweekly',monthly:'Monthly',milestone:'By Milestone',custom:'Custom'}

export default function EditProjectPage(){
 const params=useParams(),router=useRouter(),projectId=params?.projectId
 const[step,setStep]=useState(1),[form,setForm]=useState(initial),[projectNumber,setProjectNumber]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[addressStatus,setAddressStatus]=useState(''),[geocoding,setGeocoding]=useState(false)
 const set=(k,v)=>setForm(x=>({...x,[k]:v})),plannedEnd=useMemo(()=>addDays(form.planned_start_date,form.contractual_term_days),[form.planned_start_date,form.contractual_term_days]),retainageValue=useMemo(()=>form.has_retainage&&form.contract_value&&form.retainage_percent?Number(form.contract_value)*Number(form.retainage_percent)/100:0,[form.has_retainage,form.contract_value,form.retainage_percent]),probableRetainageDate=useMemo(()=>form.has_retainage&&plannedEnd&&form.retainage_payment_days!==''?addDays(plannedEnd,form.retainage_payment_days):'',[form.has_retainage,plannedEnd,form.retainage_payment_days])
 useEffect(()=>{if(!projectId)return;let active=true;(async()=>{const{data,error:e}=await supabase.from('projects').select('*').eq('id',projectId).maybeSingle();if(!active)return;if(e||!data){setError(e?.message||'Project not found.');setLoading(false);return}setProjectNumber(data.project_id||'');let address=data.address_line||'',number=data.address_number||'';if(!number&&address){const m=address.match(/^(.*?),\s*([^,]+)$/);if(m){address=m[1];number=m[2]}}setForm({name:data.name||'',client_name:data.client_name||'',contract_number:data.contract_number||'',status:data.status||'planning',country_code:data.country_code||'BR',postal_code:data.postal_code||'',address_line:address,address_number:number,neighborhood:data.neighborhood||'',city:data.city||'',state_region:data.state_region||'',latitude:data.latitude??'',longitude:data.longitude??'',contract_value:data.contract_value??'',currency_code:data.currency_code||'BRL',billing_method:data.billing_method||'progress_percent_complete',billing_cycle:data.billing_cycle||'monthly',billing_cutoff_day:data.billing_cutoff_day??'',payment_terms_days:data.payment_terms_days??'30',has_retainage:!!data.has_retainage,retainage_percent:data.retainage_percent??'',retainage_payment_days:data.retainage_payment_days??'',material_included:!!data.material_included,material_value:data.material_value??'',planned_start_date:dateOnly(data.planned_start_date),contractual_term_days:data.contractual_term_days??'',success_criteria:data.success_criteria||''});setLoading(false)})();return()=>{active=false}},[projectId])
 async function lookupPostal(raw){if((form.country_code||'BR').toUpperCase()!=='BR'){setAddressStatus('For international projects, complete the address and use Find Coordinates.');return}const cep=String(raw||'').replace(/\D/g,'');if(!cep){setAddressStatus('');return}if(cep.length!==8){setAddressStatus('Enter a valid 8-digit Brazilian CEP.');return}setAddressStatus('Looking up CEP...');try{const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`),d=await r.json();if(!r.ok||d.erro)throw new Error('CEP not found.');setForm(v=>({...v,postal_code:d.cep||raw,address_line:d.logradouro||v.address_line,neighborhood:d.bairro||v.neighborhood,city:d.localidade||v.city,state_region:d.uf||v.state_region,country_code:'BR',latitude:'',longitude:''}));setAddressStatus('Address found. Enter the street number, then click Find Coordinates.')}catch(e){setAddressStatus(e.message||'Unable to look up this CEP.')}}
 async function findCoordinates(){const q=[form.address_line,form.address_number,form.neighborhood,form.city,form.state_region,form.postal_code,form.country_code].filter(Boolean).join(', ');if(!form.city&&!form.postal_code){setAddressStatus('Enter enough address information before finding coordinates.');return}setGeocoding(true);setAddressStatus('Finding project coordinates...');try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&addressdetails=1&q=${encodeURIComponent(q)}`,{headers:{'Accept-Language':'en'}}),d=await r.json();if(!r.ok||!d?.length)throw new Error('Location not found. Review the address or enter coordinates manually.');setForm(v=>({...v,latitude:d[0].lat,longitude:d[0].lon}));setAddressStatus('Coordinates found. Review them before saving.')}catch(e){setAddressStatus(e.message||'Unable to find coordinates.')}finally{setGeocoding(false)}}
 async function saveProject(){if(!form.name.trim()){setError('Project Name is required.');setStep(1);return}setSaving(true);setError('');const payload={name:form.name.trim(),client_name:form.client_name.trim()||null,contract_number:form.contract_number.trim()||null,status:form.status,country_code:form.country_code.trim().toUpperCase()||null,postal_code:form.postal_code.trim()||null,address_line:[form.address_line.trim(),form.address_number.trim()].filter(Boolean).join(', ')||null,neighborhood:form.neighborhood.trim()||null,city:form.city.trim()||null,state_region:form.state_region.trim()||null,latitude:form.latitude!==''?Number(form.latitude):null,longitude:form.longitude!==''?Number(form.longitude):null,contract_value:form.contract_value!==''?Number(form.contract_value):null,currency_code:form.currency_code||'BRL',billing_method:form.billing_method||null,billing_cycle:form.billing_cycle||null,billing_cutoff_day:form.billing_cutoff_day!==''?Number(form.billing_cutoff_day):null,payment_terms_days:form.payment_terms_days!==''?Number(form.payment_terms_days):null,has_retainage:form.has_retainage,retainage_percent:form.has_retainage&&form.retainage_percent!==''?Number(form.retainage_percent):null,retainage_value:form.has_retainage?retainageValue:null,retainage_payment_days:form.has_retainage&&form.retainage_payment_days!==''?Number(form.retainage_payment_days):null,probable_retainage_payment_date:form.has_retainage&&probableRetainageDate?probableRetainageDate:null,material_included:form.material_included,material_value:form.material_included&&form.material_value!==''?Number(form.material_value):null,planned_start_date:form.planned_start_date||null,planned_finish_date:plannedEnd||null,contractual_term_days:form.contractual_term_days!==''?Number(form.contractual_term_days):null,success_criteria:form.success_criteria.trim()||null};const{error:e}=await supabase.from('projects').update(payload).eq('id',projectId);if(e){setError(e.message||'Unable to save changes.');setSaving(false);return}router.push(`/projects/${projectId}`);router.refresh()}
 function next(){if(step===1&&!form.name.trim()){setError('Project Name is required.');return}setError('');setStep(s=>Math.min(5,s+1))}
 const steps=[['1','Project Information','Identity and client'],['2','Project Address','International location'],['3','Contract & Billing','Commercial terms'],['4','Schedule & Success','Dates and client success'],['5','Review & Save','Confirm changes']],descriptions=['Update project identity, client and status.','Select the country, update the postal address and store the project coordinates.','Update contract value, billing basis, payment terms, material composition and retainage.','Update the contractual timeline and client success criteria.','Review all changes before updating the shared project record.']
 if(loading)return <main className={styles.shell}><div style={{padding:40}}>Loading project...</div></main>
 return <main className={styles.shell}><header className={styles.topbar}><Link href={`/projects/${projectId}`} className={styles.brand}><Image src="/logo-white.png" alt="RitsuFlow" width={160} height={58} priority/></Link><div><b>Edit Project</b><span>{projectNumber||'Shared project record'}</span></div><Link href={`/projects/${projectId}`} className={styles.cancel}>Cancel</Link></header><section className={styles.workspace}><aside className={styles.steps}>{steps.map(([n,l,s])=><button key={n} className={step===+n?styles.active:step>+n?styles.done:''} onClick={()=>setStep(+n)}><i>{step>+n?'✓':n}</i><span>{l}<small>{s}</small></span></button>)}</aside><div className={styles.formArea}><div className={styles.heading}><span>STEP {step} OF 5</span><h1>{steps[step-1][1]}</h1><p>{descriptions[step-1]}</p></div><div className={styles.card}>
 {step===1&&<div className={styles.grid}><label>Project ID<input value={projectNumber} readOnly/></label><label>Project Name *<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Client<input value={form.client_name} onChange={e=>set('client_name',e.target.value)}/></label><label>Contract Number<input value={form.contract_number} onChange={e=>set('contract_number',e.target.value)}/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="planning">Planning</option><option value="preconstruction">Preconstruction</option><option value="ongoing">Ongoing</option><option value="completed">Completed</option><option value="archived">Archived</option></select></label><div className={styles.note}><b>Project ID is permanent.</b><span>{projectNumber} remains the shared identifier used by Projects, PreCon and FieldOp.</span></div></div>}
 {step===2&&<div className={styles.grid}><label>Country<select value={form.country_code} onChange={e=>{setForm(v=>({...v,country_code:e.target.value,latitude:'',longitude:''}));setAddressStatus('')}}><option value="BR">Brazil</option><option value="US">United States</option><option value="CA">Canada</option><option value="AU">Australia</option><option value="GB">United Kingdom</option><option value="MX">Mexico</option><option value="UY">Uruguay</option><option value="OTHER">Other</option></select></label><label>ZIP / Postal Code<input value={form.postal_code} onChange={e=>{set('postal_code',e.target.value);if(form.country_code==='BR'&&e.target.value.replace(/\D/g,'').length===8)lookupPostal(e.target.value)}} onBlur={e=>form.country_code==='BR'&&lookupPostal(e.target.value)}/></label><label className={styles.wide}>Address<input value={form.address_line} onChange={e=>set('address_line',e.target.value)}/></label><label>Number<input value={form.address_number} onChange={e=>set('address_number',e.target.value)}/></label><label>Neighborhood / District<input value={form.neighborhood} onChange={e=>set('neighborhood',e.target.value)}/></label><label>City<input value={form.city} onChange={e=>set('city',e.target.value)}/></label><label>State / Province<input value={form.state_region} onChange={e=>set('state_region',e.target.value)}/></label><label>Latitude<input type="number" step="any" value={form.latitude} onChange={e=>set('latitude',e.target.value)}/></label><label>Longitude<input type="number" step="any" value={form.longitude} onChange={e=>set('longitude',e.target.value)}/></label><div className={styles.note}><b>Project location</b><span>{addressStatus||'Complete the address and use Find Coordinates. Coordinates remain editable for the exact site entrance or field location.'}</span><button type="button" onClick={findCoordinates} disabled={geocoding} style={{marginTop:10,padding:'8px 14px',border:'1px solid #0b9a9a',borderRadius:7,background:'#fff',color:'#087f8c',fontWeight:800}}>{geocoding?'Finding...':'⌖ Find Coordinates'}</button></div></div>}
 {step===3&&<div className={styles.grid}><label>Contract Value<input type="number" min="0" step="0.01" value={form.contract_value} onChange={e=>set('contract_value',e.target.value)}/></label><label>Currency<select value={form.currency_code} onChange={e=>set('currency_code',e.target.value)}><option>BRL</option><option>USD</option><option>CAD</option></select></label><label>Billing Method<select value={form.billing_method} onChange={e=>set('billing_method',e.target.value)}>{Object.entries(billingLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Billing Cycle<select value={form.billing_cycle} onChange={e=>set('billing_cycle',e.target.value)}>{Object.entries(cycleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Billing Cutoff Day<input type="number" min="1" max="31" value={form.billing_cutoff_day} onChange={e=>set('billing_cutoff_day',e.target.value)} placeholder="e.g. 25"/></label><label>Payment Terms (days)<input type="number" min="0" value={form.payment_terms_days} onChange={e=>set('payment_terms_days',e.target.value)} placeholder="e.g. 30"/><small>{form.payment_terms_days!==''?`Net ${form.payment_terms_days}`:'Contract-specific'}</small></label><label className={styles.switchRow}><span>Is there retainage?<small>Capture withheld contract value and release terms.</small></span><input type="checkbox" checked={form.has_retainage} onChange={e=>set('has_retainage',e.target.checked)}/></label>{form.has_retainage&&<><label>Retainage (%)<input type="number" min="0" max="100" value={form.retainage_percent} onChange={e=>set('retainage_percent',e.target.value)}/></label><label>Retainage Value<input value={money(retainageValue,form.currency_code)} readOnly/></label><label>Retainage Payment Criteria (days)<input type="number" min="0" value={form.retainage_payment_days} onChange={e=>set('retainage_payment_days',e.target.value)}/></label></>}<label className={styles.switchRow}><span>Is material included in this contract value?<small>Separate material value when applicable.</small></span><input type="checkbox" checked={form.material_included} onChange={e=>set('material_included',e.target.checked)}/></label>{form.material_included&&<label>Material Value<input type="number" min="0" step="0.01" value={form.material_value} onChange={e=>set('material_value',e.target.value)}/></label>}<div className={styles.note}><b>Billing setup</b><span>Progress / Percent Complete supports production-based progress billing and a future Schedule of Values / Payment Application workflow.</span></div></div>}
 {step===4&&<div className={styles.grid}><label>Planned Start Date<input type="date" value={form.planned_start_date} onChange={e=>set('planned_start_date',e.target.value)}/></label><label>Contractual Term (calendar days)<input type="number" min="0" value={form.contractual_term_days} onChange={e=>set('contractual_term_days',e.target.value)}/></label><label>Planned End Date<input type="date" value={plannedEnd} readOnly/></label>{form.has_retainage&&<label>Probable Retainage Payment Date<input type="date" value={probableRetainageDate} readOnly/></label>}<label className={styles.wide}>Client Success Criteria<textarea value={form.success_criteria} onChange={e=>set('success_criteria',e.target.value)} rows={6}/></label></div>}
 {step===5&&<div className={styles.review}><div><span>Project ID</span><b>{projectNumber}</b></div><div><span>Project</span><b>{form.name||'—'}</b><small>{form.contract_number||'No contract number'}</small></div><div><span>Client</span><b>{form.client_name||'—'}</b></div><div><span>Location</span><b>{[form.city,form.state_region,form.country_code].filter(Boolean).join(', ')||'—'}</b></div><div><span>Contract Value</span><b>{money(form.contract_value,form.currency_code)}</b></div><div><span>Billing</span><b>{billingLabels[form.billing_method]||'—'}</b><small>{cycleLabels[form.billing_cycle]||'—'}{form.billing_cutoff_day?` · Cutoff ${form.billing_cutoff_day}`:''}{form.payment_terms_days!==''?` · Net ${form.payment_terms_days}`:''}</small></div><div><span>Retainage</span><b>{form.has_retainage?`${form.retainage_percent||0}% · ${money(retainageValue,form.currency_code)}`:'No retainage'}</b></div><div><span>Schedule</span><b>{form.planned_start_date||'—'} → {plannedEnd||'—'}</b></div><div className={styles.reviewWide}><span>Client Success Criteria</span><b>{form.success_criteria||'Not defined'}</b></div></div>}
 {error&&<div className={styles.error}>{error}</div>}</div><footer className={styles.actions}><button disabled={step===1||saving} onClick={()=>setStep(s=>s-1)}>← Back</button><span>Changes update the same shared Project ID.</span>{step<5?<button className={styles.primary} onClick={next}>Continue →</button>:<button className={styles.primary} disabled={saving} onClick={saveProject}>{saving?'Saving...':'Save Changes'}</button>}</footer></div></section></main>
}
