'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '../../../lib/supabase/client'
import styles from './company.module.css'

const supabase=createClient()
const empty={name:'',legal_name:'',tax_id:'',email:'',phone:'',website:'',address_line:'',address_line_2:'',city:'',state_region:'',postal_code:'',country_code:'BR',default_currency:'BRL',timezone:'America/Sao_Paulo',unit_system:'metric',date_format:'DD/MM/YYYY',default_language:'en',logo_url:'',slug:'',created_at:null,updated_at:null}
const moduleLabels={project_setup:'Projects',planning:'PreCon',daily_reports:'Daily Reports',workforce:'Workforce',production_control:'FieldOp'}
const fmtDate=v=>v?new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v)):'—'

export default function CompanySettings(){
 const router=useRouter(); const [form,setForm]=useState(empty); const [organizationId,setOrganizationId]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [license,setLicense]=useState(null); const [platformOrg,setPlatformOrg]=useState(false)
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:members,error}=await supabase.from('organization_members').select('organization_id,role,status,organizations(*)').eq('user_id',user.id).eq('status','active');if(!active)return;if(error){setMessage(error.message);setLoading(false);return}const membership=members?.find(x=>['owner','admin'].includes(x.role))||members?.[0];const org=membership?.organizations;if(!org){setMessage('No company is connected to this account yet.');setLoading(false);return}setOrganizationId(org.id);setForm({...empty,...org});
 try{const {data,error:rpcError}=await supabase.rpc('get_platform_organizations');if(!rpcError&&Array.isArray(data)){const row=data.find(x=>x.organization_id===org.id);if(row){setLicense(row);setPlatformOrg(true)}}}catch(_e){}
 setLoading(false)})().catch(e=>{if(active){setMessage(e.message);setLoading(false)}});return()=>{active=false}},[router])
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}))
 async function save(e){e.preventDefault();if(!organizationId)return;setSaving(true);setMessage('');const payload={name:form.name.trim(),legal_name:form.legal_name||null,tax_id:form.tax_id||null,email:form.email||null,phone:form.phone||null,website:form.website||null,address_line:form.address_line||null,address_line_2:form.address_line_2||null,city:form.city||null,state_region:form.state_region||null,postal_code:form.postal_code||null,country_code:form.country_code||null,default_currency:form.default_currency,timezone:form.timezone,unit_system:form.unit_system,date_format:form.date_format,default_language:form.default_language,logo_url:form.logo_url||null};const {data,error}=await supabase.from('organizations').update(payload).eq('id',organizationId).select('*').single();setSaving(false);if(error)setMessage(error.message);else{setForm(v=>({...v,...data}));setMessage('Company profile saved successfully.')}}
 const modules=useMemo(()=>license?.enabled_modules||[],[license])
 if(loading)return <main className={styles.loading}>Loading company settings...</main>
 return <main className={styles.page}>
  <header className={styles.header}><div className={styles.brand}><Image src="/logo-white.png" alt="RitsuFlow" width={180} height={65} priority/></div><div className={styles.headerTitle}><h1>Company Profile</h1><p>Organization-level information used across RitsuFlow</p></div><Link className={styles.backButton} href="/workspaces">← Back to Workspaces</Link></header>
  <form onSubmit={save} className={styles.content}>
   <section className={styles.intro}><div><span>SETTINGS / COMPANY PROFILE</span><h2>Company Profile</h2><p>Identity, contact information and organization defaults in one place.</p></div><div className={styles.introActions}>{platformOrg&&<div className={styles.platformBadge}><b>♛ Platform Organization</b><small>RitsuFlow administration</small></div>}<button type="submit" disabled={saving||!organizationId}>{saving?'Saving...':'Save Changes'}</button></div></section>
   {message&&<div className={styles.message}>{message}</div>}
   <div className={styles.topGrid}>
    <section className={styles.card}><div className={styles.cardTitle}><span>▥</span><div><h3>Company Identity</h3><p>Basic information about your organization.</p></div></div><div className={styles.fields}>
     <label className={styles.full}>Company Name<input required name="name" value={form.name} onChange={change}/></label><label className={styles.full}>Legal Name<input name="legal_name" value={form.legal_name||''} onChange={change}/></label><label>Tax ID / Registration<input name="tax_id" value={form.tax_id||''} onChange={change} placeholder="CNPJ, EIN, VAT..."/></label><label>Company Slug<input value={form.slug||''} disabled/><small>Structural tenant identifier.</small></label><label>Organization Type<input value={platformOrg?'Platform Organization':'Customer Organization'} disabled/></label><label>Organization ID<input value={organizationId||''} disabled title={organizationId||''}/></label>
    </div></section>
    <section className={styles.card}><div className={styles.cardTitle}><span>✉</span><div><h3>Contact & Address</h3><p>How can we reach your organization?</p></div></div><div className={styles.fields}>
     <label>Company Email<input type="email" name="email" value={form.email||''} onChange={change}/></label><label>Phone<input name="phone" value={form.phone||''} onChange={change}/></label><label className={styles.full}>Website<input name="website" value={form.website||''} onChange={change} placeholder="https://"/></label><div className={styles.sectionLabel}>● Business Address</div><label>Address Line 1<input name="address_line" value={form.address_line||''} onChange={change}/></label><label>Address Line 2<input name="address_line_2" value={form.address_line_2||''} onChange={change}/></label><label>City<input name="city" value={form.city||''} onChange={change}/></label><label>State / Province<input name="state_region" value={form.state_region||''} onChange={change}/></label><label>Postal Code<input name="postal_code" value={form.postal_code||''} onChange={change}/></label><label>Country Code<input name="country_code" maxLength="2" value={form.country_code||''} onChange={change} placeholder="BR, US, CA..."/></label>
    </div></section>
    <section className={styles.card}><div className={styles.cardTitle}><span>⚙</span><div><h3>Branding & Regional Defaults</h3><p>Visual identity and defaults for new projects.</p></div></div><div className={styles.brandingRow}><div className={styles.logoBox}>{form.logo_url?<img src={form.logo_url} alt="Company logo"/>:<div>🏢<span>No company logo</span></div>}</div><label className={styles.logoUrl}>Logo URL<input name="logo_url" value={form.logo_url||''} onChange={change} placeholder="https://..."/></label></div><div className={styles.sectionLabel}>● Regional Defaults</div><div className={styles.fields}>
     <label>Default Currency<select name="default_currency" value={form.default_currency} onChange={change}><option value="BRL">BRL — Brazilian Real</option><option value="USD">USD — US Dollar</option><option value="CAD">CAD — Canadian Dollar</option><option value="EUR">EUR — Euro</option></select></label><label>Unit System<select name="unit_system" value={form.unit_system} onChange={change}><option value="metric">Metric (m, kg, m²)</option><option value="imperial">Imperial / US Customary</option></select></label><label>Time Zone<select name="timezone" value={form.timezone} onChange={change}><option value="America/Sao_Paulo">(UTC-03:00) Brasília</option><option value="America/New_York">Eastern Time</option><option value="America/Chicago">Central Time</option><option value="America/Denver">Mountain Time</option><option value="America/Los_Angeles">Pacific Time</option><option value="America/Toronto">Toronto</option><option value="UTC">UTC</option></select></label><label>Date Format<select name="date_format" value={form.date_format} onChange={change}><option value="DD/MM/YYYY">DD/MM/YYYY</option><option value="MM/DD/YYYY">MM/DD/YYYY</option><option value="YYYY-MM-DD">YYYY-MM-DD</option></select></label><label>Default Language<select name="default_language" value={form.default_language} onChange={change}><option value="en">English</option><option value="pt-BR">Português (Brasil)</option><option value="es">Español</option></select></label>
    </div></section>
   </div>
   <section className={`${styles.card} ${styles.licenseCard}`}><div className={styles.cardTitle}><span>▣</span><div><h3>Tenant & License Information</h3><p>License and module configuration managed by RitsuFlow.</p></div><div className={styles.readOnlyNote}>ⓘ Provisioning-controlled information</div></div><div className={styles.licenseGrid}>
    <div><small>License Plan</small><strong>{license?.plan_code||'—'}</strong></div><div><small>License Status</small><strong className={styles.active}>{license?.license_status||'—'}</strong></div><div><small>Seat Limit</small><strong>{license?.seat_limit??'—'}</strong></div><div><small>Seats Used</small><strong>{license?.seats_used??'—'}</strong></div><div><small>Start Date</small><strong>{fmtDate(license?.starts_at)}</strong></div><div><small>Expiration Date</small><strong>{fmtDate(license?.expires_at)}</strong></div><div className={styles.modules}><small>Enabled Modules</small><div>{modules.length?modules.map(m=><span key={m}>{moduleLabels[m]||m}</span>):<strong>—</strong>}</div></div>
   </div></section>
   <section className={`${styles.card} ${styles.adminCard}`}><div className={styles.cardTitle}><span>●●</span><div><h3>Administration</h3><p>Ownership and administrative information.</p></div></div><div className={styles.adminGrid}><div><small>Primary Admin</small><strong>{license?.primary_admin_name||'—'}</strong><span>{license?.primary_admin_email||''}</span></div><div><small>Created At</small><strong>{fmtDate(form.created_at)}</strong></div><div><small>Last Updated</small><strong>{fmtDate(form.updated_at)}</strong></div><div><small>Data Isolation</small><strong>Tenant isolated</strong></div></div></section>
  </form>
 </main>
}
