'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '../../../lib/supabase/client'
import { useLanguage } from '../../../contexts/LanguageContext'
import { LOCALE_OPTIONS, normalizeLocale } from '../../../i18n/config'
import styles from './company.module.css'

const supabase=createClient()
const empty={name:'',legal_name:'',tax_id:'',email:'',phone:'',website:'',address_line:'',address_line_2:'',city:'',state_region:'',postal_code:'',country_code:'BR',default_currency:'BRL',timezone:'America/Sao_Paulo',unit_system:'metric',date_format:'DD/MM/YYYY',default_locale:'en-US',logo_url:'',slug:'',organization_type:'customer',organization_number:'',created_at:null,updated_at:null}
const moduleLabels={project_setup:'Projects',planning:'PreCon',daily_reports:'Daily Reports',workforce:'Workforce',production_control:'FieldOp'}
const logoButton={height:30,border:'1px solid #cbdbe2',borderRadius:6,background:'#fff',color:'#143a4c',fontSize:9,fontWeight:800,padding:'0 10px',cursor:'pointer',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:5}
const legacyLocale=v=>v==='en'?'en-US':normalizeLocale(v)
function loadScript(src,id){return new Promise((resolve,reject)=>{if(document.getElementById(id)){resolve();return}const s=document.createElement('script');s.id=id;s.src=src;s.async=true;s.defer=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}

export default function CompanySettings(){
 const router=useRouter();const fileRef=useRef(null);const {locale,changeLanguage,t}=useLanguage();const [form,setForm]=useState(empty);const [organizationId,setOrganizationId]=useState(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState('');const [license,setLicense]=useState(null);const [platformRole,setPlatformRole]=useState(null)
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:members,error}=await supabase.from('organization_members').select('organization_id,role,status,organizations(*)').eq('user_id',user.id).eq('status','active');if(!active)return;if(error){setMessage(error.message);setLoading(false);return}const membership=members?.find(x=>['owner','admin'].includes(x.role))||members?.[0];const org=membership?.organizations;if(!org){setMessage('No company is connected to this account yet.');setLoading(false);return}const resolved=normalizeLocale(org.default_locale||legacyLocale(org.default_language));setOrganizationId(org.id);setForm({...empty,...org,default_locale:resolved});changeLanguage(resolved);const [{data:roles},{data:licenseRows}]=await Promise.all([supabase.from('platform_user_roles').select('role,is_active').eq('user_id',user.id).eq('is_active',true).maybeSingle(),supabase.rpc('get_platform_organizations')]);if(roles)setPlatformRole(roles.role);if(Array.isArray(licenseRows)){const row=licenseRows.find(x=>x.organization_id===org.id);if(row)setLicense(row)}setLoading(false)})().catch(e=>{if(active){setMessage(e.message);setLoading(false)}});return()=>{active=false}},[router,changeLanguage])
 const isPlatformOperator=form.organization_type==='platform_operator'
 const change=e=>{const {name,value}=e.target;setForm(v=>({...v,[name]:value}));if(name==='default_locale')changeLanguage(value)}
 const fmtDate=v=>v?new Intl.DateTimeFormat(locale,{year:'numeric',month:'short',day:'numeric'}).format(new Date(v)):'—'
 async function persistLogo(file){if(!organizationId||!file)return;const allowed=['image/png','image/jpeg','image/webp','image/svg+xml'];if(!allowed.includes(file.type))throw new Error('Validation failed: use a PNG, JPG, WEBP or SVG image.');if(file.size>5*1024*1024)throw new Error('Validation failed: logo must be 5 MB or smaller.');const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${organizationId}/logo-${Date.now()}.${ext}`;const {error:uploadError}=await supabase.storage.from('company-assets').upload(path,file,{cacheControl:'3600',upsert:true,contentType:file.type});if(uploadError)throw uploadError;const {data}=supabase.storage.from('company-assets').getPublicUrl(path);const url=data?.publicUrl;if(!url)throw new Error('Public URL generation failed.');const {error:updateError}=await supabase.from('organizations').update({logo_url:url}).eq('id',organizationId);if(updateError)throw updateError;setForm(v=>({...v,logo_url:url}))}
 async function uploadComputer(e){const file=e.target.files?.[0];if(!file)return;setUploading(true);setMessage('');try{await persistLogo(file)}catch(err){setMessage(err.message||'Logo upload failed.')}finally{setUploading(false);e.target.value=''}}
 async function importDrive(){const apiKey=process.env.NEXT_PUBLIC_GOOGLE_DRIVE_API_KEY;const clientId=process.env.NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID;if(!apiKey||!clientId){setMessage('Google Drive import needs API configuration in Vercel.');return}setUploading(true);try{await Promise.all([loadScript('https://apis.google.com/js/api.js','google-api-js'),loadScript('https://accounts.google.com/gsi/client','google-identity-js')]);await new Promise((resolve,reject)=>window.gapi.load('picker',{callback:resolve,onerror:reject}));const tokenClient=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/drive.readonly',callback:tokenResponse=>{const view=new window.google.picker.View(window.google.picker.ViewId.DOCS_IMAGES);new window.google.picker.PickerBuilder().setDeveloperKey(apiKey).setOAuthToken(tokenResponse.access_token).addView(view).setCallback(async data=>{if(data.action===window.google.picker.Action.PICKED){try{const doc=data.docs[0];const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(doc.id)}?alt=media`,{headers:{Authorization:`Bearer ${tokenResponse.access_token}`}});const blob=await response.blob();await persistLogo(new File([blob],doc.name||'company-logo',{type:blob.type||doc.mimeType||'image/png'}))}catch(err){setMessage(err.message)}finally{setUploading(false)}}else if(data.action===window.google.picker.Action.CANCEL)setUploading(false)}).build().setVisible(true)}});tokenClient.requestAccessToken({prompt:'consent'})}catch(err){setUploading(false);setMessage(err.message||'Could not open Google Drive.')}}
 async function save(e){e.preventDefault();if(!organizationId)return;setSaving(true);setMessage('');const payload={name:form.name.trim(),legal_name:form.legal_name||null,tax_id:form.tax_id||null,email:form.email||null,phone:form.phone||null,website:form.website||null,address_line:form.address_line||null,address_line_2:form.address_line_2||null,city:form.city||null,state_region:form.state_region||null,postal_code:form.postal_code||null,country_code:form.country_code||null,default_currency:form.default_currency,timezone:form.timezone,unit_system:form.unit_system,date_format:form.date_format,default_locale:normalizeLocale(form.default_locale),logo_url:form.logo_url||null};const {data,error}=await supabase.from('organizations').update(payload).eq('id',organizationId).select('*').single();setSaving(false);if(error)setMessage(error.message);else{setForm(v=>({...v,...data}));changeLanguage(data.default_locale);setMessage(t('company.saved'))}}
 const modules=useMemo(()=>license?.enabled_modules||[],[license])
 if(loading)return <main className={styles.loading}>{t('company.loading')}</main>
 return <main className={styles.page}><form onSubmit={save} className={styles.formShell}>
  <header className={styles.header}><div className={styles.brand}><Image src="/logo-white.png" alt="RitsuFlow" width={180} height={65} priority/></div><div className={styles.headerTitle}><h1>{t('company.title')}</h1><p>{t(isPlatformOperator?'company.operatorSubtitle':'company.subtitle')}</p></div><div className={styles.headerActions}>{isPlatformOperator&&<div className={styles.platformBadge}><b>♛ {t('company.platformOperator')}</b><small>{platformRole?.replaceAll('_',' ')||'Commercial administration'}</small></div>}<Link className={styles.backButton} href="/settings">← {t('company.back')}</Link><button className={styles.saveButton} type="submit" disabled={saving||!organizationId}>{saving?t('company.saving'):t('company.save')}</button></div></header>
  <div className={styles.content}>{message&&<div className={styles.message}>{message}</div>}<div className={styles.topGrid}>
   <section className={styles.card}><div className={styles.cardTitle}><span>▥</span><div><h3>{t('company.identity')}</h3><p>{t('company.identityHelp')}</p></div></div><div className={styles.fields}><label className={styles.full}>{t('company.companyName')}<input required name="name" value={form.name} onChange={change}/></label><label className={styles.full}>{t('company.legalName')}<input name="legal_name" value={form.legal_name||''} onChange={change}/></label><label>{t('company.taxId')}<input name="tax_id" value={form.tax_id||''} onChange={change} placeholder="CNPJ, EIN, VAT..."/></label><label>{t('company.slug')}<input value={form.slug||''} disabled/><small>{t('company.slugHelp')}</small></label><label>{t('company.organizationType')}<input value={t(isPlatformOperator?'company.platformOperator':'company.customerOrganization')} disabled/></label><label>{t('company.organizationId')}<input value={form.organization_number||'—'} disabled/><small>{t('company.organizationIdHelp')}</small></label></div></section>
   <section className={styles.card}><div className={styles.cardTitle}><span>✉</span><div><h3>{t('company.contact')}</h3><p>{t('company.contactHelp')}</p></div></div><div className={styles.fields}><label>{t('company.email')}<input type="email" name="email" value={form.email||''} onChange={change}/></label><label>{t('company.phone')}<input name="phone" value={form.phone||''} onChange={change}/></label><label className={styles.full}>{t('company.website')}<input name="website" value={form.website||''} onChange={change} placeholder="https://"/></label><div className={styles.sectionLabel}>● {t('company.businessAddress')}</div><label>{t('company.address1')}<input name="address_line" value={form.address_line||''} onChange={change}/></label><label>{t('company.address2')}<input name="address_line_2" value={form.address_line_2||''} onChange={change}/></label><label>{t('company.city')}<input name="city" value={form.city||''} onChange={change}/></label><label>{t('company.state')}<input name="state_region" value={form.state_region||''} onChange={change}/></label><label>{t('company.postalCode')}<input name="postal_code" value={form.postal_code||''} onChange={change}/></label><label>{t('company.countryCode')}<input name="country_code" maxLength="2" value={form.country_code||''} onChange={change} placeholder="BR, US, CA..."/></label></div></section>
   <section className={styles.card}><div className={styles.cardTitle}><span>⚙</span><div><h3>{t('company.branding')}</h3><p>{t('company.brandingHelp')}</p></div></div><div className={styles.brandingRow}><div className={styles.logoBox}>{form.logo_url?<img src={form.logo_url} alt="Company logo"/>:<div>🏢<span>{t('company.noLogo')}</span></div>}</div><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={uploadComputer} style={{display:'none'}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><button type="button" style={logoButton} disabled={uploading} onClick={()=>fileRef.current?.click()}>↑ {uploading?t('company.working'):t('company.upload')}</button><button type="button" style={logoButton} disabled={uploading} onClick={importDrive}>▣ {t('company.drive')}</button></div><small>{t('company.logoHelp')}</small></div><div className={styles.sectionLabel}>● {t('company.regional')}</div><div className={styles.fields}><label>{t('company.currency')}<select name="default_currency" value={form.default_currency} onChange={change}><option value="BRL">BRL — Brazilian Real</option><option value="USD">USD — US Dollar</option><option value="CAD">CAD — Canadian Dollar</option><option value="EUR">EUR — Euro</option></select></label><label>{t('company.units')}<select name="unit_system" value={form.unit_system} onChange={change}><option value="metric">{t('company.metric')}</option><option value="imperial">{t('company.imperial')}</option></select></label><label>{t('company.timezone')}<select name="timezone" value={form.timezone} onChange={change}><option value="America/Sao_Paulo">(UTC-03:00) Brasília</option><option value="America/New_York">Eastern Time</option><option value="America/Chicago">Central Time</option><option value="America/Denver">Mountain Time</option><option value="America/Los_Angeles">Pacific Time</option><option value="America/Toronto">Toronto</option><option value="UTC">UTC</option></select></label><label>{t('company.dateFormat')}<select name="date_format" value={form.date_format} onChange={change}><option value="DD/MM/YYYY">DD/MM/YYYY</option><option value="MM/DD/YYYY">MM/DD/YYYY</option><option value="YYYY-MM-DD">YYYY-MM-DD</option></select></label><label>{t('company.language')}<select name="default_locale" value={form.default_locale} onChange={change}>{LOCALE_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label></div></section>
  </div>
  {!isPlatformOperator&&<section className={`${styles.card} ${styles.licenseCard}`}><div className={styles.cardTitle}><span>▣</span><div><h3>{t('company.license')}</h3><p>{t('company.licenseHelp')}</p></div></div><div className={styles.licenseGrid}><div><small>{t('company.plan')}</small><strong>{license?.plan_code||'—'}</strong></div><div><small>{t('company.status')}</small><strong className={styles.active}>{license?.license_status||'—'}</strong></div><div><small>{t('company.seatLimit')}</small><strong>{license?.seat_limit??'—'}</strong></div><div><small>{t('company.seatsUsed')}</small><strong>{license?.seats_used??'—'}</strong></div><div><small>{t('company.startDate')}</small><strong>{fmtDate(license?.starts_at)}</strong></div><div><small>{t('company.expirationDate')}</small><strong>{fmtDate(license?.expires_at)}</strong></div><div className={styles.modules}><small>{t('company.enabledModules')}</small><div>{modules.length?modules.map(m=><span key={m}>{moduleLabels[m]||m}</span>):<strong>—</strong>}</div></div></div></section>}
  <section className={`${styles.card} ${styles.adminCard}`}><div className={styles.cardTitle}><span>●●</span><div><h3>{t('company.administration')}</h3><p>{t('company.administrationHelp')}</p></div></div><div className={styles.adminGrid}><div><small>{t(isPlatformOperator?'company.platformRole':'company.primaryAdmin')}</small><strong>{isPlatformOperator?(platformRole?.replaceAll('_',' ')||'—'):(license?.primary_admin_name||'—')}</strong><span>{isPlatformOperator?'RitsuFlow platform administration':(license?.primary_admin_email||'')}</span></div><div><small>{t('company.created')}</small><strong>{fmtDate(form.created_at)}</strong></div><div><small>{t('company.updated')}</small><strong>{fmtDate(form.updated_at)}</strong></div><div><small>{t('company.isolation')}</small><strong>{t('company.isolated')}</strong></div></div></section>
  </div>
 </form></main>
}
