'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '../../../lib/supabase/client'
import styles from './company.module.css'

const supabase=createClient()
const empty={name:'',legal_name:'',tax_id:'',email:'',phone:'',website:'',address_line:'',address_line_2:'',city:'',state_region:'',postal_code:'',country_code:'BR',default_currency:'BRL',timezone:'America/Sao_Paulo',unit_system:'metric',logo_url:''}

export default function CompanySettings(){
 const router=useRouter(); const [form,setForm]=useState(empty); const [organizationId,setOrganizationId]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:members,error}=await supabase.from('organization_members').select('organization_id,role,status,organizations(*)').eq('user_id',user.id).eq('status','active');if(!active)return;if(error){setMessage(error.message);setLoading(false);return}const membership=members?.find(x=>['owner','admin'].includes(x.role))||members?.[0];const org=membership?.organizations;if(org){setOrganizationId(org.id);setForm({...empty,...org})}else setMessage('No company is connected to this account yet.');setLoading(false)})().catch(e=>{if(active){setMessage(e.message);setLoading(false)}});return()=>{active=false}},[router])
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}))
 async function save(e){e.preventDefault();if(!organizationId)return;setSaving(true);setMessage('');const payload={name:form.name.trim(),legal_name:form.legal_name||null,tax_id:form.tax_id||null,email:form.email||null,phone:form.phone||null,website:form.website||null,address_line:form.address_line||null,address_line_2:form.address_line_2||null,city:form.city||null,state_region:form.state_region||null,postal_code:form.postal_code||null,country_code:form.country_code||null,default_currency:form.default_currency,timezone:form.timezone,unit_system:form.unit_system,logo_url:form.logo_url||null};const {error}=await supabase.from('organizations').update(payload).eq('id',organizationId);setSaving(false);setMessage(error?error.message:'Company profile saved successfully.')}
 if(loading)return <main className={styles.loading}>Loading company settings...</main>
 return <main className={styles.page}><header className={styles.header}><Image src="/logo-white.png" alt="RitsuFlow" width={180} height={65}/><div><h1>Company Profile</h1><p>Organization-level information used across RitsuFlow</p></div><Link href="/workspaces">← Back to Workspaces</Link></header><form onSubmit={save} className={styles.content}>
  <section className={styles.intro}><div><span>ORGANIZATION SETTINGS</span><h2>Company Profile</h2><p>This company is the tenant that owns its projects, users, standards and RitsuFlow configuration.</p></div><button type="submit" disabled={saving||!organizationId}>{saving?'Saving...':'Save Changes'}</button></section>
  {message&&<div className={styles.message}>{message}</div>}
  <div className={styles.columns}><div className={styles.stack}>
   <section className={styles.card}><h3>Company Identity</h3><div className={styles.grid}><label>Company Name<input required name="name" value={form.name} onChange={change}/></label><label>Legal Name<input name="legal_name" value={form.legal_name||''} onChange={change}/></label><label>Tax ID / Registration<input name="tax_id" value={form.tax_id||''} onChange={change} placeholder="CNPJ, EIN, VAT..."/></label><label>Company Slug<input value={form.slug||''} disabled/></label></div></section>
   <section className={styles.card}><h3>Contact Information</h3><div className={styles.grid}><label>Company Email<input type="email" name="email" value={form.email||''} onChange={change}/></label><label>Phone<input name="phone" value={form.phone||''} onChange={change}/></label><label className={styles.full}>Website<input name="website" value={form.website||''} onChange={change} placeholder="https://"/></label></div></section>
   <section className={styles.card}><h3>Company Address</h3><div className={styles.grid}><label className={styles.full}>Address<input name="address_line" value={form.address_line||''} onChange={change}/></label><label className={styles.full}>Address Line 2<input name="address_line_2" value={form.address_line_2||''} onChange={change}/></label><label>City<input name="city" value={form.city||''} onChange={change}/></label><label>State / Region<input name="state_region" value={form.state_region||''} onChange={change}/></label><label>Postal Code<input name="postal_code" value={form.postal_code||''} onChange={change}/></label><label>Country Code<input name="country_code" maxLength="2" value={form.country_code||''} onChange={change}/></label></div></section>
  </div><div className={styles.stack}>
   <section className={styles.card}><h3>Company Logo</h3><div className={styles.logoBox}>{form.logo_url?<img src={form.logo_url} alt="Company logo"/>:<div>🏢<span>No company logo</span></div>}</div><label>Logo URL<input name="logo_url" value={form.logo_url||''} onChange={change} placeholder="https://..."/></label><small>Logo upload to RitsuFlow Storage will be connected in the next settings step.</small></section>
   <section className={styles.card}><h3>Regional Defaults</h3><label>Default Currency<select name="default_currency" value={form.default_currency} onChange={change}><option value="BRL">BRL — Brazilian Real</option><option value="USD">USD — US Dollar</option><option value="CAD">CAD — Canadian Dollar</option><option value="EUR">EUR — Euro</option></select></label><label>Unit System<select name="unit_system" value={form.unit_system} onChange={change}><option value="metric">Metric</option><option value="imperial">Imperial / US Customary</option></select></label><label>Timezone<select name="timezone" value={form.timezone} onChange={change}><option value="America/Sao_Paulo">America/São Paulo</option><option value="America/New_York">America/New York</option><option value="America/Chicago">America/Chicago</option><option value="America/Denver">America/Denver</option><option value="America/Los_Angeles">America/Los Angeles</option><option value="America/Toronto">America/Toronto</option><option value="UTC">UTC</option></select></label></section>
   <section className={styles.card}><h3>Tenant Information</h3><div className={styles.tenant}><span>Organization ID</span><code>{organizationId||'—'}</code><span>Data Isolation</span><strong>Tenant isolated</strong><span>Status</span><strong>Active</strong></div></section>
  </div></div>
 </form></main>
}
