'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../../lib/supabase'

const roles=[
 {value:'manager',label:'Project Manager'},
 {value:'superintendent',label:'Superintendent'},
 {value:'project_engineer',label:'Project Engineer'},
 {value:'planner',label:'Planner'},
 {value:'field_engineer',label:'Field Engineer'},
 {value:'foreman',label:'Foreman'},
 {value:'viewer',label:'Viewer'},
]
const roleLabel=value=>roles.find(r=>r.value===value)?.label||(value==='field'?'Field / Site':value||'Viewer')
const dateTime=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'
const profileLabel=profile=>profile?.full_name?.trim()||profile?.display_name?.trim()||profile?.email?.trim()||''

export default function ProjectTeam({project}){
 const[members,setMembers]=useState([]),[users,setUsers]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[userId,setUserId]=useState(''),[role,setRole]=useState('manager')
 useEffect(()=>{if(!project?.id||!project?.organization_id)return;let active=true;(async()=>{setLoading(true);setError('');const[{data:pm,error:pmError},{data:om,error:omError}]=await Promise.all([supabase.from('project_members').select('project_id,user_id,role,joined_at').eq('project_id',project.id).order('joined_at',{ascending:true}),supabase.from('organization_members').select('user_id,role,status').eq('organization_id',project.organization_id).eq('status','active')]);if(!active)return;if(pmError||omError){setError(pmError?.message||omError?.message||'Unable to load project team.');setLoading(false);return}const ids=[...new Set([...(pm||[]).map(x=>x.user_id),...(om||[]).map(x=>x.user_id)])];let profiles=[];if(ids.length){const{data,error:e}=await supabase.from('user_profiles').select('user_id,email,full_name,display_name,job_title,status').in('user_id',ids);if(e){setError(e.message);setLoading(false);return}profiles=data||[]}const byId=Object.fromEntries(profiles.map(p=>[p.user_id,p]));setUsers((om||[]).map(x=>({...x,profile:byId[x.user_id]||null})).filter(x=>profileLabel(x.profile)));setMembers((pm||[]).map(x=>({...x,profile:byId[x.user_id]||null})));setLoading(false)})();return()=>{active=false}},[project?.id,project?.organization_id])
 const available=useMemo(()=>users.filter(u=>!members.some(m=>m.user_id===u.user_id)),[users,members])
 useEffect(()=>{if(!userId&&available.length)setUserId(available[0].user_id);if(userId&&!available.some(u=>u.user_id===userId))setUserId(available[0]?.user_id||'')},[available,userId])
 async function addMember(){if(!userId||saving)return;setSaving(true);setError('');const{data,error:e}=await supabase.from('project_members').insert({project_id:project.id,user_id:userId,role}).select('project_id,user_id,role,joined_at').single();if(e){setError(e.message);setSaving(false);return}const u=users.find(x=>x.user_id===userId);setMembers(current=>[...current,{...data,profile:u?.profile||null}]);setSaving(false)}
 async function changeRole(member,nextRole){setError('');const{error:e}=await supabase.from('project_members').update({role:nextRole}).eq('project_id',project.id).eq('user_id',member.user_id);if(e){setError(e.message);return}setMembers(current=>current.map(m=>m.user_id===member.user_id?{...m,role:nextRole}:m))}
 async function removeMember(member){const name=profileLabel(member.profile)||'this team member';if(!window.confirm(`Remove ${name} from this project?`))return;setError('');const{error:e}=await supabase.from('project_members').delete().eq('project_id',project.id).eq('user_id',member.user_id);if(e){setError(e.message);return}setMembers(current=>current.filter(m=>m.user_id!==member.user_id))}
 return <div style={wrap}>{error&&<div style={errorBox}>{error}</div>}<div style={toolbar}><select value={userId} onChange={e=>setUserId(e.target.value)} style={select} disabled={!available.length}>{available.length?available.map(u=><option key={u.user_id} value={u.user_id}>{profileLabel(u.profile)}</option>):<option value="">No additional named users available</option>}</select><select value={role} onChange={e=>setRole(e.target.value)} style={select}>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select><button onClick={addMember} disabled={!userId||saving} style={{...addButton,...((!userId||saving)?disabled:{})}}>{saving?'Adding...':'＋ Add Team Member'}</button></div><div style={list}>{loading?<div style={empty}>Loading team...</div>:members.length?<><div style={head}><span>Name</span><span>Job Title</span><span>Project Role</span><span>Added</span><span>Actions</span></div>{members.map(m=><div key={m.user_id} style={row}><div><strong>{profileLabel(m.profile)||'Profile unavailable'}</strong><div style={email}>{m.profile?.email||''}</div></div><span>{m.profile?.job_title||'—'}</span>{m.role==='field'?<select value="field" onChange={e=>changeRole(m,e.target.value)} style={roleSelect}><option value="field">{roleLabel('field')}</option>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select>:<select value={m.role||'viewer'} onChange={e=>changeRole(m,e.target.value)} style={roleSelect}>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select>}<span>{dateTime(m.joined_at)}</span><button onClick={()=>removeMember(m)} style={remove}>Remove</button></div>)}</>:<div style={empty}>No team members assigned to this project yet.</div>}</div></div>
}
const wrap={display:'flex',flexDirection:'column',minHeight:0,flex:1},toolbar={display:'grid',gridTemplateColumns:'minmax(180px,1.4fr) minmax(150px,.8fr) auto',gap:8,marginTop:8,flex:'0 0 auto'},select={height:34,border:'1px solid #cddde4',borderRadius:7,padding:'0 9px',background:'#fff',color:'#25495a',fontWeight:700,fontSize:11.5},addButton={border:0,borderRadius:7,background:'#069b9b',color:'#fff',padding:'0 15px',fontWeight:800,fontSize:11.5,cursor:'pointer'},disabled={opacity:.55,cursor:'not-allowed'},errorBox={marginTop:8,padding:'7px 9px',border:'1px solid #efb0b0',background:'#fff3f3',color:'#a61b1b',borderRadius:7,fontSize:11,fontWeight:700},list={overflowY:'auto',minHeight:0,marginTop:8,border:'1px solid #dce7eb',borderRadius:7},head={display:'grid',gridTemplateColumns:'1.4fr .9fr 1fr .8fr .55fr',gap:8,padding:'7px 9px',background:'#f2f7f9',color:'#607784',fontSize:10,fontWeight:800,textTransform:'uppercase',position:'sticky',top:0},row={display:'grid',gridTemplateColumns:'1.4fr .9fr 1fr .8fr .55fr',gap:8,alignItems:'center',padding:'8px 9px',borderTop:'1px solid #e4ecef',fontSize:10.5,color:'#25495a'},email={fontSize:9.5,color:'#78909b',marginTop:2},roleSelect={width:'100%',height:28,border:'1px solid #d3e0e5',borderRadius:6,padding:'0 6px',background:'#fff',color:'#25495a',fontSize:10.5,fontWeight:700},remove={border:'1px solid #efc0c0',background:'#fffafa',color:'#c52c2c',borderRadius:6,padding:'5px 8px',fontWeight:800,fontSize:10,cursor:'pointer'},empty={padding:'18px 10px',color:'#718691',fontSize:11.5}