'use client'

import Link from 'next/link'
import { useEffect, useMemo, useRef, useState } from 'react'
import { createClient } from '../../../lib/supabase/client'

const ASPECT = 1
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v))
const isPdf=d=>d?.mime_type==='application/pdf'||d?.document_type==='PDF'||d?.file_name?.toLowerCase().endsWith('.pdf')

export default function LocationCardViewEditor({ project, locations, userId }) {
  const supabase=useMemo(()=>createClient(),[])
  const frameRef=useRef(null),canvasRef=useRef(null),pdfRef=useRef(null),dragRef=useRef(null)
  const [documents,setDocuments]=useState([]),[documentId,setDocumentId]=useState(''),[pageNumber,setPageNumber]=useState(1),[pageCount,setPageCount]=useState(1)
  const [mapId,setMapId]=useState(''),[geometries,setGeometries]=useState([]),[selectedId,setSelectedId]=useState(locations[0]?.id||'')
  const [baseSize,setBaseSize]=useState({width:0,height:0}),[view,setView]=useState({zoom:1,x:0,y:0}),[savedView,setSavedView]=useState(null),[drawingUrl,setDrawingUrl]=useState('')
  const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')

  useEffect(()=>{loadDocuments()},[])
  useEffect(()=>{if(documentId)loadPage()},[documentId,pageNumber])

  async function loadDocuments(){const {data,error:e}=await supabase.from('project_documents').select('id,file_name,storage_path,mime_type,document_type,created_at').eq('project_id',project.id).order('created_at',{ascending:false});if(e){setError(e.message);return}const pdfs=(data||[]).filter(isPdf);setDocuments(pdfs);setDocumentId(pdfs[0]?.id||'')}

  async function loadPage(){const doc=documents.find(d=>d.id===documentId);if(!doc)return;setLoading(true);setError('');setMessage('');try{const {data:signed,error:se}=await supabase.storage.from('project-documents').createSignedUrl(doc.storage_path,120);if(se||!signed?.signedUrl)throw new Error(se?.message||'Unable to access PDF.');const res=await fetch(signed.signedUrl);if(!res.ok)throw new Error(`Unable to download PDF (${res.status}).`);const bytes=await res.arrayBuffer(),pdfjs=await import('pdfjs-dist/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';if(pdfRef.current?.destroy)await pdfRef.current.destroy().catch(()=>{});pdfRef.current=await pdfjs.getDocument({data:bytes}).promise;setPageCount(pdfRef.current.numPages);const safe=Math.min(Math.max(1,pageNumber),pdfRef.current.numPages);if(safe!==pageNumber){setPageNumber(safe);return}const page=await pdfRef.current.getPage(safe),base=page.getViewport({scale:1}),scale=1500/base.width,vp=page.getViewport({scale}),dpr=Math.min(window.devicePixelRatio||1,2),canvas=canvasRef.current;canvas.width=Math.round(vp.width*dpr);canvas.height=Math.round(vp.height*dpr);canvas.style.width=`${vp.width}px`;canvas.style.height=`${vp.height}px`;await page.render({canvasContext:canvas.getContext('2d'),viewport:vp,transform:dpr===1?null:[dpr,0,0,dpr,0,0]}).promise;setDrawingUrl(canvas.toDataURL('image/png'));const size={width:vp.width,height:vp.height};setBaseSize(size);
      const {data:dm,error:me}=await supabase.from('project_drawing_maps').select('id,print_view').eq('project_id',project.id).eq('document_id',documentId).eq('page_number',safe).maybeSingle();if(me)throw me;setMapId(dm?.id||'');setSavedView(dm?.print_view?.mode==='card_view'?dm.print_view:null);if(dm?.id){const {data:g,error:ge}=await supabase.from('project_drawing_location_geometries').select('location_id,geometry').eq('drawing_map_id',dm.id).eq('page_number',safe);if(ge)throw ge;setGeometries(g||[])}else setGeometries([]);requestAnimationFrame(()=>applySavedOrFit(size,dm?.print_view));
    }catch(e){setError(e?.message||'Unable to load drawing.')}finally{setLoading(false)}}

  function frameSize(){const el=frameRef.current;return{width:Math.max(1,el?.clientWidth||900),height:Math.max(1,el?.clientHeight||900)}}
  function constrainView(next){if(!baseSize.width||!baseSize.height)return next;const frame=frameSize(),drawW=baseSize.width*next.zoom,drawH=baseSize.height*next.zoom;return{...next,x:drawW<=frame.width?(frame.width-drawW)/2:clamp(next.x,frame.width-drawW,0),y:drawH<=frame.height?(frame.height-drawH)/2:clamp(next.y,frame.height-drawH,0)}}
  function applySavedOrFit(size,saved){const frame=frameSize();if(saved?.mode==='card_view'&&saved.width>0&&saved.height>0){const zoom=Math.min(frame.width/(saved.width*size.width),frame.height/(saved.height*size.height));setView(constrainView({zoom,x:-saved.x*size.width*zoom,y:-saved.y*size.height*zoom}));return}const zoom=Math.min(frame.width/size.width,frame.height/size.height)*.92;setView(constrainView({zoom,x:(frame.width-size.width*zoom)/2,y:(frame.height-size.height*zoom)/2}))}
  function zoomAt(next){const frame=frameSize(),cx=frame.width/2,cy=frame.height/2,n=clamp(next,.15,8),wx=(cx-view.x)/view.zoom,wy=(cy-view.y)/view.zoom;setView(constrainView({zoom:n,x:cx-wx*n,y:cy-wy*n}))}
  function pointerDown(e){if(e.button!==0)return;e.preventDefault();dragRef.current={x:e.clientX,y:e.clientY,ox:view.x,oy:view.y};e.currentTarget.setPointerCapture?.(e.pointerId)}
  function pointerMove(e){if(!dragRef.current)return;const next={...view,x:dragRef.current.ox+e.clientX-dragRef.current.x,y:dragRef.current.oy+e.clientY-dragRef.current.y};setView(constrainView(next))}
  function pointerUp(e){dragRef.current=null;try{if(e.currentTarget.hasPointerCapture?.(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}catch{}}
  function currentCrop(){if(!baseSize.width||!baseSize.height||!Number.isFinite(view.zoom)||view.zoom<=0)return null;const frame=frameSize(),rawX=(-view.x/view.zoom)/baseSize.width,rawY=(-view.y/view.zoom)/baseSize.height,rawW=(frame.width/view.zoom)/baseSize.width,rawH=(frame.height/view.zoom)/baseSize.height,x=clamp(rawX,0,1),y=clamp(rawY,0,1),width=Math.min(Math.max(rawW,.001),Math.max(.001,1-x)),height=Math.min(Math.max(rawH,.001),Math.max(.001,1-y));if(![x,y,width,height].every(Number.isFinite)||width<=0||height<=0)return null;return{x:Number(x.toFixed(6)),y:Number(y.toFixed(6)),width:Number(width.toFixed(6)),height:Number(height.toFixed(6))}}
  async function ensureMap(){if(mapId)return mapId;const {data,error:e}=await supabase.from('project_drawing_maps').insert({project_id:project.id,document_id:documentId,page_number:pageNumber,drawing_type:'floor_plan',created_by:userId}).select('id').single();if(e)throw e;setMapId(data.id);return data.id}
  async function save(){const crop=currentCrop();if(!crop)return;setSaving(true);setError('');try{const id=await ensureMap(),payload={mode:'card_view',...crop,aspect_ratio:ASPECT};const {error:e}=await supabase.from('project_drawing_maps').update({print_view:payload}).eq('id',id);if(e)throw e;setSavedView(payload);setMessage('Card View saved. The live report preview now matches the framing that will print.')}catch(e){setError(e?.message||'Unable to save Card View.')}finally{setSaving(false)}}

  const selectedGeom=geometries.find(g=>g.location_id===selectedId)?.geometry,points=selectedGeom?.points||[],color=selectedGeom?.display?.color||'#008F84',opacity=Number(selectedGeom?.display?.fill_opacity??.35)
  const drawingStyle=baseSize.width?{width:baseSize.width,height:baseSize.height,transform:`translate3d(${view.x}px,${view.y}px,0) scale(${view.zoom})`,transformOrigin:'0 0'}:undefined
  const liveCrop=currentCrop()
  const previewDrawingStyle=liveCrop&&liveCrop.width>0&&liveCrop.height>0?{position:'absolute',left:`${-liveCrop.x/liveCrop.width*100}%`,top:`${-liveCrop.y/liveCrop.height*100}%`,width:`${100/liveCrop.width}%`,height:`${100/liveCrop.height}%`}:null

  return <main style={{minHeight:'100vh',background:'#eef4f7',fontFamily:'Arial,sans-serif',color:'#0b3348'}}>
    <header style={{height:76,background:'#063247',color:'#fff',display:'flex',alignItems:'center',padding:'0 28px',gap:18}}><Link href={`/projects/${project.id}/location-map`} style={{color:'#fff',textDecoration:'none',fontWeight:800}}>← Location Map</Link><div><small>{project.project_id||project.code} · {project.name}</small><div style={{fontSize:24,fontWeight:900}}>Set Card View</div></div><div style={{marginLeft:'auto',fontSize:12,opacity:.85}}>Adjust on the right. The report preview updates live on the left.</div></header>
    <section style={{padding:20,maxWidth:1760,margin:'0 auto'}}>
      <div style={{display:'flex',gap:10,alignItems:'center',marginBottom:12,background:'#fff',padding:12,borderRadius:12,border:'1px solid #d6e1e7'}}><select value={documentId} onChange={e=>{setDocumentId(e.target.value);setPageNumber(1)}} style={{height:38,minWidth:260}}>{documents.map(d=><option key={d.id} value={d.id}>{d.file_name}</option>)}</select><button disabled={pageNumber<=1} onClick={()=>setPageNumber(p=>p-1)}>‹</button><strong>Page {pageNumber} / {pageCount}</strong><button disabled={pageNumber>=pageCount} onClick={()=>setPageNumber(p=>p+1)}>›</button><span style={{marginLeft:16}}>Highlight:</span><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} style={{height:38}}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><div style={{marginLeft:'auto',display:'flex',gap:8}}><button onClick={()=>zoomAt(view.zoom/1.15)}>−</button><strong style={{minWidth:54,textAlign:'center'}}>{Math.round(view.zoom*100)}%</strong><button onClick={()=>zoomAt(view.zoom*1.15)}>＋</button><button onClick={()=>applySavedOrFit(baseSize,null)}>Fit</button><button onClick={save} disabled={saving||!documentId} style={{background:'#078f88',color:'#fff',border:0,borderRadius:8,padding:'10px 18px',fontWeight:900}}>{saving?'Saving…':'Save Card View'}</button></div></div>
      {error?<div style={{padding:10,background:'#fff0f0',color:'#a11',marginBottom:10}}>{error}</div>:message?<div style={{padding:10,background:'#eaf8f5',color:'#075e58',marginBottom:10}}>{message}</div>:null}
      <div style={{display:'grid',gridTemplateColumns:'minmax(340px,1fr) minmax(520px,1fr)',gap:18,alignItems:'start'}}>
        <section style={{background:'#dfe7eb',borderRadius:14,padding:18,border:'1px solid #cad7dd'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.08em',marginBottom:10}}>LIVE LOCATION REPORT</div><div style={{position:'relative',width:'100%',aspectRatio:'210 / 297',background:'#fff',overflow:'hidden',boxShadow:'0 12px 35px rgba(5,42,60,.18)'}}><img src="/location-a4-picture.png" alt="" style={{position:'absolute',inset:0,width:'100%',height:'100%'}}/><div style={{position:'absolute',left:'50.55%',top:'32.06%',width:'44.91%',height:'28.43%',boxSizing:'border-box',overflow:'hidden',background:'rgba(255,0,0,.10)',outline:'4px dashed #ff1744',outlineOffset:'-4px',display:'flex',alignItems:'center',justifyContent:'center',zIndex:3}}>{drawingUrl&&previewDrawingStyle?<div style={{...previewDrawingStyle,aspectRatio:'1 / 1'}}><img src={drawingUrl} alt="" style={{position:'absolute',inset:0,width:'100%',height:'100%'}}/><svg viewBox="0 0 1 1" preserveAspectRatio="none" style={{position:'absolute',inset:0,width:'100%',height:'100%',pointerEvents:'none'}}>{points.length>=3?<polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={color} fillOpacity={clamp(opacity,.2,.65)} stroke={color} strokeWidth=".004" vectorEffect="non-scaling-stroke"/>:null}</svg></div>:null}</div></div><p style={{fontSize:12,color:'#56727f',margin:'10px 0 0'}}>Red dashed box = RitsuFlow Location On Plan viewport. This test keeps the same top and width and reduces only the height by 5 mm.</p></section>
        <section style={{background:'#dfe7eb',padding:18,borderRadius:14,border:'1px solid #cad7dd'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.08em',marginBottom:10}}>ADJUST CARD VIEW</div><div ref={frameRef} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} style={{position:'relative',width:'100%',aspectRatio:String(ASPECT),overflow:'hidden',background:'#fff',border:'4px solid #00a39b',boxShadow:'0 12px 35px rgba(5,42,60,.22)',cursor:'grab',touchAction:'none'}}><div style={{...drawingStyle,position:'absolute'}}><canvas ref={canvasRef}/><svg viewBox="0 0 1 1" preserveAspectRatio="none" style={{position:'absolute',inset:0,width:'100%',height:'100%',pointerEvents:'none'}}>{points.length>=3?<polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={color} fillOpacity={clamp(opacity,.2,.65)} stroke={color} strokeWidth=".004" vectorEffect="non-scaling-stroke"/>:null}</svg></div>{loading?<div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',background:'rgba(255,255,255,.75)',fontWeight:800}}>Loading drawing…</div>:null}<div style={{position:'absolute',left:12,top:10,background:'#063247',color:'#fff',padding:'6px 9px',borderRadius:6,fontSize:11,fontWeight:900}}>LOCATION CARD VIEW</div></div><p style={{textAlign:'center',fontSize:13,color:'#56727f',marginBottom:0}}>Drag the drawing to position it. Use + / − to zoom. The left report preview shows the live result. {savedView?'A Card View is already saved for this page.':''}</p></section>
      </div>
    </section>
  </main>
}
