'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { createClient } from '../../../lib/supabase/client'
import { extractPdfVectorSnap, nearestVectorSnap } from './pdfVectorSnap'
import styles from './location-map-workspace.module.css'

const COLORS=['#008F84','#2F80ED','#8E5BEF','#E58A1F','#D94F70','#2E8B57','#6B7280']
const SNAP_RADIUS_PX=20,CLOSE_RADIUS_PX=16,MIN_ZOOM=.20,MAX_ZOOM=8,MAX_RENDER_PIXELS=28000000,RENDER_DEBOUNCE_MS=180
const isPdf=d=>d?.mime_type==='application/pdf'||d?.document_type==='PDF'||d?.file_name?.toLowerCase().endsWith('.pdf')
const pointsOf=g=>Array.isArray(g?.points)?g.points:[]
const colorOf=g=>g?.display?.color||'#008F84'
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v))

export default function LocationMapWorkspace({projectId,userId,locations=[]}){
  const supabase=useMemo(()=>createClient(),[])
  const canvasRef=useRef(null),stageRef=useRef(null),pdfRef=useRef(null),renderTaskRef=useRef(null),panRef=useRef(null),renderTimerRef=useRef(null),basePdfScaleRef=useRef(1),renderGenerationRef=useRef(0)
  const [documents,setDocuments]=useState([]),[documentId,setDocumentId]=useState(''),[pageNumber,setPageNumber]=useState(1),[pageCount,setPageCount]=useState(1)
  const [mapId,setMapId]=useState(''),[geometries,setGeometries]=useState([]),[selectedId,setSelectedId]=useState(locations[0]?.id||'')
  const [draft,setDraft]=useState([]),[drawing,setDrawing]=useState(false),[tool,setTool]=useState('polygon'),[anchor,setAnchor]=useState(null),[previewPoint,setPreviewPoint]=useState(null),[color,setColor]=useState(COLORS[0])
  const [snapEnabled,setSnapEnabled]=useState(true),[snapPoint,setSnapPoint]=useState(null),[vectorSnap,setVectorSnap]=useState(null),[snapStatus,setSnapStatus]=useState('loading')
  const [viewport,setViewport]=useState({x:0,y:0,zoom:1}),[baseSize,setBaseSize]=useState({width:0,height:0}),[panning,setPanning]=useState(false),[renderQuality,setRenderQuality]=useState(1)
  const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const locationMap=useMemo(()=>new Map(locations.map(x=>[x.id,x])),[locations]),mapped=useMemo(()=>new Map(geometries.map(x=>[x.location_id,x])),[geometries]),selected=locationMap.get(selectedId)||null

  useEffect(()=>{loadDocuments()},[projectId])
  useEffect(()=>{if(documentId)loadPdfAndMap();else{pdfRef.current=null;setGeometries([]);setMapId('');setVectorSnap(null);setSnapStatus('unavailable')}},[documentId,pageNumber])
  useEffect(()=>{const row=mapped.get(selectedId);setColor(colorOf(row?.geometry));resetDrawing()},[selectedId,geometries])
  useEffect(()=>{const shell=stageRef.current;if(!shell)return;const onWheel=e=>{if(!documentId)return;e.preventDefault();e.stopPropagation();const factor=Math.exp(-e.deltaY*.0015);applyZoom(viewport.zoom*factor,e.clientX,e.clientY)};shell.addEventListener('wheel',onWheel,{passive:false});return()=>shell.removeEventListener('wheel',onWheel)},[documentId,viewport])
  useEffect(()=>{if(!documentId||!pdfRef.current||!baseSize.width)return;clearTimeout(renderTimerRef.current);renderTimerRef.current=setTimeout(()=>rerenderForZoom(viewport.zoom),RENDER_DEBOUNCE_MS);return()=>clearTimeout(renderTimerRef.current)},[viewport.zoom,documentId,pageNumber,baseSize.width])

  function resetDrawing(){setDraft([]);setDrawing(false);setAnchor(null);setPreviewPoint(null);setSnapPoint(null)}
  async function loadDocuments(){const {data,error:e}=await supabase.from('project_documents').select('id,file_name,storage_path,mime_type,document_type,created_at').eq('project_id',projectId).order('created_at',{ascending:false});if(e){setError(e.message);return}const pdfs=(data||[]).filter(isPdf);setDocuments(pdfs);setDocumentId(v=>v||pdfs[0]?.id||'')}
  async function loadPdfAndMap(){const doc=documents.find(x=>x.id===documentId);if(!doc)return;setLoading(true);setError('');setMessage('');setSnapPoint(null);setVectorSnap(null);setSnapStatus('loading');setRenderQuality(1);try{const {data:signed,error:se}=await supabase.storage.from('project-documents').createSignedUrl(doc.storage_path,120);if(se||!signed?.signedUrl)throw new Error(se?.message||'Unable to access this PDF.');const response=await fetch(signed.signedUrl);if(!response.ok)throw new Error(`Unable to download PDF (${response.status}).`);const bytes=await response.arrayBuffer(),pdfjs=await import('pdfjs-dist/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';if(pdfRef.current?.destroy)await pdfRef.current.destroy().catch(()=>{});pdfRef.current=await pdfjs.getDocument({data:bytes}).promise;setPageCount(pdfRef.current.numPages);const safePage=Math.min(Math.max(1,pageNumber),pdfRef.current.numPages);if(safePage!==pageNumber){setPageNumber(safePage);return}const size=await renderPage(safePage,pdfjs);requestAnimationFrame(()=>fitDrawing(size));const {data:dm,error:me}=await supabase.from('project_drawing_maps').select('id').eq('project_id',projectId).eq('document_id',documentId).eq('page_number',safePage).maybeSingle();if(me)throw me;setMapId(dm?.id||'');if(dm?.id){const {data:g,error:ge}=await supabase.from('project_drawing_location_geometries').select('id,location_id,geometry,geometry_type,page_number').eq('drawing_map_id',dm.id).eq('page_number',safePage);if(ge)throw ge;setGeometries(g||[])}else setGeometries([])}catch(e){setError(e?.message||'The drawing could not be loaded.');setSnapStatus('unavailable')}finally{setLoading(false)}}
  async function renderPage(pageNo,pdfjs){const canvas=canvasRef.current;if(!canvas||!pdfRef.current)return null;const page=await pdfRef.current.getPage(pageNo),base=page.getViewport({scale:1}),renderWidth=Math.max(900,Math.min(1500,base.width*1.7)),scale=renderWidth/base.width,pageViewport=page.getViewport({scale}),dpr=Math.min(window.devicePixelRatio||1,2);basePdfScaleRef.current=scale;canvas.width=Math.round(pageViewport.width*dpr);canvas.height=Math.round(pageViewport.height*dpr);canvas.style.width=`${pageViewport.width}px`;canvas.style.height=`${pageViewport.height}px`;const size={width:pageViewport.width,height:pageViewport.height};setBaseSize(size);renderTaskRef.current?.cancel?.();const task=page.render({canvasContext:canvas.getContext('2d'),viewport:pageViewport,transform:dpr===1?null:[dpr,0,0,dpr,0,0]});renderTaskRef.current=task;try{await task.promise}catch(e){if(e?.name!=='RenderingCancelledException')throw e}try{const geometry=await extractPdfVectorSnap(page,pageViewport,pdfjs);setVectorSnap(geometry);setSnapStatus(geometry.endpoints.length||geometry.segments.length?'vector':'unavailable')}catch{setVectorSnap(null);setSnapStatus('unavailable')}return size}
  async function rerenderForZoom(zoom){const canvas=canvasRef.current,pdf=pdfRef.current;if(!canvas||!pdf||!baseSize.width||!baseSize.height)return;const generation=++renderGenerationRef.current;try{const page=await pdf.getPage(pageNumber);if(generation!==renderGenerationRef.current)return;const desiredQuality=clamp(Math.max(1,zoom),1,8),dpr=Math.min(window.devicePixelRatio||1,2);let quality=desiredQuality;const desiredPixels=baseSize.width*baseSize.height*quality*quality*dpr*dpr;if(desiredPixels>MAX_RENDER_PIXELS)quality*=Math.sqrt(MAX_RENDER_PIXELS/desiredPixels);quality=Math.max(1,quality);if(Math.abs(quality-renderQuality)<.12)return;const renderViewport=page.getViewport({scale:basePdfScaleRef.current*quality}),pixelDpr=Math.min(dpr,Math.sqrt(MAX_RENDER_PIXELS/Math.max(1,renderViewport.width*renderViewport.height)));renderTaskRef.current?.cancel?.();canvas.width=Math.max(1,Math.round(renderViewport.width*pixelDpr));canvas.height=Math.max(1,Math.round(renderViewport.height*pixelDpr));canvas.style.width=`${baseSize.width}px`;canvas.style.height=`${baseSize.height}px`;const task=page.render({canvasContext:canvas.getContext('2d'),viewport:renderViewport,transform:pixelDpr===1?null:[pixelDpr,0,0,pixelDpr,0,0]});renderTaskRef.current=task;try{await task.promise;if(generation===renderGenerationRef.current)setRenderQuality(quality)}catch(e){if(e?.name!=='RenderingCancelledException')throw e}}catch(e){console.error('Location Map high-resolution PDF render failed.',e)}}
  async function ensureMap(){if(mapId)return mapId;const {data,error:e}=await supabase.from('project_drawing_maps').insert({project_id:projectId,document_id:documentId,page_number:pageNumber,drawing_type:'floor_plan',created_by:userId}).select('id').single();if(e){if(e.code==='23505'){const {data:existing,error:ee}=await supabase.from('project_drawing_maps').select('id').eq('document_id',documentId).eq('page_number',pageNumber).single();if(ee)throw ee;setMapId(existing.id);return existing.id}throw e}setMapId(data.id);return data.id}
  function screenSize(){return{width:Math.max(1,baseSize.width*viewport.zoom),height:Math.max(1,baseSize.height*viewport.zoom)}}
  function rawPointerPoint(e){const shell=stageRef.current;if(!shell||!baseSize.width||!baseSize.height)return{x:0,y:0};const rect=shell.getBoundingClientRect(),screenX=e.clientX-rect.left,screenY=e.clientY-rect.top,drawingX=(screenX-viewport.x)/viewport.zoom,drawingY=(screenY-viewport.y)/viewport.zoom;return{x:clamp(drawingX/baseSize.width,0,1),y:clamp(drawingY/baseSize.height,0,1)}}
  function distancePx(a,b,size){return Math.hypot((a.x-b.x)*size.width,(a.y-b.y)*size.height)}
  function findDrawingSnap(e){const raw=rawPointerPoint(e),size=screenSize();if(!snapEnabled)return{point:raw,type:'free'};if(tool!=='rectangle'&&draft.length>=3&&distancePx(raw,draft[0],size)<=CLOSE_RADIUS_PX)return{point:draft[0],type:'close',distancePx:distancePx(raw,draft[0],size)};if(snapStatus!=='vector'||!vectorSnap)return{point:raw,type:'free'};return nearestVectorSnap(raw,vectorSnap,size,SNAP_RADIUS_PX)||{point:raw,type:'free'}}
  function rectanglePoints(a,b){return[{x:a.x,y:a.y},{x:b.x,y:a.y},{x:b.x,y:b.y},{x:a.x,y:b.y}]}
  function handlePointerMove(e){const pan=panRef.current;if(pan){const dx=e.clientX-pan.x,dy=e.clientY-pan.y;setViewport(v=>({...v,x:pan.originX+dx,y:pan.originY+dy}));return}if(!drawing){if(snapPoint)setSnapPoint(null);return}const snap=findDrawingSnap(e);setSnapPoint({...snap.point,type:snap.type,distancePx:snap.distancePx});setPreviewPoint(snap.point)}
  function handlePointerLeave(){if(drawing&&!panRef.current){setSnapPoint(null);setPreviewPoint(null)}}
  function beginPan(e){const middle=e.button===1,leftPan=e.button===0&&!drawing;if(!middle&&!leftPan)return;e.preventDefault();e.stopPropagation();panRef.current={x:e.clientX,y:e.clientY,originX:viewport.x,originY:viewport.y};setPanning(true);e.currentTarget.setPointerCapture?.(e.pointerId)}
  function endPan(e){if(!panRef.current)return;panRef.current=null;setPanning(false);e.currentTarget.releasePointerCapture?.(e.pointerId)}
  function addPoint(e){if(panRef.current||e.button!==0||!drawing||!selectedId)return;const snap=findDrawingSnap(e),point={x:Number(snap.point.x.toFixed(6)),y:Number(snap.point.y.toFixed(6))};if(tool==='rectangle'){if(!anchor){setAnchor(point);setDraft([point]);setMessage('Rectangle: select the opposite corner.');return}setDraft(rectanglePoints(anchor,point));setAnchor(null);setPreviewPoint(null);setDrawing(false);setSnapPoint(null);setMessage('Rectangle ready. Save the mapping to keep it.');return}if(snap.type==='close'&&draft.length>=3){setDrawing(false);setPreviewPoint(null);setSnapPoint(null);setMessage('Perimeter closed. Save the mapping to keep it.');return}setDraft(v=>[...v,point])}
  function applyZoom(nextZoom,clientX,clientY){const shell=stageRef.current;if(!shell)return;const next=clamp(nextZoom,MIN_ZOOM,MAX_ZOOM);if(Math.abs(next-viewport.zoom)<.001)return;const rect=shell.getBoundingClientRect(),px=(clientX??rect.left+rect.width/2)-rect.left,py=(clientY??rect.top+rect.height/2)-rect.top,worldX=(px-viewport.x)/viewport.zoom,worldY=(py-viewport.y)/viewport.zoom;setViewport({zoom:next,x:px-worldX*next,y:py-worldY*next})}
  function fitDrawing(sizeOverride){const shell=stageRef.current,size=sizeOverride||baseSize;if(!shell||!size?.width||!size?.height)return;const pad=36,availableW=Math.max(100,shell.clientWidth-pad*2),availableH=Math.max(100,shell.clientHeight-pad*2),next=clamp(Math.min(availableW/size.width,availableH/size.height),MIN_ZOOM,1.5);setViewport({zoom:next,x:(shell.clientWidth-size.width*next)/2,y:(shell.clientHeight-size.height*next)/2})}
  function startTool(nextTool){if(!selectedId)return;setTool(nextTool);setDraft([]);setAnchor(null);setPreviewPoint(null);setDrawing(true);setSnapPoint(null);const label=nextTool==='rectangle'?'Rectangle':nextTool==='line'?'Line':'Polygon';setMessage(`${label}: draw the perimeter for ${selected?.name||'this location'}. Middle-drag pans while drawing.`)}
  function closePerimeter(){if(draft.length<3){setMessage('Add at least three perimeter points before closing.');return}setDrawing(false);setPreviewPoint(null);setSnapPoint(null);setMessage('Perimeter ready. Save the mapping to keep it.')}
  function undoPoint(){setDraft(v=>v.slice(0,-1));if(tool==='rectangle'){setAnchor(null);setPreviewPoint(null)}}
  async function saveMapping(){const points=draft.length>=3?draft:pointsOf(mapped.get(selectedId)?.geometry);if(!selectedId||points.length<3)return;setSaving(true);setError('');try{const drawingMapId=await ensureMap(),geometry={points,coordinate_space:'normalized',source_tool:tool,display:{color,fill_opacity:.12}},existing=mapped.get(selectedId),payload={project_id:projectId,drawing_map_id:drawingMapId,document_id:documentId,location_id:selectedId,page_number:pageNumber,geometry_type:'polygon',geometry},query=existing?supabase.from('project_drawing_location_geometries').update(payload).eq('id',existing.id):supabase.from('project_drawing_location_geometries').insert({...payload,created_by:userId});const {error:e}=await query;if(e)throw e;resetDrawing();setMessage(`${selected?.name||'Location'} mapping saved.`);await loadPdfAndMap()}catch(e){setError(e?.message||'Unable to save the location mapping.')}finally{setSaving(false)}}
  async function removeMapping(){const row=mapped.get(selectedId);if(!row)return;if(!window.confirm(`Remove the saved perimeter for ${selected?.name}?`))return;const{error:e}=await supabase.from('project_drawing_location_geometries').delete().eq('id',row.id);if(e){setError(e.message);return}setMessage('Mapping removed.');await loadPdfAndMap()}
  async function uploadPdf(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){setError('Location Map accepts PDF drawings only.');return}if(file.size>50*1024*1024){setError('PDF must be 50 MB or smaller.');return}setUploading(true);setError('');try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${projectId}/${Date.now()}-${safe}`,{error:ue}=await supabase.storage.from('project-documents').upload(path,file,{contentType:'application/pdf',upsert:false});if(ue)throw ue;const{data,error:de}=await supabase.from('project_documents').insert({project_id:projectId,file_name:file.name,storage_path:path,mime_type:'application/pdf',file_size:file.size,document_type:'PDF',uploaded_by:userId}).select('id,file_name,storage_path,mime_type,document_type,created_at').single();if(de){await supabase.storage.from('project-documents').remove([path]);throw de}setDocuments(v=>[data,...v]);setDocumentId(data.id);setPageNumber(1);setMessage('PDF uploaded. Select a location and draw its perimeter.')}catch(err){setError(err?.message||'Unable to upload the PDF.')}finally{setUploading(false)}}

  const displayRows=geometries.filter(g=>pointsOf(g.geometry).length>=3),savedPoints=pointsOf(mapped.get(selectedId)?.geometry),activePoints=draft.length?draft:savedPoints,drawingStyle=baseSize.width?{width:baseSize.width,height:baseSize.height,transform:`translate3d(${viewport.x}px,${viewport.y}px,0) scale(${viewport.zoom})`}:undefined
  const snapLabel=!snapEnabled?'Snap OFF':snapStatus==='vector'?`Snap ON · ${vectorSnap?.segmentCount||0} seg`:snapStatus==='loading'?'Snap…':'Free Draw',snapDetail=snapStatus==='vector'?`${vectorSnap?.segmentCount||0} segments · ${vectorSnap?.endpointCount||0} endpoints · ${vectorSnap?.intersectionCount||0} intersections`:''
  const rectanglePreview=tool==='rectangle'&&drawing&&anchor&&previewPoint?rectanglePoints(anchor,previewPoint):null,linePreview=tool!=='rectangle'&&drawing&&draft.length&&previewPoint?[draft[draft.length-1],previewPoint]:null
  return <section className={styles.workspace}>
    <aside className={styles.sidebar}><div className={styles.sideHeader}><span>LOCATION MAP</span><strong>Spatial identity</strong><small>{mapped.size} of {locations.length} locations mapped on this page</small></div><div className={styles.locationList}>{locations.map(loc=><button key={loc.id} type="button" className={`${styles.locationRow} ${selectedId===loc.id?styles.locationActive:''}`} onClick={()=>setSelectedId(loc.id)}><span>{mapped.has(loc.id)?'●':'○'}</span><strong>{loc.name}</strong><small>{loc.location_type}</small></button>)}</div></aside>
    <div className={styles.mapPanel}>
      <div className={styles.mapToolbar}><select value={documentId} onChange={e=>{setDocumentId(e.target.value);setPageNumber(1)}}><option value="">Select PDF drawing…</option>{documents.map(doc=><option key={doc.id} value={doc.id}>{doc.file_name}</option>)}</select><label className={styles.uploadButton}>＋ {uploading?'Uploading…':'Upload PDF'}<input type="file" accept="application/pdf,.pdf" onChange={uploadPdf} disabled={uploading}/></label><button type="button" disabled={!documentId||pageNumber<=1} onClick={()=>setPageNumber(p=>p-1)}>‹</button><span className={styles.pageLabel}>Page {pageNumber} / {pageCount}</span><button type="button" disabled={!documentId||pageNumber>=pageCount} onClick={()=>setPageNumber(p=>p+1)}>›</button><div className={styles.spacer}/><div className={styles.zoomGroup}><button type="button" disabled={!documentId} onClick={()=>applyZoom(viewport.zoom/1.2)}>−</button><span title={`PDF render quality ${renderQuality.toFixed(1)}×`}>{Math.round(viewport.zoom*100)}%</span><button type="button" disabled={!documentId} onClick={()=>applyZoom(viewport.zoom*1.2)}>＋</button><button type="button" disabled={!documentId} onClick={()=>fitDrawing()}>Fit</button></div><button type="button" title={snapStatus==='unavailable'?'This PDF page has no usable vector paths. Free Draw remains available.':snapDetail||'Snap to PDF vector geometry.'} className={snapEnabled&&snapStatus==='vector'?styles.snapOn:styles.snapOff} onClick={()=>{setSnapEnabled(v=>!v);setSnapPoint(null)}}>{snapLabel}</button><button type="button" className={tool==='line'&&drawing?styles.drawButton:''} disabled={!documentId||!selectedId} onClick={()=>startTool('line')}>Line</button><button type="button" className={tool==='rectangle'&&drawing?styles.drawButton:''} disabled={!documentId||!selectedId} onClick={()=>startTool('rectangle')}>Rectangle</button><button type="button" className={tool==='polygon'&&drawing?styles.drawButton:''} disabled={!documentId||!selectedId} onClick={()=>startTool('polygon')}>Polygon</button><button type="button" disabled={!drawing||!draft.length} onClick={undoPoint}>Undo</button><button type="button" disabled={!drawing||tool==='rectangle'||draft.length<3} onClick={closePerimeter}>Close</button></div>
      <div className={styles.actionBar}><div><strong>{selected?.name||'Select a location'}</strong><span>{drawing?`${tool[0].toUpperCase()+tool.slice(1)} perimeter · ${snapLabel}${snapPoint?.type&&snapPoint.type!=='free'?` · ${snapPoint.type.toUpperCase()}`:''} · middle-drag to pan`:mapped.has(selectedId)?'Mapped on this page · selected location highlighted':'Not mapped on this page · drag anywhere to pan'}</span></div><div className={styles.colors}>{COLORS.map(c=><button key={c} type="button" aria-label={`Use ${c}`} className={color===c?styles.colorActive:''} style={{background:c}} onClick={()=>setColor(c)}/>)}</div><button type="button" className={styles.deleteButton} disabled={!mapped.has(selectedId)} onClick={removeMapping}>Remove</button><button type="button" className={styles.saveButton} disabled={saving||(!draft.length&&!mapped.has(selectedId))} onClick={saveMapping}>{saving?'Saving…':'Save Mapping'}</button></div>
      {error?<div className={styles.error}>{error}</div>:message?<div className={styles.message}>{message}</div>:null}
      <div className={`${styles.stageShell} ${panning?styles.panning:''}`} ref={stageRef} onPointerDown={beginPan} onPointerMove={handlePointerMove} onPointerUp={endPan} onPointerCancel={endPan} onPointerLeave={handlePointerLeave} onAuxClick={e=>e.preventDefault()}>{!documentId?<div className={styles.empty}><strong>Select or upload a project PDF</strong><span>The drawing stays untouched. Location perimeters are stored as a separate spatial overlay.</span></div>:<div style={drawingStyle} className={`${styles.drawingStage} ${drawing?styles.drawingMode:styles.panMode}`} onClick={addPoint}><canvas ref={canvasRef}/><svg className={styles.overlay} viewBox="0 0 1 1" preserveAspectRatio="none">
        {displayRows.filter(g=>g.location_id!==selectedId).map(g=><polygon key={g.id} points={pointsOf(g.geometry).map(p=>`${p.x},${p.y}`).join(' ')} fill={colorOf(g.geometry)} fillOpacity=".10" stroke={colorOf(g.geometry)} strokeOpacity=".65" strokeWidth=".002" vectorEffect="non-scaling-stroke"/>)}
        {activePoints.length>=2?<polyline points={activePoints.map(p=>`${p.x},${p.y}`).join(' ')} fill={activePoints.length>=3&&!drawing?color:'none'} fillOpacity={activePoints.length>=3&&!drawing?'1':'0'} stroke={color} strokeWidth=".004" vectorEffect="non-scaling-stroke"/>:null}
        {rectanglePreview?<polygon points={rectanglePreview.map(p=>`${p.x},${p.y}`).join(' ')} fill={color} fillOpacity=".12" stroke={color} strokeWidth=".0025" strokeDasharray=".008 .005" vectorEffect="non-scaling-stroke"/>:null}{linePreview?<line x1={linePreview[0].x} y1={linePreview[0].y} x2={linePreview[1].x} y2={linePreview[1].y} stroke={color} strokeWidth=".0025" strokeDasharray=".008 .005" vectorEffect="non-scaling-stroke"/>:null}{draft.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r=".006" fill="#fff" stroke={color} strokeWidth=".002" vectorEffect="non-scaling-stroke"/>)}{drawing&&snapPoint?<g className={styles.snapMarker}><circle cx={snapPoint.x} cy={snapPoint.y} r={snapPoint.type==='close'?'.011':'.008'} fill="none" stroke={snapPoint.type==='free'?'#8798A3':'#FF7A00'} strokeWidth=".0025" vectorEffect="non-scaling-stroke"/><line x1={snapPoint.x-.012} y1={snapPoint.y} x2={snapPoint.x+.012} y2={snapPoint.y} stroke={snapPoint.type==='free'?'#8798A3':'#FF7A00'} strokeWidth=".0015" vectorEffect="non-scaling-stroke"/><line x1={snapPoint.x} y1={snapPoint.y-.012} x2={snapPoint.x} y2={snapPoint.y+.012} stroke={snapPoint.type==='free'?'#8798A3':'#FF7A00'} strokeWidth=".0015" vectorEffect="non-scaling-stroke"/></g>:null}
      </svg>{loading?<div className={styles.loading}>Loading drawing…</div>:null}</div>}</div>
    </div>
  </section>
}
