'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { supabase } from '../../../../lib/supabase'

function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function workerName(w){return w?[w.first_name,w.middle_name,w.last_name].filter(Boolean).join(' ')||w.field_id||'—':'—'}
function label(v){return v?v.charAt(0).toUpperCase()+v.slice(1).toLowerCase():'—'}
const blankManual={worker_name:'',company:'',trade:'',role:'',crew:'',field_id:'',start_date:'',end_date:'',notes:'',status:'active'}
const blankAssignment=()=>({workerId:'',companyId:'',tradeId:'',roleId:'',crewId:'',startDate:today(),endDate:'',status:'active'})

export default function FieldOpWorkforceSetup({projectId,onCountChange}){
 const [project,setProject]=useState(null),[assignments,setAssignments]=useState([]),[manualWorkers,setManualWorkers]=useState([]),[workers,setWorkers]=useState([]),[companies,setCompanies]=useState([]),[trades,setTrades]=useState([]),[roles,setRoles]=useState([]),[crews,setCrews]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const [manualOpen,setManualOpen]=useState(false),[manual,setManual]=useState(blankManual),[manualEditingId,setManualEditingId]=useState(null)
 const [assignmentOpen,setAssignmentOpen]=useState(false),[assignment,setAssignment]=useState(blankAssignment),[assignmentEditingId,setAssignmentEditingId]=useState(null),[formError,setFormError]=useState('')

 async function loadWorkforce(){if(!projectId)return;setLoading(true);setError('');try{const [p,a,m,w,c,t,r,cr]=await Promise.all([
  supabase.from('projects').select('id,organization_id,code,name').eq('id',projectId).maybeSingle(),
  supabase.from('field_project_assignments').select(`id,organization_id,project_id,worker_id,company_id,trade_id,role_id,crew_id,start_date,end_date,status,field_workers:worker_id(id,field_id,first_name,middle_name,last_name,status),field_companies:company_id(id,name),field_trades:trade_id(id,name),field_roles:role_id(id,name),field_crews:crew_id(id,name)`).eq('project_id',projectId).in('status',['active','scheduled']).order('start_date',{ascending:true}),
  supabase.from('fieldop_manual_workers').select('*').eq('project_id',projectId).in('status',['active','scheduled']).order('created_at',{ascending:true}),
  supabase.from('field_workers').select('id,organization_id,field_id,first_name,middle_name,last_name,default_company_id,default_trade_id,default_role_id,status').eq('status','active').order('field_id'),
  supabase.from('field_companies').select('id,organization_id,name,status').eq('status','active').order('name'),
  supabase.from('field_trades').select('id,organization_id,name,status').eq('status','active').order('name'),
  supabase.from('field_roles').select('id,organization_id,name,status').eq('status','active').order('name'),
  supabase.from('field_crews').select('id,organization_id,company_id,name,status').eq('status','active').order('name')]);
  const first=[p,a,m,w,c,t,r,cr].find(x=>x.error);if(first?.error)throw first.error;setProject(p.data||null);setAssignments(a.data||[]);setManualWorkers(m.data||[]);setWorkers(w.data||[]);setCompanies(c.data||[]);setTrades(t.data||[]);setRoles(r.data||[]);setCrews(cr.data||[]);const active=(a.data||[]).filter(x=>x.status==='active').length+(m.data||[]).filter(x=>x.status==='active').length;onCountChange?.(active)
 }catch(err){setError(err?.message||String(err));onCountChange?.(0)}finally{setLoading(false)}}
 useEffect(()=>{loadWorkforce()},[projectId])
 const counts=useMemo(()=>{const all=[...assignments,...manualWorkers],crewNames=[...assignments.map(x=>x.field_crews?.name),...manualWorkers.map(x=>x.crew)].filter(Boolean);return{active:all.filter(x=>x.status==='active').length,scheduled:all.filter(x=>x.status==='scheduled').length,crews:new Set(crewNames).size}},[assignments,manualWorkers])
 const availableWorkers=useMemo(()=>{const used=new Set(assignments.filter(x=>x.id!==assignmentEditingId).map(x=>x.worker_id));return workers.filter(w=>(!project?.organization_id||w.organization_id===project.organization_id)&&!used.has(w.id))},[workers,assignments,assignmentEditingId,project])
 const availableCompanies=useMemo(()=>companies.filter(x=>!project?.organization_id||x.organization_id===project.organization_id),[companies,project]),availableTrades=useMemo(()=>trades.filter(x=>!project?.organization_id||x.organization_id===project.organization_id),[trades,project]),availableRoles=useMemo(()=>roles.filter(x=>!project?.organization_id||x.organization_id===project.organization_id),[roles,project]),availableCrews=useMemo(()=>crews.filter(x=>(!project?.organization_id||x.organization_id===project.organization_id)&&(!assignment.companyId||x.company_id===assignment.companyId)),[crews,project,assignment.companyId])

 function openAssign(){setAssignmentEditingId(null);setAssignment(blankAssignment());setFormError('');setAssignmentOpen(true)}
 function openAssignmentEdit(item){setAssignmentEditingId(item.id);setAssignment({workerId:item.worker_id||'',companyId:item.company_id||'',tradeId:item.trade_id||'',roleId:item.role_id||'',crewId:item.crew_id||'',startDate:item.start_date||today(),endDate:item.end_date||'',status:item.status||'active'});setFormError('');setAssignmentOpen(true)}
 function closeAssignment(){if(saving)return;setAssignmentOpen(false);setAssignmentEditingId(null);setAssignment(blankAssignment());setFormError('')}
 function changeAssignment(name,value){if(name==='workerId'){const w=workers.find(x=>x.id===value);setAssignment(x=>({...x,workerId:value,companyId:w?.default_company_id||'',tradeId:w?.default_trade_id||'',roleId:w?.default_role_id||'',crewId:''}));return}if(name==='companyId'){setAssignment(x=>({...x,companyId:value,crewId:''}));return}setAssignment(x=>({...x,[name]:value}))}
 async function saveAssignment(e){e.preventDefault();setFormError('');if(!assignment.workerId)return setFormError('Worker is required.');if(!assignment.companyId)return setFormError('Company is required.');if(!assignment.startDate)return setFormError('Start Date is required.');if(assignment.endDate&&assignment.endDate<assignment.startDate)return setFormError('End Date cannot be earlier than Start Date.');const w=workers.find(x=>x.id===assignment.workerId);if(!project?.organization_id||!w)return setFormError('Unable to determine the Project or Worker organization.');if(w.organization_id!==project.organization_id)return setFormError('Worker and Project must belong to the same organization.');const duplicate=assignments.find(x=>x.id!==assignmentEditingId&&x.worker_id===assignment.workerId&&['active','scheduled'].includes(x.status));if(duplicate)return setFormError('This worker already has an active or scheduled assignment for this project.');setSaving(true);try{const payload={organization_id:project.organization_id,project_id:projectId,worker_id:assignment.workerId,company_id:assignment.companyId,trade_id:assignment.tradeId||null,role_id:assignment.roleId||null,crew_id:assignment.crewId||null,start_date:assignment.startDate,end_date:assignment.endDate||null,status:assignment.status};const result=assignmentEditingId?await supabase.from('field_project_assignments').update(payload).eq('id',assignmentEditingId).eq('project_id',projectId):await supabase.from('field_project_assignments').insert(payload);if(result.error)throw result.error;closeAssignment();await loadWorkforce()}catch(err){setFormError(err?.message||'Unable to save project assignment.')}finally{setSaving(false)}}
 async function endAssignment(item){if(!window.confirm(`End ${workerName(item.field_workers)}'s assignment to this project? Attendance history will be preserved.`))return;setError('');const {error:e}=await supabase.from('field_project_assignments').update({status:'ended',end_date:item.end_date||today()}).eq('id',item.id).eq('project_id',projectId);if(e)setError(e.message);else loadWorkforce()}

 function openManual(){setManualEditingId(null);setManual(blankManual);setManualOpen(true)}
 function editManual(item){setManualEditingId(item.id);setManual({worker_name:item.worker_name||'',company:item.company||'',trade:item.trade||'',role:item.role||'',crew:item.crew||'',field_id:item.field_id||'',start_date:item.start_date||'',end_date:item.end_date||'',notes:item.notes||'',status:item.status||'active'});setManualOpen(true)}
 function closeManual(){if(saving)return;setManualOpen(false);setManualEditingId(null);setManual(blankManual)}
 async function saveManual(e){e.preventDefault();if(!manual.worker_name.trim()||saving)return;setSaving(true);setError('');try{const payload={project_id:projectId,worker_name:manual.worker_name.trim(),company:manual.company.trim()||null,trade:manual.trade.trim()||null,role:manual.role.trim()||null,crew:manual.crew.trim()||null,field_id:manual.field_id.trim()||null,start_date:manual.start_date||null,end_date:manual.end_date||null,notes:manual.notes.trim()||null,status:manual.status,updated_at:new Date().toISOString()};const result=manualEditingId?await supabase.from('fieldop_manual_workers').update(payload).eq('id',manualEditingId).eq('project_id',projectId):await supabase.from('fieldop_manual_workers').insert(payload);if(result.error)throw result.error;closeManual();await loadWorkforce()}catch(err){setError(err?.message||String(err))}finally{setSaving(false)}}
 async function removeManual(id){if(!window.confirm('Remove this manual worker from this FieldOp project?'))return;const {error:e}=await supabase.from('fieldop_manual_workers').delete().eq('id',id).eq('project_id',projectId);if(e)setError(e.message);else loadWorkforce()}

 return <section style={panel}><div style={header}><div><h2 style={{margin:0,fontSize:17}}>Workforce</h2><p style={subtle}>Assign registered company workers to this project or add project-specific workers for FieldOp and Daily Reports.</p></div><div style={actions}><Link href="/workforce" style={button}>View Workforce Registry</Link><button type="button" style={button} onClick={openAssign}>+ Assign Registered Worker</button><button type="button" style={primary} onClick={openManual}>+ Add Manual Worker</button></div></div>
 <div style={metrics}><Metric label="Active Workers" value={counts.active}/><Metric label="Scheduled" value={counts.scheduled}/><Metric label="Crews" value={counts.crews}/></div>{error&&<div style={errorStyle}>{error}</div>}
 {loading?<div style={empty}>Loading project workforce...</div>:assignments.length+manualWorkers.length===0?<div style={empty}><strong>No workers are available to this project yet.</strong><span>Assign a registered worker or add someone manually.</span><div style={{display:'flex',gap:8,marginTop:8}}><button style={button} onClick={openAssign}>+ Assign Registered Worker</button><button style={primary} onClick={openManual}>+ Add Manual Worker</button></div></div>:<div style={tableWrap}><table style={table}><thead><tr style={thead}><th style={th}>Worker</th><th style={th}>Source</th><th style={th}>Company</th><th style={th}>Trade</th><th style={th}>Role</th><th style={th}>Crew</th><th style={th}>Status</th><th style={th}>Actions</th></tr></thead><tbody>
 {assignments.map(item=><tr key={`r-${item.id}`} style={tr}><td style={td}><strong>{workerName(item.field_workers)}</strong><small style={small}>{item.field_workers?.field_id||'—'}</small></td><td style={td}><Badge text="Registered" bg="#e3f2ff" color="#0872b9"/></td><td style={td}>{item.field_companies?.name||'—'}</td><td style={td}>{item.field_trades?.name||'—'}</td><td style={td}>{item.field_roles?.name||'—'}</td><td style={td}>{item.field_crews?.name||'—'}</td><td style={td}><Status value={item.status}/></td><td style={td}><div style={{display:'flex',gap:7}}><button style={edit} onClick={()=>openAssignmentEdit(item)}>Edit</button><button style={remove} onClick={()=>endAssignment(item)}>End Assignment</button></div></td></tr>)}
 {manualWorkers.map(item=><tr key={`m-${item.id}`} style={tr}><td style={td}><strong>{item.worker_name}</strong><small style={small}>{item.field_id||'No field ID'}</small></td><td style={td}><Badge text="Manual" bg="#f1e9ff" color="#7040b0"/></td><td style={td}>{item.company||'—'}</td><td style={td}>{item.trade||'—'}</td><td style={td}>{item.role||'—'}</td><td style={td}>{item.crew||'—'}</td><td style={td}><Status value={item.status}/></td><td style={td}><div style={{display:'flex',gap:7}}><button style={edit} onClick={()=>editManual(item)}>Edit</button><button style={remove} onClick={()=>removeManual(item.id)}>Remove</button></div></td></tr>)}</tbody></table></div>}
 {assignmentOpen&&<div style={backdrop}><form style={modal} onSubmit={saveAssignment}><header style={modalHeader}><div><h2 style={{margin:0}}>{assignmentEditingId?'Edit Registered Assignment':'Assign Registered Worker'}</h2><p style={subtle}>Project assignment keeps company, trade, role and crew context without creating another worker record.</p></div><button type="button" style={close} onClick={closeAssignment}>×</button></header>{formError&&<div style={{...errorStyle,margin:'16px 22px 0'}}>{formError}</div>}<div style={formGrid}><Select label="Worker" required value={assignment.workerId} disabled={Boolean(assignmentEditingId)} onChange={v=>changeAssignment('workerId',v)} options={availableWorkers.map(w=>({value:w.id,text:`${w.field_id||'—'} · ${workerName(w)}`}))} wide/><Select label="Company" required value={assignment.companyId} onChange={v=>changeAssignment('companyId',v)} options={availableCompanies.map(x=>({value:x.id,text:x.name}))}/><Select label="Trade" value={assignment.tradeId} onChange={v=>changeAssignment('tradeId',v)} options={availableTrades.map(x=>({value:x.id,text:x.name}))}/><Select label="Role" value={assignment.roleId} onChange={v=>changeAssignment('roleId',v)} options={availableRoles.map(x=>({value:x.id,text:x.name}))}/><Select label="Crew" value={assignment.crewId} onChange={v=>changeAssignment('crewId',v)} options={availableCrews.map(x=>({value:x.id,text:x.name}))}/><Field label="Start Date" type="date" required value={assignment.startDate} onChange={v=>changeAssignment('startDate',v)}/><Field label="End Date" type="date" value={assignment.endDate} onChange={v=>changeAssignment('endDate',v)}/><Select label="Status" value={assignment.status} onChange={v=>changeAssignment('status',v)} options={[{value:'active',text:'Active'},{value:'scheduled',text:'Scheduled'}]}/></div><footer style={modalFooter}><button type="button" style={button} onClick={closeAssignment}>Cancel</button><button style={primary} disabled={saving}>{saving?'Saving...':assignmentEditingId?'Save Assignment':'Assign Worker'}</button></footer></form></div>}
 {manualOpen&&<div style={backdrop}><form style={modal} onSubmit={saveManual}><header style={modalHeader}><div><h2 style={{margin:0}}>{manualEditingId?'Edit Manual Worker':'Add Manual Worker'}</h2><p style={subtle}>Add a project-specific worker without creating a canonical Workforce Registry record.</p></div><button type="button" style={close} onClick={closeManual}>×</button></header><div style={formGrid}><Field label="Worker Name" required value={manual.worker_name} onChange={v=>setManual({...manual,worker_name:v})} wide/><Field label="Company / Subcontractor" value={manual.company} onChange={v=>setManual({...manual,company:v})}/><Field label="Trade" value={manual.trade} onChange={v=>setManual({...manual,trade:v})}/><Field label="Role" value={manual.role} onChange={v=>setManual({...manual,role:v})}/><Field label="Crew" value={manual.crew} onChange={v=>setManual({...manual,crew:v})}/><Field label="Field ID / Badge" value={manual.field_id} onChange={v=>setManual({...manual,field_id:v})}/><Select label="Status" value={manual.status} onChange={v=>setManual({...manual,status:v})} options={[{value:'active',text:'Active'},{value:'scheduled',text:'Scheduled'}]}/><Field label="Start Date" type="date" value={manual.start_date} onChange={v=>setManual({...manual,start_date:v})}/><Field label="End Date" type="date" value={manual.end_date} onChange={v=>setManual({...manual,end_date:v})}/><label style={{...field,gridColumn:'1 / -1'}}>Notes<textarea style={{...input,minHeight:70,paddingTop:9}} value={manual.notes} onChange={e=>setManual({...manual,notes:e.target.value})}/></label></div><footer style={modalFooter}><button type="button" style={button} onClick={closeManual}>Cancel</button><button style={primary} disabled={saving}>{saving?'Saving...':manualEditingId?'Save Changes':'Add Worker'}</button></footer></form></div>}</section>
}
function Field({label:name,value,onChange,type='text',required=false,wide=false}){return <label style={{...field,...(wide?{gridColumn:'1 / -1'}:{})}}>{name}<input style={input} type={type} required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label:name,value,onChange,options,required=false,disabled=false,wide=false}){return <label style={{...field,...(wide?{gridColumn:'1 / -1'}:{})}}>{name}<select style={input} required={required} disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}><option value="">Select {name.toLowerCase()}</option>{options.map(o=><option key={o.value} value={o.value}>{o.text}</option>)}</select></label>}
function Metric({label:metricLabel,value}){return <div style={metric}><small>{metricLabel}</small><strong style={{display:'block',marginTop:3,fontSize:20}}>{value}</strong></div>}
function Badge({text,bg,color}){return <span style={{display:'inline-block',borderRadius:999,padding:'4px 8px',background:bg,color,fontWeight:700}}>{text}</span>}
function Status({value}){return <span style={{display:'inline-block',borderRadius:999,padding:'4px 8px',background:value==='active'?'#e6f8ef':'#fff5dc',color:value==='active'?'#147a50':'#9a6a00',fontWeight:700}}>{label(value)}</span>}
const panel={marginTop:12,minHeight:430,background:'#fff',border:'1px solid #d6e0e5',borderRadius:10,padding:17},header={display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16},subtle={margin:'5px 0',color:'#6b7e89'},actions={display:'flex',gap:8,flexWrap:'wrap',justifyContent:'flex-end'},button={minHeight:34,border:'1px solid #cbd9df',borderRadius:7,background:'#fff',padding:'0 11px',color:'#36586b',textDecoration:'none',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:700,fontSize:13,cursor:'pointer'},primary={...button,borderColor:'#0aa695',background:'#0aa695',color:'#fff'},metrics={display:'grid',gridTemplateColumns:'repeat(3,minmax(130px,1fr))',gap:10,marginTop:18,maxWidth:560},metric={border:'1px solid #dfe7eb',borderRadius:8,padding:'11px 13px',background:'#fafcfd',color:'#17384a'},errorStyle={marginTop:18,border:'1px solid #f0c6c6',background:'#fff4f4',color:'#a43c3c',padding:'10px 12px',borderRadius:7},empty={minHeight:260,display:'grid',placeContent:'center',justifyItems:'center',textAlign:'center',gap:7,color:'#748590'},tableWrap={marginTop:18,border:'1px solid #dfe7eb',borderRadius:8,overflow:'auto'},table={width:'100%',borderCollapse:'collapse',fontSize:13},thead={background:'#edf3f5',color:'#45606f',textAlign:'left'},tr={borderTop:'1px solid #e3eaed'},th={padding:'10px 12px',fontSize:11,textTransform:'uppercase',letterSpacing:'.03em',whiteSpace:'nowrap'},td={padding:'11px 12px',color:'#294b5d',whiteSpace:'nowrap'},small={display:'block',color:'#7a8b95',marginTop:2},edit={border:'1px solid #b9d6e5',borderRadius:6,background:'#fff',color:'#176b94',padding:'6px 9px',cursor:'pointer',fontWeight:700},remove={border:'1px solid #efcaca',borderRadius:6,background:'#fff',color:'#b54b4b',padding:'6px 9px',cursor:'pointer'},backdrop={position:'fixed',inset:0,zIndex:1000,background:'rgba(7,36,50,.62)',display:'grid',placeItems:'center',padding:20},modal={width:'min(760px,96vw)',maxHeight:'90vh',overflow:'auto',background:'#fff',borderRadius:12,boxShadow:'0 24px 70px rgba(0,0,0,.25)'},modalHeader={display:'flex',justifyContent:'space-between',gap:20,padding:'20px 22px',borderBottom:'1px solid #dfe7eb'},close={border:0,background:'transparent',fontSize:26,color:'#637986',cursor:'pointer'},formGrid={display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,padding:'20px 22px'},field={display:'grid',gap:6,fontSize:13,fontWeight:700,color:'#486170'},input={width:'100%',boxSizing:'border-box',height:38,border:'1px solid #cbd9df',borderRadius:7,padding:'0 10px',font:'inherit',background:'#fff'},modalFooter={display:'flex',justifyContent:'flex-end',gap:9,padding:'14px 22px',borderTop:'1px solid #dfe7eb'}
