// Writes the SQL that loads the standard library into the shared RitsuFlow library (no organization, no project).
// Run: node scripts/standard-library/generate.mjs
import { writeFileSync } from 'node:fs'
import { usCeilings, usFloors, usWalls } from './us.mjs'

const q = v => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const j = v => `${q(JSON.stringify(v))}::jsonb`
const FRAMED = /montante|guia|chapa|stud|track|board/i

const walls = usWalls()
const ceilings = usCeilings()
const floors = usFloors()
const recipes = [...walls, ...ceilings, ...floors].map(t => t.recipe).filter(Boolean)
// Lines the app must keep (not counted by the layout) must not look like framing to it, and vice versa.
for (const w of walls) for (const l of w.recipe.lines) {
  const layout = !!(l.note && /framing layout/.test(l.note))
  if (!layout && FRAMED.test(l.mat)) throw new Error(`${w.code}: "${l.mat}" would be skipped as framing`)
}
// Every framing material of a wall recipe must be recognised as counted by the layout (no double count).
for (const w of walls) {
  const f = w.recipe.lines.filter(l => l.note && /framing layout/.test(l.note))
  for (const l of f) if (!FRAMED.test(l.mat)) throw new Error(`${w.code}: "${l.mat}" would be counted twice`)
}

/** Lets the library accept ceiling and floor types (same as migration 20261006_009); safe to run again. */
export const CATEGORY_FIX = `-- 0. Allow the 'ceiling' and 'floor' categories (same as migration 20261006_009; safe to run again).
do $$
declare
  c record;
begin
  for c in
    select con.conname
      from pg_constraint con
     where con.conrelid = 'public.takeoff_wall_types'::regclass
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%category%'
  loop
    execute format('alter table public.takeoff_wall_types drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.takeoff_wall_types
  add constraint takeoff_wall_types_category_check
  check (category in ('non_rated', 'rated', 'shaft', 'furring', 'chase', 'exterior', 'other', 'ceiling', 'floor'));
`

const recipeId = name => `(select r.id from public.takeoff_recipes r where r.organization_id is null and r.country_code = 'US' and r.name = ${q(name)} order by r.created_at limit 1)`
const notExists = code => `not exists (select 1 from public.takeoff_wall_types w where w.organization_id is null and w.project_id is null and w.country_code = 'US' and lower(w.code) = lower(${q(code)}))`

let sql = `-- RitsuScope standard library for the United States (generated by scripts/standard-library/generate.mjs).
-- ${walls.length} wall types (PT01…), ${ceilings.length} ceiling types (CL01…), ${floors.length} floor types (FL01…), each with a recipe holding its
-- complete material list, in the shared RitsuFlow library (no organization, no project): every company reads
-- them, only the platform owner edits them. Status 'review': consumption rates are common estimating values;
-- fire ratings, UL designs, STC and stud limiting heights must be checked against the current listings.
-- Includes the 'ceiling'/'floor' category update, so it runs on its own. Safe to run more than once: rows that
-- already exist (same name / code) are skipped, nothing is overwritten.

${CATEGORY_FIX}
-- 1. Recipes (material lists)
insert into public.takeoff_recipes (organization_id, country_code, name, maker, system, kind, status, mode, waste_included_pct, lines, source, notes)
select null, 'US', v.name, null, v.system, v.kind, 'review', 'fixed', 0, v.lines, v.source, v.notes
from (values
${recipes.map(rc => `  (${q(rc.name)}, ${q(rc.system)}, ${q(rc.kind)}, ${j(rc.lines)}, ${j({ basis: 'RitsuFlow standard library (US), common estimating values' })}, ${q('Per m² of wall face or area and per m of wall length or perimeter, in US purchase units. Studs, tracks, boards and screws are counted by the framing layout when framing is on.')})`).join(',\n')}
) as v(name, system, kind, lines, source, notes)
where not exists (select 1 from public.takeoff_recipes r where r.organization_id is null and r.country_code = 'US' and r.name = v.name);

-- 2. Wall types
`
for (const w of walls) {
  sql += `insert into public.takeoff_wall_types (organization_id, project_id, country_code, code, name, category, fire_rating_hr, stc_min, stc_max, rated_design, thickness_m, framing, boards, recipe_id, status, notes)
select null, null, 'US', ${q(w.code)}, ${q(w.name)}, ${q(w.category)}, ${w.fire ?? 'null'}, ${w.stc ? w.stc[0] : 'null'}, ${w.stc ? w.stc[1] : 'null'}, ${q(w.rated)}, ${w.thickness_m}, ${j(w.framing)}, ${j(w.boards)}, ${recipeId(w.recipe.name)}, 'review', ${q(w.notes)}
where ${notExists(w.code)};
`
}
sql += `
-- 3. Ceiling and floor types
`
for (const [list, cat] of [[ceilings, 'ceiling'], [floors, 'floor']]) {
  for (const t of list) {
    sql += `insert into public.takeoff_wall_types (organization_id, project_id, country_code, code, name, category, thickness_m, framing, recipe_id, status, notes)
select null, null, 'US', ${q(t.code)}, ${q(t.name)}, '${cat}', ${t.thickness_m}, ${j(t.framing)}, ${t.recipe ? recipeId(t.recipe.name) : 'null'}, 'review', ${q(t.notes)}
where ${notExists(t.code)};
`
  }
}
writeFileSync(new URL('../../supabase/migrations/20261007_002_ritsuscope_standard_library_us.sql', import.meta.url), sql)
console.log(`US: ${recipes.length} recipes, ${walls.length} walls, ${ceilings.length} ceilings, ${floors.length} floors`)

// --- Brazil: finishing materials for the drywall ceilings already in the shared library (CL01…CL07) ---------
const BR_CEILINGS = ['CL01', 'CL02', 'CL03', 'CL04', 'CL05', 'CL06', 'CL07']
const brLines = [
  { mat: 'Massa para tratamento de juntas', unit: 'kg', coef: 0.5, base: 'm2', waste: 10, packSize: 15, packName: 'balde 15 kg', note: 'Estimativa; ajustar ao fabricante.' },
  { mat: 'Fita de papel microperfurada 50 mm', unit: 'm', coef: 1.5, base: 'm2', waste: 5, packSize: 150, packName: 'rolo 150 m' },
  { mat: 'Arame galvanizado nº 18 (amarração e regulagem dos pendurais)', unit: 'kg', coef: 0.02, base: 'm2', waste: 10 },
]
const brName = code => `${code} – lista de materiais (BR)`
let br = `-- RitsuScope (Brazil): finishing materials for the standard drywall ceilings CL01…CL07 of the shared library
-- (generated by scripts/standard-library/generate.mjs). Profiles, hangers, boards and screws are estimated by the
-- ceiling type itself; this recipe adds joint compound, tape and tie wire. Safe to run more than once.
-- Run after the Brazilian standard list (20261007_001); includes the category update so it never fails on it.

${CATEGORY_FIX}
insert into public.takeoff_recipes (organization_id, country_code, name, maker, system, kind, status, mode, waste_included_pct, lines, source, notes)
select null, 'BR', v.name, null, 'Forro', 'area', 'review', 'fixed', 0, ${j(brLines)}, ${j({ basis: 'Biblioteca padrão RitsuFlow (BR), valores usuais de orçamento' })}, 'Por m² de forro.'
from (values ${BR_CEILINGS.map(c => `(${q(brName(c))})`).join(', ')}) as v(name)
where not exists (select 1 from public.takeoff_recipes r where r.organization_id is null and r.country_code = 'BR' and r.name = v.name);

-- Link each ceiling type to its recipe (only where none is set yet).
update public.takeoff_wall_types w
   set recipe_id = (select r.id from public.takeoff_recipes r where r.organization_id is null and r.country_code = 'BR' and r.name = w.code || ' – lista de materiais (BR)' order by r.created_at limit 1)
 where w.organization_id is null and w.project_id is null and w.country_code = 'BR' and w.category = 'ceiling'
   and w.code in (${BR_CEILINGS.map(q).join(', ')}) and w.recipe_id is null;
`
writeFileSync(new URL('../../supabase/migrations/20261007_003_ritsuscope_br_ceiling_finishing.sql', import.meta.url), br)
console.log(`BR: ${BR_CEILINGS.length} ceiling finishing recipes`)

// --- Brazil: standard ceiling (CL01…CL13) and floor (FL01…FL12) types, from the app's own lists -------------
const { STANDARD_CEILINGS } = await import('../../src/lib/takeoff/ceilingTypes.ts')
const { STANDARD_FLOORS } = await import('../../src/lib/takeoff/floorTypes.ts')
const brTypes = [
  ...STANDARD_CEILINGS.map(c => ({ ...c, category: 'ceiling', framing: { ceiling: c.spec, color: c.color } })),
  ...STANDARD_FLOORS.map(c => ({ ...c, category: 'floor', framing: { floor: c.spec, color: c.color } })),
]
const brBase = `-- RitsuScope: standard ceiling types (CL01…CL13) and floor types (FL01…FL12) for Brazil
-- (generated by scripts/standard-library/generate.mjs), in the shared RitsuFlow library (no organization, no
-- project): every company reads them, only the platform owner edits them. Companies can duplicate one into
-- their own library to customise it. Includes the 'ceiling'/'floor' category update, so it runs on its own.
-- Safe to run more than once: codes that already exist in the shared library are skipped, nothing is overwritten.

${CATEGORY_FIX}
-- 1. Standard ceiling and floor types (Brazil)
insert into public.takeoff_wall_types (organization_id, project_id, country_code, code, name, category, thickness_m, framing, notes, status)
select null, null, 'BR', v.code, v.name, v.category, v.thickness_m, v.framing, v.notes, 'approved'
from (values
${brTypes.map(t => `  (${q(t.code)}, ${q(t.name)}, ${q(t.category)}, ${t.thickness_m}, ${j(t.framing)}, ${q(t.notes['pt-BR'])})`).join(',\n')}
) as v(code, name, category, thickness_m, framing, notes)
where not exists (
  select 1 from public.takeoff_wall_types w
   where w.organization_id is null and w.project_id is null and w.country_code = 'BR' and lower(w.code) = lower(v.code)
);
`
writeFileSync(new URL('../../supabase/migrations/20261007_001_ritsuscope_standard_ceiling_floor_types.sql', import.meta.url), brBase)
console.log(`BR: ${brTypes.length} standard ceiling and floor types`)

// --- Colours: one per standard type (scripts/standard-library/colors.json), for rows already loaded ----------
const COLORS = JSON.parse((await import('node:fs')).readFileSync(new URL('./colors.json', import.meta.url), 'utf8'))
const standardNames = {
  BR: Object.fromEntries(brTypes.map(t => [t.code, t.name])),
  US: Object.fromEntries([...walls, ...ceilings, ...floors].map(t => [t.code, t.name])),
}
const kindOf = code => (code.startsWith('CL') ? 'ceiling' : code.startsWith('FL') ? 'floor' : 'wall')
const colorRows = Object.entries(COLORS).flatMap(([country, m]) => Object.entries(m).map(([code, color]) =>
  `    (${q(country)}, ${q(code)}, ${q(kindOf(code))}, ${q(standardNames[country][code])}, ${q(color)})`))
const colorSql = `-- RitsuScope: one colour per standard type (generated by scripts/standard-library/generate.mjs from colors.json).
-- Updates, for Brazil and the United States:
--   1. the standard types of the shared RitsuFlow library;
--   2. company copies of the standard ceiling/floor types that still have the old default colour and name
--      (types a company customised keep their colour);
--   3. takeoff items already drawn from those types that still have the type's old colour.
-- Safe to run more than once.
with v(country, code, kind, name, color) as (values
${colorRows.join(',\n')}
),
targets as (
  select w.id, coalesce(w.framing->>'color', '') as old_color, v.color
    from public.takeoff_wall_types w
    join v on w.country_code = v.country and upper(w.code) = v.code
           and ((v.kind = 'wall' and w.category not in ('ceiling', 'floor')) or w.category = v.kind)
   where w.project_id is null
     and (w.organization_id is null
          or (w.category in ('ceiling', 'floor') and w.name = v.name and upper(coalesce(w.framing->>'color', '')) in ('#7C3AED', '#B7791F')))
     and upper(coalesce(w.framing->>'color', '')) <> upper(v.color)
),
layers as (
  update public.takeoff_layers l
     set color = t.color
    from targets t
   where l.wall_type_id = t.id and upper(l.color) = upper(t.old_color)
  returning l.id
)
update public.takeoff_wall_types w
   set framing = jsonb_set(coalesce(w.framing, '{}'::jsonb), '{color}', to_jsonb(t.color))
  from targets t
 where w.id = t.id;
`
writeFileSync(new URL('../../supabase/migrations/20261007_004_ritsuscope_standard_type_colors.sql', import.meta.url), colorSql)
console.log(`Colours: ${colorRows.length} standard types`)
