// Completes the US wall types already in the shared library (migration 20261007_002): region, reference
// source and page, catalog products (stud, track, face A/B board, insulation) and the updated material lists
// (acoustical sealant on PT01/PT12, control joints on every wall).
// Run: node --experimental-strip-types --import ./scripts/ts-resolve.mjs scripts/standard-library/us-details.mjs
import { writeFileSync } from 'node:fs'
import { usWalls } from './us.mjs'

const q = v => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const j = v => `${q(JSON.stringify(v))}::jsonb`

/** Reference documents (shared, US). Cited per type in source + page/table. */
const SOURCES = [
  { key: 'ul', name: 'UL Product iQ – Fire Resistance Directory', publisher: 'UL Solutions', url: 'https://productiq.ulprospector.com',
    notes: 'Fire-rated designs (U400 series for steel-stud walls). Always check the current listing: board brands, layers, screws and joints.' },
  { key: 'ga600', name: 'GA-600 Fire Resistance and Sound Control Design Manual', publisher: 'Gypsum Association', url: 'https://gypsum.org',
    notes: 'Generic fire and sound (STC) assemblies for gypsum board systems.' },
  { key: 'usg', name: 'The Gypsum Construction Handbook', publisher: 'USG', url: 'https://www.usg.com',
    notes: 'Installation practice: framing, fastening, joint treatment, control joints, furring and shaft walls.' },
  { key: 'ga216', name: 'GA-216 Application and Finishing of Gypsum Panel Products', publisher: 'Gypsum Association', url: 'https://gypsum.org',
    notes: 'Fastener spacing, joint treatment levels and control joint spacing (30 ft max. on walls).' },
]
const srcId = key => `(select s.id from public.takeoff_reference_sources s where s.organization_id is null and s.country_code = 'US' and s.name = ${q(SOURCES.find(x => x.key === key).name)} order by s.created_at limit 1)`

/** Which document backs each type, and where to look in it. */
function citation(w) {
  if (w.category === 'rated' || w.category === 'shaft') return { key: 'ul', ref: `${w.rated} · ${w.fire} hr — check the current listing (layers, screws, joint treatment, head-of-wall joint)` }
  if (w.category === 'furring' || w.category === 'exterior') return { key: 'usg', ref: w.category === 'furring' ? 'Furring on masonry / concrete (hat channel)' : 'Exterior steel framing and gypsum sheathing; studs per the structural design' }
  return { key: 'ga600', ref: `Sound control tables: STC ${w.stc ? `${w.stc[0]}–${w.stc[1]}` : ''} for this build-up, perimeter sealed` }
}

// Catalog products: one generic product per name, linked to the types' slots.
const insulationOf = w => w.recipe.lines.find(l => l.unit === 'sf' && /wool|fiberglass|batt/i.test(l.mat))?.mat || null
const products = new Map()
const add = (name, category, unit, notes) => { if (name && !products.has(name)) products.set(name, { name, category, unit, notes }) }
const walls = usWalls()
for (const w of walls) {
  add(w.framing.studName, 'stud', 'm', 'Generic product; sold in 10\'–16\' lengths (ClarkDietrich, CEMCO, MarinoWARE…). Check limiting heights.')
  add(w.framing.trackName, 'track', 'm', 'Generic product; sold in 10\' lengths.')
  for (const b of w.boards) add(b.product, 'board', 'm²', 'Generic product (USG, CertainTeed, Gold Bond, Georgia-Pacific…): for rated walls use a brand listed in the UL design.')
  add(insulationOf(w), 'insulation', 'sf', 'Generic product; sold in bags of batts.')
}
const productId = name => (name ? `(select m.id from public.takeoff_materials m where m.organization_id is null and m.country_code = 'US' and lower(m.name) = lower(${q(name)}) order by m.created_at limit 1)` : 'null')

let sql = `-- RitsuScope: completes the United States wall types (PT01…PT12) in the shared library
-- (generated by scripts/standard-library/us-details.mjs). Run after 20261007_002.
-- 1. Reference documents  2. Catalog products  3. Region, source, page and products on each type
-- 4. Updated material lists (acoustical sealant on PT01/PT12, control joints on every wall).
-- Safe to run more than once. Types stay 'review' until you approve them.

-- 1. Reference documents
insert into public.takeoff_reference_sources (organization_id, name, publisher, country_code, url, notes)
select null, v.name, v.publisher, 'US', v.url, v.notes
from (values
${SOURCES.map(s => `  (${q(s.name)}, ${q(s.publisher)}, ${q(s.url)}, ${q(s.notes)})`).join(',\n')}
) as v(name, publisher, url, notes)
where not exists (select 1 from public.takeoff_reference_sources s where s.organization_id is null and s.country_code = 'US' and s.name = v.name);

-- 2. Catalog products (generic, status review)
insert into public.takeoff_materials (organization_id, country_code, name, category, unit, notes, status)
select null, 'US', v.name, v.category, v.unit, v.notes, 'review'
from (values
${[...products.values()].map(p => `  (${q(p.name)}, ${q(p.category)}, ${q(p.unit)}, ${q(p.notes)})`).join(',\n')}
) as v(name, category, unit, notes)
where not exists (select 1 from public.takeoff_materials m where m.organization_id is null and m.country_code = 'US' and lower(m.name) = lower(v.name));

-- 3. Region, source, page and catalog products on each wall type
`
for (const w of walls) {
  const c = citation(w)
  const a = w.boards.find(b => b.side === 'A')?.product
  const b = w.boards.find(x => x.side === 'B')?.product
  const slots = [['stud', w.framing.studName], ['track', w.framing.trackName], ['boardA', a], ['boardB', b], ['insulation', insulationOf(w)]].filter(([, n]) => n)
  sql += `update public.takeoff_wall_types set
  region = 'All states (IBC)',
  source_id = ${srcId(c.key)},
  source_ref = ${q(c.ref)},
  materials = jsonb_strip_nulls(jsonb_build_object(${slots.map(([k, n]) => `${q(k)}, ${productId(n)}`).join(', ')})),
  notes = ${q(w.notes)},
  updated_at = now()
where organization_id is null and project_id is null and country_code = 'US' and code = ${q(w.code)};
`
}
sql += `
-- 4. Updated material lists
`
for (const w of walls) {
  sql += `update public.takeoff_recipes set lines = ${j(w.recipe.lines)}, updated_at = now()
where organization_id is null and country_code = 'US' and name = ${q(w.recipe.name)};
`
}

writeFileSync(new URL('../../supabase/migrations/20261007_005_ritsuscope_us_wall_details.sql', import.meta.url), sql)
console.log(`US details: ${SOURCES.length} sources, ${products.size} products, ${walls.length} wall types`)
