'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '../../../lib/supabase/client'
import styles from './users.module.css'

const supabase=createClient()
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function UsersAccess(){
 const router=useRouter(); const [loading,setLoading]=useState(true); const [org,setOrg]=useState(null); const [members,setMembers]=useState([]); const [license,setLicense]=useState(null); const [message,setMessage]=useState(''); const [search,setSearch]=useState(''); const [showInvite,setShowInvite]=useState(false); const [sending,setSending]=useState(false); const [form,setForm]=useState({fullName:'',email:'',role:'member',projectAccessMode:'assigned_projects'})
 const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:mine,error:mineError}=await supabase.from('organization_members').select('organization_id,role,status,organizations(id,name,slug,organization_number,owner_user_id)').eq('user_id',user.id).eq('status','active');if(mineError)throw mineError;const membership=mine?.find(x=>['owner','admin'].includes(x.role))||mine?.[0];if(!membership)throw new Error('No company is connected to this account.');const organization=membership.organizations;const {data,error}=await supabase.from('organization_members').select('organization_id,user_id,role,status,joined_at,project_access_mode,profiles(id,full_name,email)').eq('organization_id',membership.organization_id).order('joined_at',{ascending:true});if(error)throw error;const {data:licenseRows}=await supabase.rpc('get_platform_organizations');const licenseRow=Array.isArray(licenseRows)?licenseRows.find(x=>x.organization_id===membership.organization_id):null;setOrg(organization);setMembers(data||[]);setLicense(licenseRow||null)},[router])
 useEffect(()=>{let active=true;load().catch(e=>active&&setMessage(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[load])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return members.filter(m=>!q||[m.profiles?.full_name,m.profiles?.email,m.role,m.status].join(' ').toLowerCase().includes(q))},[members,search])
 const active=members.filter(m=>m.status==='active').length; const limit=license?.seat_limit??null; const available=limit==null?'—':Math.max(0,limit-active)
 async function inviteUser(e){e.preventDefault();setMessage('');setSending(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Your session expired. Please sign in again.');const response=await fetch('/api/settings/users/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({...form,organizationId:org.id})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to invite user.');setShowInvite(false);setForm({fullName:'',email:'',role:'member',projectAccessMode:'assigned_projects'});setMessage(`Invitation sent to ${result.user.email}. The user will not consume a seat until activated.`);await load()}catch(error){setMessage(error.message)}finally{setSending(false)}}
 if(loading)return <main className={styles.loading}>Loading users & access...</main>
 return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><Image src="/logo-white.png" alt="RitsuFlow" width={180} height={65} priority/></div><div className={styles.headerTitle}><h1>Users & Access</h1><p>Organization users, roles and access control</p></div><div className={styles.headerActions}><Link className={styles.backButton} href="/settings">← Return to Settings</Link><button className={styles.addButton} type="button" onClick={()=>setShowInvite(true)}>+ Add User</button></div></header><section className={styles.content}>
  {message&&<div className={styles.message}>{message}</div>}
  <section className={styles.stats}><article><small>ORGANIZATION</small><strong className={styles.company}>{org?.name||'—'}</strong><p>{org?.organization_number||org?.slug||'Tenant isolated'}</p></article><article><small>ACTIVE USERS</small><strong>{active}</strong><p>Currently consuming seats</p></article><article><small>SEAT LIMIT</small><strong>{limit??'—'}</strong><p>Provisioning-controlled</p></article><article><small>SEATS AVAILABLE</small><strong>{available}</strong><p>Remaining active capacity</p></article></section>
  <section className={styles.card}><div className={styles.cardHead}><div><h3>Organization Users</h3><p>Manage who belongs to this organization and their current access status.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search users..."/></div><div className={styles.tableWrap}><table><thead><tr><th>User</th><th>Email</th><th>Company Role</th><th>Status</th><th>Project Access</th><th>Joined</th><th></th></tr></thead><tbody>{filtered.map(m=><tr key={m.user_id}><td><div className={styles.person}><b>{(m.profiles?.full_name||m.profiles?.email||'?').slice(0,1).toUpperCase()}</b><span><strong>{m.profiles?.full_name||'RitsuFlow User'}</strong><small>{m.user_id===org?.owner_user_id?'Primary Admin':''}</small></span></div></td><td>{m.profiles?.email||'—'}</td><td><span className={styles.role}>{label(m.role)}</span></td><td><span className={`${styles.status} ${styles[m.status]||''}`}>● {label(m.status)}</span></td><td>{label(m.project_access_mode||'assigned_projects')}</td><td>{m.joined_at?new Date(m.joined_at).toLocaleDateString():'—'}</td><td><button className={styles.edit} type="button" onClick={()=>setMessage(`Access editor for ${m.profiles?.full_name||m.profiles?.email||'this user'} will be connected with Roles & Permissions and Workspace Access.`)}>Manage</button></td></tr>)}{!filtered.length&&<tr><td colSpan="7" className={styles.empty}>No users found.</td></tr>}</tbody></table></div></section>
  <div className={styles.note}><strong>Access architecture</strong><span><b>Users & Access</b> controls who belongs to the organization and whether their account is active. <b>Roles & Permissions</b> defines what each role can do, while <b>Workspace Access</b> controls access to Projects, PreCon, FieldOp and RitsuCAD.</span></div>
 </section>{showInvite&&<div className={styles.overlay} onMouseDown={e=>e.target===e.currentTarget&&setShowInvite(false)}><form className={styles.modal} onSubmit={inviteUser}><div className={styles.modalHead}><div><h2>Add User</h2><p>Invite a person to {org?.name}.</p></div><button type="button" onClick={()=>setShowInvite(false)}>×</button></div><label>Full Name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Full name"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@company.com"/></label><div className={styles.formGrid}><label>Company Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Admin</option><option value="manager">Manager</option><option value="member">Member</option><option value="viewer">Viewer</option></select></label><label>Project Access<select value={form.projectAccessMode} onChange={e=>setForm({...form,projectAccessMode:e.target.value})}><option value="assigned_projects">Assigned Projects</option><option value="all_projects">All Projects</option></select></label></div><div className={styles.seatInfo}><b>Seat policy</b><span>Invited users do not consume a seat. A seat is consumed when the user becomes Active.</span></div><div className={styles.modalActions}><button type="button" className={styles.cancel} onClick={()=>setShowInvite(false)}>Cancel</button><button type="submit" className={styles.send} disabled={sending}>{sending?'Sending...':'Send Invitation'}</button></div></form></div>}</main>
}
