'use client'

import { useEffect, useMemo, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { createClient } from '../../../../../lib/supabase/client'
import styles from '../daily-reports.module.css'

const tabs=['Overview','General','Weather','Workforce','Production','Materials','Equipment','Safety','Issues','Notes','Attachments','Approval']

function GeneralSection({report,supabase,onSaved}){
 const [start,setStart]=useState(report.work_start_time||'')
 const [end,setEnd]=useState(report.work_end_time||'')
 const [notes,setNotes]=useState(report.general_notes||'')
 const [saving,setSaving]=useState(false)
 const [message,setMessage]=useState('')
 async function save(event){event.preventDefault();setSaving(true);setMessage('');const {data,error}=await supabase.from('daily_reports').update({work_start_time:start||null,work_end_time:end||null,general_notes:notes.trim()||null}).eq('id',report.id).select('id,work_start_time,work_end_time,general_notes').single();if(error)setMessage(error.message);else{setMessage('General information saved.');onSaved(data)}setSaving(false)}
 return <section className={styles.panel}><div className={styles.panelHead}><div><h3>General</h3><p>Core information for this field day. Project and report identity are inherited automatically.</p></div><span>{report.status}</span></div><form onSubmit={save} style={{display:'grid',gap:18,padding:18}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14}}><label style={{display:'grid',gap:7}}><b>Project</b><input value={report.projects?.name||''} disabled /></label><label style={{display:'grid',gap:7}}><b>Project code</b><input value={report.projects?.code||'—'} disabled /></label><label style={{display:'grid',gap:7}}><b>Report date</b><input value={report.report_date||''} disabled /></label><label style={{display:'grid',gap:7}}><b>Report number</b><input value={`DR-${String(report.report_number||0).padStart(4,'0')}`} disabled /></label><label style={{display:'grid',gap:7}}><b>Work start</b><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label style={{display:'grid',gap:7}}><b>Work end</b><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label style={{display:'grid',gap:7}}><b>Client</b><input value={report.projects?.client_name||'—'} disabled /></label><label style={{display:'grid',gap:7}}><b>Status</b><input value={report.status||'draft'} disabled /></label></div><label style={{display:'grid',gap:7}}><b>General notes</b><textarea rows={7} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record relevant field context that does not belong to a more specific Daily Report section."/></label><div style={{display:'flex',alignItems:'center',justifyContent:'flex-end',gap:12}}>{message&&<span>{message}</span>}<button className={styles.primaryButton} type="submit" disabled={saving}>{saving?'Saving...':'Save General'}</button></div></form></section>
}

function ProductionSection({report,supabase}){
 const [loading,setLoading]=useState(true);const [rows,setRows]=useState([]);const [values,setValues]=useState({});const [saving,setSaving]=useState(false);const [message,setMessage]=useState('')
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setMessage('');const {data:allocations,error:aError}=await supabase.from('location_service_quantities').select('id,location_id,service_id,quantity,locations(id,name,location_type),fieldop_activity:fieldop_project_activities!location_service_quantities_service_id_fkey(id,activity_name,unit,source,scope_item_id,scope_item:project_scopes(scope_code,scope_name,unit))').eq('project_id',report.projects.id).gt('quantity',0).order('created_at',{ascending:true});if(aError){if(!cancelled){setMessage(aError.message);setLoading(false)}return}const {data:production,error:pError}=await supabase.from('daily_report_production').select('id,location_service_quantity_id,fieldop_activity_id,actual_quantity,cumulative_quantity,production_status,notes').eq('daily_report_id',report.id);if(pError){if(!cancelled){setMessage(pError.message);setLoading(false)}return}const ids=(allocations||[]).map(x=>x.id);let previous=[];if(ids.length){const {data,error}=await supabase.from('daily_report_production').select('location_service_quantity_id,actual_quantity,daily_reports!inner(report_date)').in('location_service_quantity_id',ids).lt('daily_reports.report_date',report.report_date);if(!error)previous=data||[]}const previousBy={};previous.forEach(x=>{previousBy[x.location_service_quantity_id]=(previousBy[x.location_service_quantity_id]||0)+Number(x.actual_quantity||0)});const currentBy={};(production||[]).forEach(x=>{currentBy[x.location_service_quantity_id]=x});const prepared=(allocations||[]).map(a=>({allocation:a,current:currentBy[a.id]||null,previous:previousBy[a.id]||0}));const initial={};prepared.forEach(r=>{initial[r.allocation.id]=r.current?.actual_quantity??''});if(!cancelled){setRows(prepared);setValues(initial);setLoading(false)}}load();return()=>{cancelled=true}},[report.id,report.report_date,report.projects.id,supabase])
 async function save(){setSaving(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();for(const {allocation,previous,current} of rows){const today=Math.max(0,Number(values[allocation.id]||0));const allocated=Number(allocation.quantity||0);const cumulative=previous+today;const activity=allocation.fieldop_activity;const scope=activity?.scope_item;const item={daily_report_id:report.id,location_id:allocation.location_id,fieldop_activity_id:allocation.service_id,location_service_quantity_id:allocation.id,location_name:allocation.locations?.name||null,service_code:scope?.scope_code||null,service_name:scope?.scope_name||activity?.activity_name||'Production activity',unit:scope?.unit||activity?.unit||null,planned_quantity:allocated,actual_quantity:today,cumulative_quantity:cumulative,production_status:cumulative>=allocated?'completed':today>0?'in_progress':'not_started',source:'manual',created_by:user?.id||null};const query=current?.id?supabase.from('daily_report_production').update(item).eq('id',current.id):supabase.from('daily_report_production').insert(item);const {error}=await query;if(error){setMessage(error.message);setSaving(false);return}}setMessage('Production quantities saved.');setRows(current=>current.map(r=>({...r,current:{...(r.current||{}),actual_quantity:Number(values[r.allocation.id]||0)}})));setSaving(false)}
 if(loading)return <section className={styles.panel}><div className={styles.empty}>Loading allocated production scope...</div></section>
 const allocated=rows.reduce((s,r)=>s+Number(r.allocation.quantity||0),0);const previous=rows.reduce((s,r)=>s+r.previous,0);const today=rows.reduce((s,r)=>s+Number(values[r.allocation.id]||0),0)
 return <section className={styles.productionPanel}><div className={styles.productionHead}><div><span className={styles.eyebrowDark}>FIELD PRODUCTION</span><h2>Production by Location</h2><p>Report only what was produced today. Activities and quantities come from Scope Allocation.</p></div><div className={styles.productionStats}><div><span>Allocated</span><strong>{allocated.toFixed(2)}</strong></div><div><span>Previous</span><strong>{previous.toFixed(2)}</strong></div><div><span>Today</span><strong>{today.toFixed(2)}</strong></div><div><span>Remaining</span><strong>{Math.max(0,allocated-previous-today).toFixed(2)}</strong></div></div></div>{rows.length===0?<div className={styles.productionEmpty}><strong>No production scope is allocated by location yet.</strong><span>Use Project → Location Breakdown → Scope Allocation first. Daily Report will consume that allocation automatically.</span></div>:<div className={styles.productionTableWrap}><table className={styles.productionTable}><thead><tr><th>Location</th><th>Activity</th><th>Allocated</th><th>Previous</th><th>Today</th><th>Cumulative</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{rows.map(({allocation,previous})=>{const todayValue=Number(values[allocation.id]||0);const allocatedValue=Number(allocation.quantity||0);const cumulative=previous+todayValue;const remaining=Math.max(0,allocatedValue-cumulative);const status=cumulative>=allocatedValue?'Completed':todayValue>0?'In progress':'Not started';const activity=allocation.fieldop_activity;const scope=activity?.scope_item;const code=scope?.scope_code||'';const name=scope?.scope_name||activity?.activity_name||'Activity';const unit=scope?.unit||activity?.unit||'';return <tr key={allocation.id}><td><strong>{allocation.locations?.name||'Location'}</strong><small>{allocation.locations?.location_type||''}</small></td><td><strong>{code?`${code} · `:''}{name}</strong><small>{unit}</small></td><td>{allocatedValue.toFixed(2)}</td><td>{previous.toFixed(2)}</td><td><input className={styles.productionInput} type="number" min="0" max={Math.max(0,allocatedValue-previous)} step="0.01" value={values[allocation.id]??''} onChange={e=>setValues(v=>({...v,[allocation.id]:e.target.value}))}/></td><td>{cumulative.toFixed(2)}</td><td>{remaining.toFixed(2)}</td><td><span className={`${styles.productionStatus} ${status==='Completed'?styles.statusComplete:status==='In progress'?styles.statusProgress:''}`}>{status}</span></td></tr>})}</tbody></table></div>}<div className={styles.productionFooter}><span className={message.includes('saved')?styles.successMessage:styles.productionMessage}>{message||'Quantities entered here become the production record for this Daily Report.'}</span><button className={styles.primaryButton} type="button" disabled={saving||rows.length===0} onClick={save}>{saving?'Saving...':'Save Production'}</button></div></section>
}

export default function FieldOpDailyReportWorkspace(){
 const {reportId}=useParams();const supabase=useMemo(()=>createClient(),[]);const [report,setReport]=useState(null);const [loading,setLoading]=useState(true);const [active,setActive]=useState('Overview');const [error,setError]=useState('')
 useEffect(()=>{async function load(){setLoading(true);const {data,error}=await supabase.from('daily_reports').select('id,report_number,report_date,status,work_start_time,work_end_time,general_notes,projects(id,code,name,client_name)').eq('id',reportId).single();if(error)setError(error.message);else setReport(data);setLoading(false)}if(reportId)load()},[reportId,supabase])
 if(loading)return <main className={styles.page}><div className={styles.empty}>Loading Daily Report...</div></main>
 if(error||!report)return <main className={styles.page}><div className={styles.empty}><strong>Daily Report unavailable.</strong><p>{error}</p><Link href="/fieldop/reports/daily">Return to Daily Reports</Link></div></main>
 return <main className={styles.page}><header className={styles.header}><Image className={styles.logo} src="/logo-white.png" alt="RitsuFlow" width={160} height={58} priority/><div className={styles.headerTitle}><span className={styles.eyebrow}>FIELDOP · DAILY REPORT</span><h1>DR-{String(report.report_number||0).padStart(4,'0')}</h1></div><div className={styles.headerActions}><button className={styles.headerButton} type="button" aria-label="Notifications">♧</button><Link className={styles.headerButton} href="/fieldop">← Return to Workspace</Link><Link className={styles.secondaryButton} href="/fieldop/reports/daily">Reports</Link></div></header><section className={styles.reportMeta}><strong>{report.projects?.code?`${report.projects.code} · `:''}{report.projects?.name||'Project'}</strong><span>{report.report_date}</span><span>{report.projects?.client_name||''}</span><span className={styles.badge}>{report.status}</span></section><nav className={styles.tabs}>{tabs.map(tab=><button key={tab} type="button" onClick={()=>setActive(tab)} className={`${styles.tab} ${active===tab?styles.tabActive:''}`}>{tab}</button>)}</nav><section className={styles.workspace}>{active==='Overview'&&<><div className={styles.hero}><div><h2>Daily Report Overview</h2><p>Field execution for {report.report_date}. This workspace is native to FieldOp.</p></div></div><div className={styles.sectionGrid}><article className={styles.sectionCard}><h3>Workforce</h3><p>Crews, workers and labor hours will be connected here without duplicate field entry.</p></article><article className={styles.sectionCard}><h3>Production</h3><p>Installed quantities connect project scope, production location and daily field execution.</p></article><article className={styles.sectionCard}><h3>Field Evidence</h3><p>Photos, notes, safety observations and issues will support traceability.</p></article></div></>}{active==='General'&&<GeneralSection report={report} supabase={supabase} onSaved={data=>setReport(current=>({...current,...data}))}/>} {active==='Production'&&<ProductionSection report={report} supabase={supabase}/>} {!['Overview','General','Production'].includes(active)&&<section className={styles.panel}><div className={styles.panelHead}><h3>{active}</h3><span>FieldOp Daily Report</span></div><div className={styles.empty}>The new {active} workflow will be developed here from current field-use requirements. No legacy Daily Report UI is being reused.</div></section>}</section></main>
}
