-- RitsuScope (Brazil): finishing materials for the standard drywall ceilings CL01…CL07 of the shared library
-- (generated by scripts/standard-library/generate.mjs). Profiles, hangers, boards and screws are estimated by the
-- ceiling type itself; this recipe adds joint compound, tape and tie wire. Safe to run more than once.

insert into public.takeoff_recipes (organization_id, country_code, name, maker, system, kind, status, mode, waste_included_pct, lines, source, notes)
select null, 'BR', v.name, null, 'Forro', 'area', 'review', 'fixed', 0, '[{"mat":"Massa para tratamento de juntas","unit":"kg","coef":0.5,"base":"m2","waste":10,"packSize":15,"packName":"balde 15 kg","note":"Estimativa; ajustar ao fabricante."},{"mat":"Fita de papel microperfurada 50 mm","unit":"m","coef":1.5,"base":"m2","waste":5,"packSize":150,"packName":"rolo 150 m"},{"mat":"Arame galvanizado nº 18 (amarração e regulagem dos pendurais)","unit":"kg","coef":0.02,"base":"m2","waste":10}]'::jsonb, '{"basis":"Biblioteca padrão RitsuFlow (BR), valores usuais de orçamento"}'::jsonb, 'Por m² de forro.'
from (values ('CL01 – lista de materiais (BR)'), ('CL02 – lista de materiais (BR)'), ('CL03 – lista de materiais (BR)'), ('CL04 – lista de materiais (BR)'), ('CL05 – lista de materiais (BR)'), ('CL06 – lista de materiais (BR)'), ('CL07 – lista de materiais (BR)')) as v(name)
where not exists (select 1 from public.takeoff_recipes r where r.organization_id is null and r.country_code = 'BR' and r.name = v.name);

-- Link each ceiling type to its recipe (only where none is set yet).
update public.takeoff_wall_types w
   set recipe_id = (select r.id from public.takeoff_recipes r where r.organization_id is null and r.country_code = 'BR' and r.name = w.code || ' – lista de materiais (BR)' order by r.created_at limit 1)
 where w.organization_id is null and w.project_id is null and w.country_code = 'BR' and w.category = 'ceiling'
   and w.code in ('CL01', 'CL02', 'CL03', 'CL04', 'CL05', 'CL06', 'CL07') and w.recipe_id is null;
