-- RitsuScope: one colour per standard type (generated by scripts/standard-library/generate.mjs from colors.json).
-- Updates, for Brazil and the United States:
--   1. the standard types of the shared RitsuFlow library;
--   2. company copies of the standard ceiling/floor types that still have the old default colour and name
--      (types a company customised keep their colour);
--   3. takeoff items already drawn from those types that still have the type's old colour.
-- Safe to run more than once.
with v(country, code, kind, name, color) as (values
    ('BR', 'CL01', 'ceiling', 'Suspenso F530/600/ST12,5', '#0EA5E9'),
    ('BR', 'CL02', 'ceiling', 'Suspenso F530/600/RU12,5', '#C026D3'),
    ('BR', 'CL03', 'ceiling', 'Suspenso F530/400/2×RF12,5', '#14B8A6'),
    ('BR', 'CL04', 'ceiling', 'Suspenso F530/600/ST12,5/LV50', '#1E40AF'),
    ('BR', 'CL05', 'ceiling', 'Suspenso F530/400/ACU12,5', '#115E59'),
    ('BR', 'CL06', 'ceiling', 'Aderido F530/600/ST12,5', '#075985'),
    ('BR', 'CL07', 'ceiling', 'Autoportante M70/600/ST12,5', '#86198F'),
    ('BR', 'CL08', 'ceiling', 'Modular T24/625×625/Fibra mineral', '#8B5CF6'),
    ('BR', 'CL09', 'ceiling', 'Modular T24/625×625/Gesso vinílico', '#3B82F6'),
    ('BR', 'CL10', 'ceiling', 'Modular T24/625×1250/Lã de vidro', '#06B6D4'),
    ('BR', 'CL11', 'ceiling', 'Modular Clip-in/600×600/Metálico', '#5B21B6'),
    ('BR', 'CL12', 'ceiling', 'Lambril PVC/200', '#9333EA'),
    ('BR', 'CL13', 'ceiling', 'Linear metálico / baffle', '#1E3A8A'),
    ('BR', 'FL01', 'floor', 'Porcelanato 60×60 retificado', '#EA580C'),
    ('BR', 'FL02', 'floor', 'Porcelanato 90×90 retificado', '#9F1239'),
    ('BR', 'FL03', 'floor', 'Cerâmica 45×45 áreas molhadas', '#EAB308'),
    ('BR', 'FL04', 'floor', 'Vinílico manta hospitalar 2,0 mm soldada', '#854D0E'),
    ('BR', 'FL05', 'floor', 'Vinílico LVT régua 3 mm colado', '#78716C'),
    ('BR', 'FL06', 'floor', 'Piso elevado 600×600', '#EF4444'),
    ('BR', 'FL07', 'floor', 'Epóxi autonivelante 2 mm', '#9A3412'),
    ('BR', 'FL08', 'floor', 'Poliuretano cimentício 6 mm', '#D97706'),
    ('BR', 'FL09', 'floor', 'Laminado flutuante 7 mm', '#44403C'),
    ('BR', 'FL10', 'floor', 'Carpete em placas 50×50', '#7F1D1D'),
    ('BR', 'FL11', 'floor', 'Contrapiso argamassa 4 cm', '#CA8A04'),
    ('BR', 'FL12', 'floor', 'Concreto polido', '#B45309'),
    ('US', 'CL01', 'ceiling', 'Suspended drywall · 7/8" furring @ 16" · 1× 5/8" Type X', '#0EA5E9'),
    ('US', 'CL02', 'ceiling', 'Suspended drywall · 7/8" furring @ 16" · 1× 5/8" Type X moisture-resistant', '#C026D3'),
    ('US', 'CL03', 'ceiling', 'Suspended drywall · 7/8" furring @ 16" · 2× 5/8" Type X (fire-rated)', '#14B8A6'),
    ('US', 'CL04', 'ceiling', 'ACT 2''×2'' mineral fiber · 15/16" exposed grid', '#1E40AF'),
    ('US', 'CL05', 'ceiling', 'ACT 2''×4'' mineral fiber · 15/16" exposed grid', '#115E59'),
    ('US', 'CL06', 'ceiling', 'ACT 2''×2'' vinyl-faced gypsum · 15/16" grid · hold-down clips', '#075985'),
    ('US', 'FL01', 'floor', 'VCT 12"×12"×1/8"', '#EA580C'),
    ('US', 'FL02', 'floor', 'Sheet vinyl homogeneous 2.0 mm · heat-welded · 6" flash cove', '#9F1239'),
    ('US', 'FL03', 'floor', 'LVT plank 7"×48" · 2.5 mm · glue-down', '#EAB308'),
    ('US', 'FL04', 'floor', 'Porcelain tile 24"×24" · large-format mortar', '#854D0E'),
    ('US', 'FL05', 'floor', 'Ceramic tile 12"×12" · wet areas · waterproofing', '#78716C'),
    ('US', 'FL06', 'floor', 'Carpet tile 24"×24"', '#EF4444'),
    ('US', 'FL07', 'floor', 'Raised access floor 24"×24"', '#9A3412'),
    ('US', 'FL08', 'floor', 'Epoxy resinous flooring 1/8" · 6" integral cove', '#D97706'),
    ('US', 'FL09', 'floor', 'Polished concrete (grind, densify, polish)', '#44403C'),
    ('US', 'FL10', 'floor', 'Engineered wood 1/2" · floating', '#7F1D1D'),
    ('US', 'PT01', 'wall', '3-5/8" 25 ga @ 16" · 1× 5/8" Type X each side', '#84CC16'),
    ('US', 'PT02', 'wall', '3-5/8" 25 ga @ 16" · 1× 5/8" Type X each side · 3" mineral wool', '#3F6212'),
    ('US', 'PT03', 'wall', '3-5/8" 20 ga EQ @ 16" · 1× 5/8" Type X each side · 3" mineral wool · 1 hr', '#EC4899'),
    ('US', 'PT04', 'wall', '3-5/8" 20 ga EQ @ 16" · 2× 5/8" Type X each side · 3" mineral wool · 2 hr', '#16A34A'),
    ('US', 'PT05', 'wall', '6" 20 ga EQ @ 16" · 1× 5/8" Type X each side · 3-1/2" mineral wool · 1 hr', '#3B82F6'),
    ('US', 'PT06', 'wall', '3-5/8" 20 ga EQ @ 16" · 5/8" Type X moisture-resistant (wet side) + 5/8" Type X · 1 hr', '#6B21A8'),
    ('US', 'PT07', 'wall', '3-5/8" 20 ga EQ @ 16" · 1/2" cement board (tile side) + 5/8" Type X', '#06B6D4'),
    ('US', 'PT08', 'wall', '3-5/8" 20 ga EQ @ 16" · 5/8" abuse-resistant Type X each side · 3" mineral wool · 1 hr', '#047857'),
    ('US', 'PT09', 'wall', '7/8" hat channel @ 16" on masonry · 1× 5/8" Type X', '#9333EA'),
    ('US', 'PT10', 'wall', 'Shaft wall 2-1/2" CH stud @ 24" · 1" shaftliner + 2× 5/8" Type X · 2 hr', '#10B981'),
    ('US', 'PT11', 'wall', 'Exterior 6" 18 ga @ 16" · 5/8" exterior sheathing + 5/8" Type X · R-19', '#1E293B'),
    ('US', 'PT12', 'wall', 'Chase wall double 2-1/2" 25 ga @ 16" · 1× 5/8" Type X each side', '#65A30D')
),
targets as (
  select w.id, coalesce(w.framing->>'color', '') as old_color, v.color
    from public.takeoff_wall_types w
    join v on w.country_code = v.country and upper(w.code) = v.code
           and ((v.kind = 'wall' and w.category not in ('ceiling', 'floor')) or w.category = v.kind)
   where w.project_id is null
     and (w.organization_id is null
          or (w.category in ('ceiling', 'floor') and w.name = v.name and upper(coalesce(w.framing->>'color', '')) in ('#7C3AED', '#B7791F')))
     and upper(coalesce(w.framing->>'color', '')) <> upper(v.color)
),
layers as (
  update public.takeoff_layers l
     set color = t.color
    from targets t
   where l.wall_type_id = t.id and upper(l.color) = upper(t.old_color)
  returning l.id
)
update public.takeoff_wall_types w
   set framing = jsonb_set(coalesce(w.framing, '{}'::jsonb), '{color}', to_jsonb(t.color))
  from targets t
 where w.id = t.id;
