-- RitsuScope: standard ceiling types (CL01…CL13) and floor types (FL01…FL12) for Brazil
-- (generated by scripts/standard-library/generate.mjs), in the shared RitsuFlow library (no organization, no
-- project): every company reads them, only the platform owner edits them. Companies can duplicate one into
-- their own library to customise it. Includes the 'ceiling'/'floor' category update, so it runs on its own.
-- Safe to run more than once: codes that already exist in the shared library are skipped, nothing is overwritten.

-- 0. Allow the 'ceiling' and 'floor' categories (same as migration 20261006_009; safe to run again).
do $$
declare
  c record;
begin
  for c in
    select con.conname
      from pg_constraint con
     where con.conrelid = 'public.takeoff_wall_types'::regclass
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%category%'
  loop
    execute format('alter table public.takeoff_wall_types drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.takeoff_wall_types
  add constraint takeoff_wall_types_category_check
  check (category in ('non_rated', 'rated', 'shaft', 'furring', 'chase', 'exterior', 'other', 'ceiling', 'floor'));

-- 1. Standard ceiling and floor types (Brazil)
insert into public.takeoff_wall_types (organization_id, project_id, country_code, code, name, category, thickness_m, framing, notes, status)
select null, null, 'BR', v.code, v.name, v.category, v.thickness_m, v.framing, v.notes, 'approved'
from (values
  ('CL01', 'Suspenso F530/600/ST12,5', 'ceiling', 0.0125, '{"ceiling":{"system":"suspended","profile":"Perfil F530","spacing_m":0.6,"hanger_m":1.2,"board":"Chapa ST 12,5 mm","layers":1},"color":"#7C3AED"}'::jsonb, 'Forro monolítico em áreas secas: salas, escritórios, circulações.'),
  ('CL02', 'Suspenso F530/600/RU12,5', 'ceiling', 0.0125, '{"ceiling":{"system":"suspended","profile":"Perfil F530","spacing_m":0.6,"hanger_m":1.2,"board":"Chapa RU 12,5 mm","layers":1},"color":"#7C3AED"}'::jsonb, 'Áreas úmidas: banheiros, copas, áreas de serviço.'),
  ('CL03', 'Suspenso F530/400/2×RF12,5', 'ceiling', 0.025, '{"ceiling":{"system":"suspended","profile":"Perfil F530","spacing_m":0.4,"hanger_m":1,"board":"Chapa RF 12,5 mm","layers":2},"color":"#7C3AED"}'::jsonb, 'Forro resistente ao fogo; conferir o sistema ensaiado do fabricante.'),
  ('CL04', 'Suspenso F530/600/ST12,5/LV50', 'ceiling', 0.0125, '{"ceiling":{"system":"suspended","profile":"Perfil F530","spacing_m":0.6,"hanger_m":1.2,"board":"Chapa ST 12,5 mm","layers":1,"insulation":"Lã de vidro 50 mm"},"color":"#7C3AED"}'::jsonb, 'Conforto acústico/térmico: enfermarias, salas de reunião.'),
  ('CL05', 'Suspenso F530/400/ACU12,5', 'ceiling', 0.0125, '{"ceiling":{"system":"suspended","profile":"Perfil F530","spacing_m":0.4,"hanger_m":1,"board":"Chapa acústica perfurada 12,5 mm","layers":1},"color":"#7C3AED"}'::jsonb, 'Placa perfurada com véu acústico: auditórios, áreas de espera.'),
  ('CL06', 'Aderido F530/600/ST12,5', 'ceiling', 0.0125, '{"ceiling":{"system":"direct","profile":"Perfil F530","spacing_m":0.6,"hanger_m":0.6,"board":"Chapa ST 12,5 mm","layers":1},"color":"#7C3AED"}'::jsonb, 'Fixado direto na laje com suportes, sem pendurais: pouco plenum, reformas.'),
  ('CL07', 'Autoportante M70/600/ST12,5', 'ceiling', 0.0125, '{"ceiling":{"system":"self","profile":"Montante M70","spacing_m":0.6,"board":"Chapa ST 12,5 mm","layers":1},"color":"#7C3AED"}'::jsonb, 'Vão livre de parede a parede, sem pendurais: circulações com muitas instalações.'),
  ('CL08', 'Modular T24/625×625/Fibra mineral', 'ceiling', 0.015, '{"ceiling":{"system":"grid","tile_w_m":0.625,"tile_l_m":0.625,"hanger_m":1.2,"tile":"Placa de fibra mineral 625×625"},"color":"#7C3AED"}'::jsonb, 'Removível em perfil T aparente: escritórios, corredores técnicos.'),
  ('CL09', 'Modular T24/625×625/Gesso vinílico', 'ceiling', 0.008, '{"ceiling":{"system":"grid","tile_w_m":0.625,"tile_l_m":0.625,"hanger_m":1.2,"tile":"Placa de gesso revestida em vinil 625×625"},"color":"#7C3AED"}'::jsonb, 'Lavável: hospitais, áreas limpas, laboratórios.'),
  ('CL10', 'Modular T24/625×1250/Lã de vidro', 'ceiling', 0.02, '{"ceiling":{"system":"grid","tile_w_m":0.625,"tile_l_m":1.25,"hanger_m":1.2,"tile":"Painel de lã de vidro 625×1250"},"color":"#7C3AED"}'::jsonb, 'Acústico: escritórios abertos, salões.'),
  ('CL11', 'Modular Clip-in/600×600/Metálico', 'ceiling', 0.005, '{"ceiling":{"system":"clipin","tile_w_m":0.6,"tile_l_m":0.6,"hanger_m":1.2,"tile":"Placa metálica clip-in 600×600"},"color":"#7C3AED"}'::jsonb, 'Grelha oculta: áreas de higiene e grande circulação.'),
  ('CL12', 'Lambril PVC/200', 'ceiling', 0.008, '{"ceiling":{"system":"pvc","spacing_m":0.5,"tile":"Lambril de PVC 200 mm"},"color":"#7C3AED"}'::jsonb, 'Baixo custo, lavável: áreas técnicas, garagens.'),
  ('CL13', 'Linear metálico / baffle', 'ceiling', 0.02, '{"ceiling":{"system":"open","hanger_m":1.2,"tile":"Painel linear metálico"},"color":"#7C3AED"}'::jsonb, 'Forro arquitetônico aberto ou semiaberto: halls, áreas nobres.'),
  ('FL01', 'Porcelanato 60×60 retificado', 'floor', 0.009, '{"floor":{"system":"tile","product":"Porcelanato 60×60","tile_w_m":0.6,"tile_l_m":0.6,"joint_mm":2,"tile_mm":9,"adhesive_kg_m2":5,"adhesive":"Argamassa colante ACIII","skirting":"Rodapé porcelanato h=7 cm","waste_pct":10},"color":"#B7791F"}'::jsonb, 'Áreas secas e circulações; dupla colagem.'),
  ('FL02', 'Porcelanato 90×90 retificado', 'floor', 0.01, '{"floor":{"system":"tile","product":"Porcelanato 90×90","tile_w_m":0.9,"tile_l_m":0.9,"joint_mm":2,"tile_mm":10,"adhesive_kg_m2":6,"adhesive":"Argamassa colante ACIII","skirting":"Rodapé porcelanato h=7 cm","waste_pct":12},"color":"#B7791F"}'::jsonb, 'Halls e áreas nobres; mais perda de corte.'),
  ('FL03', 'Cerâmica 45×45 áreas molhadas', 'floor', 0.008, '{"floor":{"system":"tile","product":"Cerâmica 45×45 PEI 4","tile_w_m":0.45,"tile_l_m":0.45,"joint_mm":3,"tile_mm":8,"adhesive_kg_m2":4,"adhesive":"Argamassa colante ACII","waste_pct":10},"color":"#B7791F"}'::jsonb, 'Banheiros, copas e áreas de serviço (rodapé pelo revestimento de parede).'),
  ('FL04', 'Vinílico manta hospitalar 2,0 mm soldada', 'floor', 0.002, '{"floor":{"system":"vinyl_sheet","product":"Manta vinílica hospitalar 2,0 mm","roll_w_m":2,"adhesive_kg_m2":0.35,"adhesive":"Adesivo acrílico para vinílico","skirting":"Rodapé vinílico boleado (meia-cana)","waste_pct":8},"color":"#B7791F"}'::jsonb, 'Hospitais: emendas soldadas a quente e rodapé boleado, sem frestas.'),
  ('FL05', 'Vinílico LVT régua 3 mm colado', 'floor', 0.003, '{"floor":{"system":"vinyl_tile","product":"Régua vinílica LVT 3 mm","adhesive_kg_m2":0.35,"adhesive":"Adesivo acrílico para vinílico","skirting":"Rodapé vinílico h=7 cm","waste_pct":8},"color":"#B7791F"}'::jsonb, 'Consultórios, quartos e escritórios.'),
  ('FL06', 'Piso elevado 600×600', 'floor', 0.03, '{"floor":{"system":"raised","product":"Placa de piso elevado 600×600","tile_w_m":0.6,"tile_l_m":0.6,"waste_pct":3},"color":"#B7791F"}'::jsonb, 'Salas técnicas, TI e CPD (altura pelos pedestais).'),
  ('FL07', 'Epóxi autonivelante 2 mm', 'floor', 0.002, '{"floor":{"system":"resin","product":"Resina epóxi autonivelante","thickness_mm":2,"kg_m2_mm":1.6,"skirting":"Rodapé epóxi meia-cana","waste_pct":5},"color":"#B7791F"}'::jsonb, 'Laboratórios, áreas limpas e técnicas.'),
  ('FL08', 'Poliuretano cimentício 6 mm', 'floor', 0.006, '{"floor":{"system":"resin","product":"Poliuretano cimentício","thickness_mm":6,"kg_m2_mm":2,"skirting":"Rodapé PU meia-cana","waste_pct":5},"color":"#B7791F"}'::jsonb, 'Cozinhas industriais e áreas de lavagem (CME, expurgo).'),
  ('FL09', 'Laminado flutuante 7 mm', 'floor', 0.007, '{"floor":{"system":"laminate","product":"Piso laminado 7 mm","underlay":"Manta de polietileno 2 mm","skirting":"Rodapé MDF h=7 cm","waste_pct":8},"color":"#B7791F"}'::jsonb, 'Áreas administrativas secas.'),
  ('FL10', 'Carpete em placas 50×50', 'floor', 0.006, '{"floor":{"system":"carpet","product":"Carpete em placas 50×50","tile_w_m":0.5,"tile_l_m":0.5,"adhesive_kg_m2":0.15,"adhesive":"Adesivo fixador (tackifier)","skirting":"Rodapé MDF h=7 cm","waste_pct":5},"color":"#B7791F"}'::jsonb, 'Escritórios, auditórios e salas de reunião.'),
  ('FL11', 'Contrapiso argamassa 4 cm', 'floor', 0.04, '{"floor":{"system":"screed","product":"Argamassa de contrapiso","thickness_mm":40,"waste_pct":5},"color":"#B7791F"}'::jsonb, 'Regularização sob o revestimento.'),
  ('FL12', 'Concreto polido', 'floor', 0.001, '{"floor":{"system":"other","product":"Polimento de concreto"},"color":"#B7791F"}'::jsonb, 'Garagens, depósitos e áreas industriais.')
) as v(code, name, category, thickness_m, framing, notes)
where not exists (
  select 1 from public.takeoff_wall_types w
   where w.organization_id is null and w.project_id is null and w.country_code = 'BR' and lower(w.code) = lower(v.code)
);
