'use client'

import { useEffect, useMemo, useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '../../lib/supabase'

function makeTree(rows){const map=new Map();rows.forEach(row=>{const key=row.parent_id||'root';if(!map.has(key))map.set(key,[]);map.get(key).push(row)});return map}

export default function DrawingLocationPanel(){
 const params=useSearchParams(),router=useRouter(),pathname=usePathname(),projectId=params.get('projectId'),documentId=params.get('documentId')
 const enabled=params.get('mode')==='location-mapping'&&params.get('locationStep')==='drawing'&&projectId&&documentId
 const [locations,setLocations]=useState([]),[selected,setSelected]=useState(new Set()),[expanded,setExpanded]=useState(new Set()),[fileName,setFileName]=useState('Current Drawing'),[status,setStatus]=useState(''),[saving,setSaving]=useState(false)
 const tree=useMemo(()=>makeTree(locations),[locations])
 useEffect(()=>{if(!enabled)return;let live=true;(async()=>{setStatus('Loading…');const [{data:locs},{data:doc},{data:links}]=await Promise.all([supabase.from('locations').select('id,parent_id,name,location_type,sequence_number').eq('project_id',projectId).order('sequence_number'),supabase.from('project_documents').select('file_name').eq('id',documentId).eq('project_id',projectId).maybeSingle(),supabase.from('drawing_location_associations').select('location_id').eq('project_id',projectId).eq('document_id',documentId)]);if(!live)return;setLocations(locs||[]);setFileName(doc?.file_name||'Current Drawing');setSelected(new Set((links||[]).map(x=>x.location_id)));setExpanded(new Set((locs||[]).filter(x=>!x.parent_id).map(x=>x.id)));setStatus('')})();return()=>{live=false}},[enabled,projectId,documentId])
 function close(){const p=new URLSearchParams(params.toString());p.delete('mode');p.delete('locationStep');router.replace(`${pathname}?${p.toString()}`,{scroll:false})}
 function choose(id){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function expand(id){setExpanded(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 async function save(){setSaving(true);setStatus('');const del=await supabase.from('drawing_location_associations').delete().eq('project_id',projectId).eq('document_id',documentId);if(del.error){setStatus(del.error.message);setSaving(false);return}if(selected.size){const add=await supabase.from('drawing_location_associations').insert([...selected].map(location_id=>({project_id:projectId,document_id:documentId,location_id})));if(add.error){setStatus(add.error.message);setSaving(false);return}}window.dispatchEvent(new CustomEvent('ritsucad:drawing-location-associations-changed',{detail:{projectId,documentId,locationIds:[...selected]}}));setSaving(false);close()}
 function branch(parent='root',depth=0){return(tree.get(parent)||[]).map(item=>{const kids=tree.get(item.id)||[],open=expanded.has(item.id);return <div key={item.id}><div className={selected.has(item.id)?'dlRow on':'dlRow'} style={{paddingLeft:10+depth*17}}><button type="button" onClick={()=>{if(kids.length)expand(item.id)}} aria-label={kids.length?`${open?'Collapse':'Expand'} ${item.name}`:''}>{kids.length?(open?'▾':'▸'):'◇'}</button><label><input type="checkbox" checked={selected.has(item.id)} onChange={()=>choose(item.id)}/><b>{item.name}</b></label></div>{kids.length>0&&open?branch(item.id,depth+1):null}</div>})}
 if(!enabled)return null
 return <aside className="drawingLocationPanel"><style>{css}</style><header><div><small>ASSOCIATE DRAWING TO LOCATION</small><b>{fileName}</b></div><button onClick={close} title="Close">×</button></header><div className="dlIntro"><strong>Select exact location(s)</strong><span>Choose only the LBS location(s) this drawing directly represents. Selecting a parent does not select its children.</span></div><main>{status==='Loading…'?<div className="dlEmpty">Loading project locations…</div>:branch()}</main>{status&&status!=='Loading…'&&<div className="dlStatus">{status}</div>}<footer><div><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save Association'}</button></div><small>Drawing association defines context. Spatial boundaries are mapped separately.</small></footer></aside>
}

const css=`.drawingLocationPanel{position:fixed;z-index:83;top:176px;right:28px;bottom:88px;width:360px;display:flex;flex-direction:column;background:#fff;border:1px solid #aebfc8;border-radius:8px;box-shadow:0 10px 30px rgba(15,52,70,.24);color:#0d3347;overflow:hidden}.drawingLocationPanel header{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #dce6eb;background:#fff}.drawingLocationPanel header div{display:flex;min-width:0;flex-direction:column;gap:4px}.drawingLocationPanel header small{font-size:8px;color:#008f88;font-weight:900;letter-spacing:.1em}.drawingLocationPanel header b{max-width:285px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.drawingLocationPanel header>button{width:27px;height:27px;border:0;border-radius:50%;background:#eef4f6;color:#416777;font-size:18px;cursor:pointer}.dlIntro{display:flex;flex-direction:column;gap:3px;padding:10px 14px;border-bottom:1px solid #dce6eb;background:#f7fbfc}.dlIntro strong{font-size:10px}.dlIntro span{color:#607d89;font-size:8.5px;line-height:1.35}.drawingLocationPanel main{flex:1;overflow:auto;padding:3px 0}.dlRow{height:30px;display:flex;align-items:center;border-bottom:1px solid #f0f4f6}.dlRow.on{background:#e9f7f7;box-shadow:inset 3px 0 0 #0aa3a0}.dlRow>button{width:22px;border:0;background:transparent;color:#2e657b;font-size:8px;cursor:pointer}.dlRow label{flex:1;display:flex;align-items:center;gap:8px;cursor:pointer}.dlRow input{accent-color:#00a59d}.dlRow b{font-size:9.5px}.dlStatus,.dlEmpty{margin:8px 12px;padding:9px;background:#eef8f8;color:#17627c;font-size:9px}.drawingLocationPanel footer{padding:10px 12px;border-top:1px solid #dce6eb;background:#f8fafb;display:flex;flex-direction:column;gap:7px}.drawingLocationPanel footer>div{display:flex;justify-content:flex-end;gap:7px}.drawingLocationPanel footer button{height:32px;padding:0 14px;border-radius:4px;font-size:9px;font-weight:900;cursor:pointer}.drawingLocationPanel footer .secondary{border:1px solid #bdcdd5;background:#fff;color:#31596c}.drawingLocationPanel footer .primary{min-width:125px;border:0;background:#056b88;color:#fff}.drawingLocationPanel footer .primary:disabled{opacity:.55;cursor:default}.drawingLocationPanel footer small{text-align:right;color:#718995;font-size:7.5px}`