'use client'

import { useEffect, useMemo, useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '../../lib/supabase'

function buildTree(locations){const m=new Map();locations.forEach(x=>{const k=x.parent_id||'root';if(!m.has(k))m.set(k,[]);m.get(k).push(x)});m.forEach(a=>a.sort((x,y)=>Number(x.sequence_number||0)-Number(y.sequence_number||0)||String(x.name||'').localeCompare(String(y.name||''))));return m}

export default function LocationMappingPanel(){
 const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams()
 const projectId=searchParams.get('projectId'),documentId=searchParams.get('documentId')
 const enabled=searchParams.get('mode')==='location-mapping'&&projectId&&documentId
 const [locations,setLocations]=useState([]),[mapped,setMapped]=useState(new Set()),[expanded,setExpanded]=useState(new Set()),[loading,setLoading]=useState(Boolean(enabled)),[error,setError]=useState('')
 const tree=useMemo(()=>buildTree(locations),[locations])
 useEffect(()=>{if(!enabled)return;let active=true;(async()=>{setLoading(true);setError('');const [{data:locs,error:le},{data:map,error:me}]=await Promise.all([supabase.from('locations').select('id,parent_id,name,location_type,sequence_number').eq('project_id',projectId).order('sequence_number',{ascending:true}),supabase.from('project_drawing_maps').select('id').eq('project_id',projectId).eq('document_id',documentId).eq('page_number',1).maybeSingle()]);if(!active)return;if(le)setError(le.message);else{setLocations(locs||[]);setExpanded(new Set((locs||[]).filter(x=>!x.parent_id).map(x=>x.id)))}if(me)setError(c=>c||me.message);else if(map){const {data:g,error:ge}=await supabase.from('project_drawing_location_geometries').select('location_id').eq('drawing_map_id',map.id);if(!ge)setMapped(new Set((g||[]).map(x=>x.location_id)))}setLoading(false)})();return()=>{active=false}},[enabled,projectId,documentId])
 function close(){const p=new URLSearchParams(searchParams.toString());p.delete('mode');router.replace(`${pathname}?${p.toString()}`,{scroll:false})}
 function toggle(id){setExpanded(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n})}
 function branch(parent='root',depth=0){return(tree.get(parent)||[]).map(x=>{const kids=tree.get(x.id)||[],open=expanded.has(x.id),done=mapped.has(x.id);return <div key={x.id}><button type="button" style={{...row,paddingLeft:12+depth*18}} onClick={()=>kids.length&&toggle(x.id)}><span style={chev}>{kids.length?(open?'▾':'▸'):'•'}</span><span style={text}><strong>{x.name}</strong><small style={type}>{x.location_type||'Location'}</small></span><span style={done?yes:no}>{done?'Mapped':'Unmapped'}</span></button>{kids.length&&open&&branch(x.id,depth+1)}</div>})}
 if(!enabled)return null
 return <aside style={panel}><div style={header}><div><div style={eye}>PROJECT LOCATION STRUCTURE</div><div style={title}>Location Breakdown Structure</div></div><button type="button" onClick={close} style={closeBtn} title="Close">×</button></div><div style={bar}><span style={connected}>LBS Connected</span><span style={count}>{mapped.size} mapped</span></div><div style={body}>{loading?<div style={empty}>Loading project locations...</div>:error?<div style={err}>{error}</div>:locations.length===0?<div style={empty}>No locations are available. Create the project Location Breakdown Structure in Project Setup first.</div>:branch()}</div><div style={foot}>RitsuCAD reads this hierarchy directly from the project's Location Breakdown Structure. No duplicate location structure is created here.</div></aside>
}

const panel={position:'fixed',top:88,right:14,bottom:34,width:350,zIndex:80,display:'flex',flexDirection:'column',background:'#fff',border:'1px solid #cbd8df',borderRadius:10,boxShadow:'-8px 8px 24px rgba(15,52,70,.12)',fontFamily:'inherit',color:'#0d3347',overflow:'hidden'},header={display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:'14px 15px',borderBottom:'1px solid #dce6eb'},eye={fontSize:9,fontWeight:900,letterSpacing:'1.2px',color:'#008f8f'},title={marginTop:3,fontSize:16,fontWeight:900},closeBtn={width:27,height:27,border:'1px solid #d4e0e5',borderRadius:6,background:'#fff',color:'#52707e',fontSize:17,cursor:'pointer'},bar={display:'flex',justifyContent:'space-between',alignItems:'center',padding:'9px 14px',background:'#f6fafb',borderBottom:'1px solid #e1e9ed'},connected={border:'1px solid #9ed8d8',background:'#effafa',color:'#087f7f',borderRadius:999,padding:'4px 8px',fontSize:9,fontWeight:900},count={fontSize:9.5,fontWeight:800,color:'#718995'},body={flex:1,overflowY:'auto',padding:'8px 0'},row={width:'100%',minHeight:47,display:'flex',alignItems:'center',gap:8,paddingRight:12,border:0,borderBottom:'1px solid #edf2f4',background:'#fff',color:'#173f52',textAlign:'left',cursor:'pointer'},chev={width:14,color:'#64808d',fontSize:12},text={display:'flex',flex:1,minWidth:0,flexDirection:'column',gap:2,fontSize:11},type={fontSize:9,color:'#8a9da6',fontWeight:700,textTransform:'capitalize'},yes={border:'1px solid #9ed8d8',borderRadius:999,padding:'3px 6px',background:'#eaf9f8',color:'#087f7f',fontSize:8.5,fontWeight:900},no={border:'1px solid #d9e2e6',borderRadius:999,padding:'3px 6px',background:'#f7f9fa',color:'#8b9ba3',fontSize:8.5,fontWeight:800},foot={padding:'10px 14px',borderTop:'1px solid #e1e9ed',background:'#f8fbfc',color:'#738b96',fontSize:9.5,lineHeight:1.4},empty={padding:18,color:'#718995',fontSize:11,lineHeight:1.5},err={margin:12,padding:10,border:'1px solid #e3b5b5',borderRadius:6,background:'#fff5f5',color:'#9a4545',fontSize:10}
