'use client'

import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { createSmartTakeoffMetadata, getSmartTakeoffGroups } from './smartTakeoff'

const APPROVED_SHELL_CSS=`
[class*="application"]:has([data-ritsucad-approved-shell="true"]){display:grid!important;grid-template-columns:290px minmax(0,1fr)!important;grid-template-rows:65px minmax(0,1fr)!important;position:relative!important;background:#9aaaba!important}
[class*="application"]:has([data-ritsucad-approved-shell="true"])>[class*="applicationHeader"]{grid-column:1/3!important;grid-row:1!important;width:100%!important;height:65px!important;min-height:65px!important;padding:0 12px!important;background:#063c56!important;border-bottom:0!important;color:#fff!important}
[class*="application"]:has([data-ritsucad-approved-shell="true"])>[class*="applicationHeader"] [class*="productText"] strong,[class*="application"]:has([data-ritsucad-approved-shell="true"])>[class*="applicationHeader"] [class*="headerDrawingName"]{color:#fff!important}
[class*="application"]:has([data-ritsucad-approved-shell="true"])>[class*="applicationHeader"] [class*="productText"] span{color:#7fa2b5!important}
[class*="application"]:has([data-ritsucad-approved-shell="true"])>[class*="applicationHeader"] [class*="backButton"]{height:40px!important;background:#fff!important;border-color:#d4dee7!important;color:#244b63!important;font-size:14px!important}
[data-ritsucad-approved-shell="true"]{grid-column:1!important;grid-row:2!important;position:relative!important;z-index:70!important;display:flex!important;flex-direction:column!important;align-items:stretch!important;width:290px!important;height:100%!important;min-height:0!important;padding:0 12px 16px!important;overflow-x:hidden!important;overflow-y:auto!important;border-right:1px solid #d5dee7!important;border-bottom:0!important;background:#f8fafc!important;scrollbar-width:thin!important}
[class*="application"]:has([data-ritsucad-approved-shell="true"])>[class*="cadArea"]{grid-column:2!important;grid-row:2!important;width:auto!important;min-width:0!important;min-height:0!important}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;align-items:start!important;gap:4px 7px!important;width:100%!important;padding:35px 0 12px!important;position:relative!important;border-bottom:1px solid #d8e1e7!important}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]:nth-of-type(1)::before{content:'FILE'}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]:nth-of-type(2)::before{content:'VIEW'}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]:nth-of-type(3)::before{content:'DRAW'}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]:nth-of-type(4)::before{content:'MEASURE · TAKEOFF'}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]:nth-of-type(5)::before{content:'EDIT · SETUP'}
[data-ritsucad-approved-shell="true"]>[class*="toolbarSection"]::before{position:absolute;top:12px;left:5px;color:#31556b;font-size:10px;line-height:1;font-weight:900;letter-spacing:.08em}
[data-ritsucad-approved-shell="true"]>[class*="toolbarDivider"]{display:none!important}
[data-ritsucad-approved-shell="true"] [class*="toolbarButton"],[data-ritsucad-approved-shell="true"] [class*="toolbarButtonWide"],[data-ritsucad-approved-shell="true"] [class*="toolbarIconButton"]{width:100%!important;min-width:0!important;height:54px!important;min-height:54px!important;padding:5px 3px!important;margin:0!important;flex-direction:column!important;justify-content:center!important;gap:4px!important;border-radius:6px!important;font-size:9px!important;line-height:1!important;overflow:hidden!important;background:transparent!important;border-color:transparent!important}
[data-ritsucad-approved-shell="true"] [class*="importButton"]{width:100%!important;min-width:0!important;height:56px!important;min-height:56px!important;padding:5px!important;margin:0!important;flex-direction:column!important;justify-content:center!important;gap:4px!important;border-radius:7px!important;font-size:10px!important;line-height:1!important;overflow:hidden!important;background:#052f4c!important;color:#fff!important;border-color:#052f4c!important}
[data-ritsucad-approved-shell="true"] [class*="toolbarButton"] span,[data-ritsucad-approved-shell="true"] [class*="toolbarButtonWide"] span{max-width:100%!important;overflow:hidden!important;text-overflow:ellipsis!important;font-size:9px!important}
[data-ritsucad-approved-shell="true"] [class*="toolbarButton"][class*="active"],[data-ritsucad-approved-shell="true"] [class*="toolbarButtonWide"][class*="active"]{background:#e9fbf9!important;border-color:#79d8d2!important;color:#007f79!important}
.ritsucadBridgeSection{position:relative;display:block;width:100%;padding:35px 0 12px;border-bottom:1px solid #d8e1e7}
.ritsucadBridgeTitle{position:absolute;top:12px;left:5px;color:#31556b;font-size:10px;line-height:1;font-weight:900;letter-spacing:.08em}
.ritsucadBridgeGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}
.ritsucadBridgeButton{width:100%;height:48px;min-width:0;padding:4px 5px;border:1px solid #b9cbd5;border-radius:6px;background:#fff;color:#173e52;display:inline-flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;font:inherit;font-weight:800;cursor:pointer;overflow:hidden}
.ritsucadBridgeButton>span{font-size:15px;line-height:1}.ritsucadBridgeButton>small{max-width:100%;font-size:8px;line-height:1.05;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ritsucadBridgeButton.active{border-color:#73d1cc;background:#e8faf8;color:#007f79}.ritsucadBridgeButton:disabled{opacity:.45;cursor:default}
.ritsucadSmartMenu{position:absolute;z-index:1000;top:50px;left:0;min-width:190px;padding:5px;border:1px solid #bfd0da;border-radius:7px;background:#fff;box-shadow:0 8px 24px rgba(15,54,75,.18)}
.ritsucadSmartMenu button{width:100%;display:grid;grid-template-columns:22px 1fr auto;align-items:center;gap:6px;padding:7px 9px;border:0;border-radius:5px;background:#fff;color:#173e52;font:inherit;text-align:left;cursor:pointer}.ritsucadSmartMenu button.active{background:#e8faf8;color:#007f79}.ritsucadSmartMenu button strong{font-size:11px}.ritsucadSmartMenu button small{font-size:9px;color:#78909c}
[class*="application"]:has([data-ritsucad-approved-shell="true"]) [class*="statusBar"]{background:#063c56!important;color:#fff!important}
@media(max-width:1200px){[class*="application"]:has([data-ritsucad-approved-shell="true"]){grid-template-columns:290px minmax(0,1fr)!important}[data-ritsucad-approved-shell="true"]{width:290px!important}}
`

export default function RitsuCadRibbonBridge(){
 const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams();const[fileSection,setFileSection]=useState(null),[toolbar,setToolbar]=useState(null),[activeSmartTakeoff,setActiveSmartTakeoff]=useState(null),[openGroup,setOpenGroup]=useState(null);const smartMenuRef=useRef(null)
 const projectId=searchParams.get('projectId'),documentId=searchParams.get('documentId'),viewId=searchParams.get('viewId'),mappingMode=searchParams.get('mode')==='location-mapping',hasProjectDrawing=Boolean(projectId&&documentId),smartGroups=getSmartTakeoffGroups()
 useEffect(()=>{let cancelled=false,observer=null;const sync=()=>{if(cancelled)return;const t=document.querySelector('[class*="cadToolbar"]'),f=t?.querySelector('[class*="toolbarSection"]')||null;setToolbar(c=>c===t?c:t);setFileSection(c=>c===f?c:f)};sync();observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});return()=>{cancelled=true;observer?.disconnect()}},[pathname])
 useEffect(()=>{if(!toolbar)return;toolbar.dataset.ritsucadApprovedShell='true';return()=>{delete toolbar.dataset.ritsucadApprovedShell}},[toolbar])
 useEffect(()=>{const close=e=>{if(smartMenuRef.current&&!smartMenuRef.current.contains(e.target))setOpenGroup(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[])
 useEffect(()=>{let cancelled=false,attempts=0,closed=false;const run=()=>{if(cancelled||closed)return;attempts++;const inspector=document.querySelector('[class*="_inspector__"]');if(inspector){const close=Array.from(inspector.querySelectorAll('button')).find(b=>{const title=(b.getAttribute('title')||'').toLowerCase(),label=(b.getAttribute('aria-label')||'').toLowerCase(),text=(b.textContent||'').trim().toLowerCase();return title.includes('close')||label.includes('close')||text==='×'});if(close){close.click();closed=true;return}}if(attempts<120)window.setTimeout(run,50)};run();return()=>{cancelled=true}},[pathname,documentId])
 useEffect(()=>()=>{delete window.__RITSUCAD_ACTIVE_SMART_TAKEOFF__},[])
 function openLocationMapping(){if(!hasProjectDrawing)return;const p=new URLSearchParams(searchParams.toString());p.set('mode','location-mapping');window.dispatchEvent(new Event('ritsucad:close-takeoff-context'));router.replace(`${pathname}?${p.toString()}`,{scroll:false})}
 function openTakeoffContext(){if(!hasProjectDrawing)return;const p=new URLSearchParams(searchParams.toString());p.delete('mode');router.replace(`${pathname}?${p.toString()}`,{scroll:false});window.setTimeout(()=>window.dispatchEvent(new Event('ritsucad:open-takeoff-context')),0)}
 function activateSmartTakeoff(item){if(!hasProjectDrawing)return;const metadata=createSmartTakeoffMetadata(item.id);window.__RITSUCAD_ACTIVE_SMART_TAKEOFF__=metadata;setActiveSmartTakeoff(item.id);setOpenGroup(null);window.dispatchEvent(new CustomEvent('ritsucad:smart-takeoff-selected',{detail:{...item,metadata}}));const key={line:'l',polyline:'p',area:'a',rectangle:'r',count:'c'}[item.measurementTool];if(key)document.dispatchEvent(new KeyboardEvent('keydown',{key,code:`Key${key.toUpperCase()}`,bubbles:true}))}
 const projectDrawingButton=fileSection&&!hasProjectDrawing?createPortal(<RibbonButton icon="▣" label="Project Drawing" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-project-drawing'))} title="Open a PDF drawing stored in a RitsuFlow project"/>,fileSection):null
 const smartTakeoffSection=toolbar?createPortal(<div ref={smartMenuRef} data-ritsucad-smart-takeoff="true" className="ritsucadBridgeSection"><span className="ritsucadBridgeTitle">SMART TAKEOFF</span><div className="ritsucadBridgeGrid">{smartGroups.map(group=><div key={group.name} style={{position:'relative',minWidth:0}}><CategoryButton label={group.name==='Architectural'?'Architecture':group.name} icon={groupIcon(group.name)} disabled={!hasProjectDrawing} active={group.items.some(i=>i.id===activeSmartTakeoff)} onClick={()=>hasProjectDrawing&&setOpenGroup(c=>c===group.name?null:group.name)}/>{openGroup===group.name&&hasProjectDrawing?<div className="ritsucadSmartMenu">{group.items.map(item=><button key={item.id} type="button" onClick={()=>activateSmartTakeoff(item)} className={activeSmartTakeoff===item.id?'active':''}><span>{smartIcon(item.id)}</span><strong>{item.label}</strong><small>{item.measurementTool}</small></button>)}</div>:null}</div>)}</div></div>,toolbar):null
 const projectDataSection=toolbar&&hasProjectDrawing?createPortal(<div data-ritsucad-project-data="true" className="ritsucadBridgeSection"><span className="ritsucadBridgeTitle">PROJECT DATA</span><div className="ritsucadBridgeGrid"><RibbonButton icon="▤" label="Views" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-drawing-views-command'))} title="Open saved drawing views"/><RibbonButton icon="✓" label={viewId?'Save View':'Save As'} onClick={()=>window.dispatchEvent(new Event('ritsucad:save-drawing-view'))} title={viewId?'Save the current drawing view':'Save the current geometry as a drawing view'}/><RibbonButton icon="⌖" label="Locations" active={mappingMode} onClick={openLocationMapping} title="Map existing LBS locations on this drawing"/><RibbonButton icon="▦" label="Takeoff" onClick={openTakeoffContext} title="Open project takeoff context"/></div></div>,toolbar):null
 return <><style>{APPROVED_SHELL_CSS}</style>{projectDrawingButton}{smartTakeoffSection}{projectDataSection}</>
}
function groupIcon(group){return{Architectural:'⌂',Structural:'▰',MEP:'⌁',Geometry:'△'}[group]||'•'}
function smartIcon(type){return{wall:'▥',floor:'▱',ceiling:'⌂',door:'◧',window:'⊞',baseboard:'━',painting:'▨',slab:'▰',beam:'▬',column:'▮',footing:'▣',pipe:'⌁',duct:'▭',fixture:'⊕',equipment:'⚙','generic-linear':'╱','generic-area':'△','generic-count':'#'}[type]||'•'}
function CategoryButton({icon,label,onClick,disabled,active}){return <button type="button" disabled={disabled} onClick={onClick} title={disabled?'Open a project drawing to use Smart Takeoff':`${label} Smart Takeoff`} className={`ritsucadBridgeButton${active?' active':''}`}><span aria-hidden="true">{icon}</span><small>{label} ▾</small></button>}
function RibbonButton({icon,label,onClick,title,active=false}){return <button type="button" onClick={onClick} title={title} className={`ritsucadBridgeButton${active?' active':''}`}><span aria-hidden="true">{icon}</span><small>{label}</small></button>}
