'use client'

import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { useSearchParams } from 'next/navigation'
import { supabase } from '../../lib/supabase'

function treeOf(rows){const map=new Map();for(const row of rows){const key=row.parent_id||'root';if(!map.has(key))map.set(key,[]);map.get(key).push(row)}for(const list of map.values())list.sort((a,b)=>Number(a.sequence_number||0)-Number(b.sequence_number||0)||String(a.name||'').localeCompare(String(b.name||'')));return map}

export default function RitsuCadProjectContext(){
 const params=useSearchParams(),projectId=params.get('projectId')
 const [project,setProject]=useState(null),[locations,setLocations]=useState([]),[expanded,setExpanded]=useState(new Set()),[selected,setSelected]=useState(''),[collapsed,setCollapsed]=useState(false),[ribbonHost,setRibbonHost]=useState(null)
 const tree=useMemo(()=>treeOf(locations),[locations])
 useEffect(()=>{let frame=0,cancelled=false;const sync=()=>{if(cancelled)return;const groups=document.querySelector('.rfRibbonGroups');const home=document.querySelector('.rfRibbonTabList button.active')?.textContent?.trim()==='Home';setRibbonHost(home?groups:null)};const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(sync)};sync();const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});return()=>{cancelled=true;cancelAnimationFrame(frame);observer.disconnect()}},[])
 useEffect(()=>{if(!projectId){setProject(null);setLocations([]);return}let active=true;(async()=>{const [{data:p},{data:l}]=await Promise.all([supabase.from('projects').select('id,project_id,code,name,status').eq('id',projectId).maybeSingle(),supabase.from('locations').select('id,parent_id,name,location_type,sequence_number').eq('project_id',projectId).order('sequence_number',{ascending:true})]);if(!active)return;setProject(p||null);setLocations(l||[]);setExpanded(new Set((l||[]).filter(x=>!x.parent_id).map(x=>x.id)))})();return()=>{active=false}},[projectId])
 function toggle(id){setExpanded(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function renderBranch(parent='root',depth=0){return(tree.get(parent)||[]).map(item=>{const kids=tree.get(item.id)||[],open=expanded.has(item.id),active=selected===item.id;return <div key={item.id}><button className={active?'rfLbsRow active':'rfLbsRow'} style={{paddingLeft:10+depth*15}} onClick={()=>{setSelected(item.id);if(kids.length)toggle(item.id);window.dispatchEvent(new CustomEvent('ritsucad:active-location-changed',{detail:{location:item}}))}}><span className="rfLbsChevron">{kids.length?(open?'▾':'▸'):'◇'}</span><span className="rfLbsName"><strong>{item.name}</strong><small>{item.location_type||'Location'}</small></span></button>{kids.length&&open&&renderBranch(item.id,depth+1)}</div>})}
 const projectButton=ribbonHost?createPortal(<div className="rfCommandGroup rfProjectGroup"><div className="rfCommandItems"><button type="button" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-project'))} title={project?'Change active project':'Open project'}><span>▣</span><strong>{project?'Change Project':'Open Project'}</strong></button>{project&&<button type="button" onClick={()=>setCollapsed(v=>!v)} title="Show or hide the project Location Breakdown Structure"><span>⌘</span><strong>{collapsed?'Show LBS':'Hide LBS'}</strong></button>}</div><small>Project</small></div>,ribbonHost):null
 return <><style>{CSS}</style>{projectButton}{project&&!collapsed&&<aside className="rfProjectExplorer"><header><div><small>ACTIVE PROJECT</small><strong>{project.name}</strong><span>{project.project_id||project.code||'RitsuFlow Project'}</span></div><button type="button" onClick={()=>setCollapsed(true)} title="Collapse LBS">‹</button></header><div className="rfLbsHeading"><div><strong>Location Breakdown Structure</strong><span>{locations.length} location{locations.length===1?'':'s'}</span></div><button type="button" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-project'))}>Change</button></div><div className="rfLbsTree">{locations.length?renderBranch():<div className="rfLbsEmpty">No locations have been registered for this project yet.</div>}</div><footer>{selected?'Active location selected':'Select a location to make it the active CAD context'}</footer></aside>}{project&&collapsed&&<button className="rfProjectExplorerCollapsed" type="button" onClick={()=>setCollapsed(false)} title="Open project LBS"><span>⌘</span><strong>LBS</strong></button>}</>
}

const CSS=`
.rfProjectGroup{order:-1}.rfProjectExplorer{position:fixed;z-index:82;top:160px;left:12px;bottom:88px;width:270px;display:flex;flex-direction:column;background:#f8fbfc;border:1px solid #aebfc8;border-radius:7px;box-shadow:0 8px 24px rgba(15,52,70,.18);color:#123b50;overflow:hidden;font-family:inherit}.rfProjectExplorer header{min-height:58px;display:flex;align-items:center;justify-content:space-between;padding:9px 9px 9px 12px;background:#083f59;color:#fff}.rfProjectExplorer header>div{display:flex;min-width:0;flex-direction:column;gap:1px}.rfProjectExplorer header small{font-size:7px;letter-spacing:.12em;color:#8fc0d0;font-weight:900}.rfProjectExplorer header strong{max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.rfProjectExplorer header span{font-size:8px;color:#b8d0db}.rfProjectExplorer header button{width:28px;height:28px;border:0;border-radius:4px;background:rgba(255,255,255,.1);color:#fff;font-size:22px;cursor:pointer}.rfLbsHeading{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px 10px 8px;border-bottom:1px solid #d7e2e7;background:#fff}.rfLbsHeading>div{display:flex;flex-direction:column;gap:2px}.rfLbsHeading strong{font-size:10px}.rfLbsHeading span{font-size:8px;color:#78909b}.rfLbsHeading button{height:25px;padding:0 8px;border:1px solid #c4d5dc;border-radius:4px;background:#fff;color:#17627c;font-size:8px;font-weight:900;cursor:pointer}.rfLbsTree{flex:1;overflow:auto;padding:5px 0;background:#fff}.rfLbsRow{width:100%;min-height:38px;display:flex;align-items:center;gap:5px;padding-right:8px;border:0;border-bottom:1px solid #eef3f5;background:#fff;color:#173f52;text-align:left;cursor:pointer}.rfLbsRow:hover{background:#f0f8f9}.rfLbsRow.active{background:#e3f6f5;box-shadow:inset 3px 0 0 #00a59d}.rfLbsChevron{width:12px;color:#317087;font-size:9px}.rfLbsName{display:flex;min-width:0;flex:1;flex-direction:column;gap:1px}.rfLbsName strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9.5px}.rfLbsName small{font-size:7.5px;color:#8297a1;text-transform:capitalize}.rfLbsEmpty{padding:18px 14px;color:#718995;font-size:9.5px;line-height:1.5}.rfProjectExplorer footer{padding:8px 10px;border-top:1px solid #d7e2e7;background:#f5f9fa;color:#6d8793;font-size:8px}.rfProjectExplorerCollapsed{position:fixed;z-index:82;top:176px;left:0;width:42px;height:72px;border:1px solid #aebfc8;border-left:0;border-radius:0 7px 7px 0;background:#fff;color:#075f78;box-shadow:0 5px 16px rgba(15,52,70,.15);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;cursor:pointer}.rfProjectExplorerCollapsed span{font-size:19px}.rfProjectExplorerCollapsed strong{font-size:8px}
`