'use client'

import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { supabase } from '../../lib/supabase'

function buildTree(locations){const map=new Map();locations.forEach(location=>{const key=location.parent_id||'root';if(!map.has(key))map.set(key,[]);map.get(key).push(location)});map.forEach(items=>items.sort((a,b)=>Number(a.sequence_number||0)-Number(b.sequence_number||0)||String(a.name||'').localeCompare(String(b.name||''))));return map}

export default function RitsuCadProjectPanel(){
 const searchParams=useSearchParams(),projectId=searchParams.get('projectId'),documentId=searchParams.get('documentId')
 const [project,setProject]=useState(null),[locations,setLocations]=useState([]),[mappedLocations,setMappedLocations]=useState(new Set()),[expanded,setExpanded]=useState(new Set()),[selected,setSelected]=useState(''),[collapsed,setCollapsed]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const tree=useMemo(()=>buildTree(locations),[locations])
 useEffect(()=>{if(!projectId)return;let active=true;(async()=>{setLoading(true);setError('');const[{data:projectData,error:projectError},{data:locationData,error:locationError}]=await Promise.all([supabase.from('projects').select('id,project_id,code,name,status').eq('id',projectId).maybeSingle(),supabase.from('locations').select('id,parent_id,name,location_type,sequence_number').eq('project_id',projectId).order('sequence_number',{ascending:true})]);if(!active)return;if(projectError||locationError)setError(projectError?.message||locationError?.message||'Unable to load project context.');const resolvedLocations=locationData||[];setProject(projectData||null);setLocations(resolvedLocations);setExpanded(new Set(resolvedLocations.filter(item=>!item.parent_id).map(item=>item.id)));setSelected(resolvedLocations[0]?.id||'');window.__ritsuCadLbsContext={projectId,locations:resolvedLocations};window.dispatchEvent(new CustomEvent('ritsucad:lbs-context-ready',{detail:{projectId,locations:resolvedLocations}}));setLoading(false)})();return()=>{active=false}},[projectId])
 useEffect(()=>{if(!projectId||!documentId){setMappedLocations(new Set());return}let active=true;async function loadMapped(){const{data:map,error:mapError}=await supabase.from('project_drawing_maps').select('id').eq('project_id',projectId).eq('document_id',documentId).eq('page_number',1).maybeSingle();if(!active)return;if(mapError||!map?.id){setMappedLocations(new Set());return}const{data,error:geometryError}=await supabase.from('project_drawing_location_geometries').select('location_id').eq('drawing_map_id',map.id);if(!active)return;if(geometryError){setMappedLocations(new Set());return}setMappedLocations(new Set((data||[]).map(row=>row.location_id).filter(Boolean)))}loadMapped();const saved=event=>{const id=event?.detail?.locationId;if(id)setMappedLocations(current=>new Set([...current,id]))};window.addEventListener('ritsucad:location-boundary-saved',saved);return()=>{active=false;window.removeEventListener('ritsucad:location-boundary-saved',saved)}},[projectId,documentId])
 function toggle(id){setExpanded(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function select(location){setSelected(location.id);window.dispatchEvent(new CustomEvent('ritsucad:location-selected',{detail:{locationId:location.id,name:location.name}}))}
 function renderBranch(parent='root',depth=0){return(tree.get(parent)||[]).map(location=>{const children=tree.get(location.id)||[],open=expanded.has(location.id),active=selected===location.id,mapped=mappedLocations.has(location.id);return <div key={location.id}><div className={`rfLbsRow${active?' active':''}`} style={{paddingLeft:10+depth*16}} onClick={()=>select(location)}><button type="button" className="rfLbsChevron" title={children.length?(open?'Collapse':'Expand'):''} onClick={event=>{event.stopPropagation();if(children.length)toggle(location.id)}}>{children.length?(open?'▾':'▸'):'◇'}</button><span className="rfLbsName">{location.name}</span>{mapped?<span className="rfLbsMapped" title="Mapped on drawing" aria-label="Mapped on drawing">✓</span>:null}</div>{children.length&&open?renderBranch(location.id,depth+1):null}</div>})}
 if(!projectId)return null
 const projectCode=project?.project_id||project?.code||'Project'
 if(collapsed)return <button type="button" className="rfLbsRestore" title="Show Location Breakdown Structure" onClick={()=>setCollapsed(false)}>LBS</button>
 return <aside className="rfLbsPanel" data-ritsucad-project-panel="true"><style>{CSS}</style><div className="rfLbsHeader"><div><strong>Location Breakdown Structure</strong><small><b>{project?.name||'Project'}</b><span>·</span>{projectCode}<span>·</span>{locations.length} locations</small></div><div className="rfLbsHeaderActions"><button type="button" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-project'))}>Change</button><button type="button" className="collapse" title="Hide LBS" onClick={()=>setCollapsed(true)}>‹</button></div></div><div className="rfLbsTree">{loading?<div className="rfLbsMessage">Loading Location Breakdown Structure…</div>:error?<div className="rfLbsError">{error}</div>:locations.length?renderBranch():<div className="rfLbsMessage">No project locations yet.</div>}</div><div className="rfLbsFooter">{mappedLocations.size} mapped · {selected?'Active location selected':'Select a location'}</div></aside>
}

const CSS=`
.rfLbsPanel{position:fixed;z-index:70;top:160px;left:0;bottom:76px;width:316px;display:flex;flex-direction:column;background:#fff;border:1px solid #c8d6dd;border-left:0;border-radius:0 8px 8px 0;color:#123b50;font-family:inherit;box-shadow:0 7px 20px rgba(20,57,75,.10);overflow:hidden}
.rfLbsHeader{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px 9px 10px 13px;border-bottom:1px solid #d9e3e7;background:#fff}.rfLbsHeader>div:first-child{min-width:0}.rfLbsHeader strong{display:block;font-size:11px;line-height:1.25;color:#0c3549;white-space:nowrap}.rfLbsHeader small{display:flex;align-items:center;gap:6px;margin-top:4px;font-size:8px;color:#718995;white-space:nowrap}.rfLbsHeader small b{color:#31596c;font-weight:800;max-width:90px;overflow:hidden;text-overflow:ellipsis}.rfLbsHeaderActions{display:flex;align-items:center;gap:5px}.rfLbsHeaderActions button{height:29px;padding:0 10px;border:1px solid #c4d4dc;border-radius:5px;background:#fff;color:#14506a;font-size:9px;font-weight:850;cursor:pointer}.rfLbsHeaderActions button:hover{background:#eef7f8}.rfLbsHeaderActions button.collapse{width:29px;padding:0;font-size:20px;line-height:1}
.rfLbsTree{flex:1;min-height:0;overflow:auto;background:#fff}.rfLbsRow{min-height:34px;display:flex;align-items:center;gap:4px;padding-right:8px;border-bottom:1px solid #edf2f4;background:#fff;color:#173f52;cursor:pointer;user-select:none}.rfLbsRow:hover{background:#f2f8f9}.rfLbsRow.active{background:#e3f5f4;box-shadow:inset 3px 0 0 #0aa3a0}.rfLbsChevron{width:25px;height:30px;flex:0 0 25px;border:0;background:transparent;color:#23627a;font-size:10px;cursor:pointer}.rfLbsName{min-width:0;flex:1;font-size:10px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rfLbsMapped{width:18px;height:18px;flex:0 0 18px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #0a948a;border-radius:4px;background:#e7f8f5;color:#07877d;font-size:10px;font-weight:950;line-height:1}
.rfLbsFooter{height:29px;display:flex;align-items:center;padding:0 12px;border-top:1px solid #dce6ea;background:#fafcfc;color:#708894;font-size:8px}.rfLbsMessage,.rfLbsError{padding:18px 13px;font-size:10px;line-height:1.45;color:#718995}.rfLbsError{color:#9a4545}.rfLbsRestore{position:fixed;z-index:71;top:204px;left:0;width:46px;height:32px;border:1px solid #bfd0d8;border-left:0;border-radius:0 6px 6px 0;background:#fff;color:#0a5870;font-size:9px;font-weight:900;box-shadow:0 5px 15px rgba(20,57,75,.12);cursor:pointer}
@media(max-width:1100px){.rfLbsPanel{width:286px}}
`