'use client'

import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { useSearchParams } from 'next/navigation'
import { supabase } from '../../lib/supabase'

function treeOf(rows){const map=new Map();for(const row of rows){const key=row.parent_id||'root';if(!map.has(key))map.set(key,[]);map.get(key).push(row)}for(const list of map.values())list.sort((a,b)=>Number(a.sequence_number||0)-Number(b.sequence_number||0)||String(a.name||'').localeCompare(String(b.name||'')));return map}

export default function RitsuCadProjectContext(){
 const params=useSearchParams(),projectId=params.get('projectId')
 const [project,setProject]=useState(null),[locations,setLocations]=useState([]),[expanded,setExpanded]=useState(new Set()),[selected,setSelected]=useState(''),[collapsed,setCollapsed]=useState(false),[ribbonHost,setRibbonHost]=useState(null)
 const tree=useMemo(()=>treeOf(locations),[locations])
 useEffect(()=>{let frame=0,cancelled=false;const sync=()=>{if(cancelled)return;const groups=document.querySelector('.rfRibbonGroups');const home=document.querySelector('.rfRibbonTabList button.active')?.textContent?.trim()==='Home';setRibbonHost(home?groups:null)};const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(sync)};sync();const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});return()=>{cancelled=true;cancelAnimationFrame(frame);observer.disconnect()}},[])
 useEffect(()=>{if(!projectId){setProject(null);setLocations([]);return}let active=true;(async()=>{const [{data:p},{data:l}]=await Promise.all([supabase.from('projects').select('id,project_id,code,name,status').eq('id',projectId).maybeSingle(),supabase.from('locations').select('id,parent_id,name,location_type,sequence_number').eq('project_id',projectId).order('sequence_number',{ascending:true})]);if(!active)return;setProject(p||null);setLocations(l||[]);setExpanded(new Set((l||[]).filter(x=>!x.parent_id).map(x=>x.id)))})();return()=>{active=false}},[projectId])
 function toggle(id){setExpanded(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function renderBranch(parent='root',depth=0){return(tree.get(parent)||[]).map(item=>{const kids=tree.get(item.id)||[],open=expanded.has(item.id),active=selected===item.id;return <div key={item.id}><button className={active?'rfLbsRow active':'rfLbsRow'} style={{paddingLeft:10+depth*15}} onClick={()=>{setSelected(item.id);if(kids.length)toggle(item.id);window.dispatchEvent(new CustomEvent('ritsucad:active-location-changed',{detail:{location:item}}))}}><span className="rfLbsChevron">{kids.length?(open?'▾':'▸'):'◇'}</span><span className="rfLbsName"><strong>{item.name}</strong></span></button>{kids.length&&open&&renderBranch(item.id,depth+1)}</div>})}
 const projectButton=ribbonHost?createPortal(<div className="rfCommandGroup rfProjectGroup"><div className="rfCommandItems"><button type="button" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-project'))} title={project?'Change active project':'Open project'}><span>▣</span><strong>{project?'Change Project':'Open Project'}</strong></button>{project&&<button type="button" onClick={()=>setCollapsed(v=>!v)} title="Show or hide the project Location Breakdown Structure"><span>⌘</span><strong>{collapsed?'Show LBS':'Hide LBS'}</strong></button>}</div><small>Project</small></div>,ribbonHost):null
 return <><style>{CSS}</style>{projectButton}{project&&!collapsed&&<aside className="rfProjectExplorer"><div className="rfLbsHeading"><div><strong>Location Breakdown Structure</strong><span><b>{project.name}</b><i>·</i>{project.project_id||project.code||'RitsuFlow Project'}<i>·</i>{locations.length} location{locations.length===1?'':'s'}</span></div><div className="rfLbsHeadingActions"><button type="button" onClick={()=>window.dispatchEvent(new Event('ritsucad:open-project'))}>Change</button><button type="button" className="rfLbsCollapse" onClick={()=>setCollapsed(true)} title="Collapse LBS">‹</button></div></div><div className="rfLbsTree">{locations.length?renderBranch():<div className="rfLbsEmpty">No locations have been registered for this project yet.</div>}</div><footer>{selected?'Active location selected':'Select a location to make it the active CAD context'}</footer></aside>}{project&&collapsed&&<button className="rfProjectExplorerCollapsed" type="button" onClick={()=>setCollapsed(false)} title="Open project LBS"><span>⌘</span><strong>LBS</strong></button>}</>
}

const CSS=`
.rfProjectGroup{order:-1}.rfProjectExplorer{position:fixed;z-index:82;top:160px;left:12px;bottom:88px;width:270px;display:flex;flex-direction:column;background:#f8fbfc;border:1px solid #aebfc8;border-radius:7px;box-shadow:0 8px 24px rgba(15,52,70,.18);color:#123b50;overflow:hidden;font-family:inherit}.rfLbsHeading{min-height:47px;display:flex;align-items:center;justify-content:space-between;gap:6px;padding:7px 7px 7px 11px;border-bottom:1px solid #d7e2e7;background:#fff}.rfLbsHeading>div:first-child{display:flex;min-width:0;flex:1;flex-direction:column;gap:3px}.rfLbsHeading strong{font-size:10px}.rfLbsHeading span{display:flex;align-items:center;gap:4px;min-width:0;overflow:hidden;color:#78909b;font-size:7.5px;white-space:nowrap}.rfLbsHeading span b{max-width:90px;overflow:hidden;text-overflow:ellipsis;color:#31596c;font-size:8px}.rfLbsHeading span i{font-style:normal;color:#b0c0c7}.rfLbsHeadingActions{display:flex!important;flex:0 0 auto!important;flex-direction:row!important;align-items:center;gap:4px!important}.rfLbsHeading button{height:25px;padding:0 8px;border:1px solid #c4d5dc;border-radius:4px;background:#fff;color:#17627c;font-size:8px;font-weight:900;cursor:pointer}.rfLbsHeading button.rfLbsCollapse{width:25px;padding:0;font-size:18px;line-height:20px}.rfLbsTree{flex:1;overflow:auto;padding:3px 0;background:#fff}.rfLbsRow{width:100%;height:29px;min-height:29px;display:flex;align-items:center;gap:4px;padding-top:0;padding-bottom:0;padding-right:8px;border:0;border-bottom:1px solid #f0f4f6;background:#fff;color:#173f52;text-align:left;cursor:pointer}.rfLbsRow:hover{background:#f0f8f9}.rfLbsRow.active{background:#e3f6f5;box-shadow:inset 3px 0 0 #00a59d}.rfLbsChevron{width:12px;flex:0 0 12px;color:#317087;font-size:8px}.rfLbsName{display:flex;min-width:0;flex:1;align-items:center}.rfLbsName strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9.5px;line-height:1}.rfLbsEmpty{padding:18px 14px;color:#718995;font-size:9.5px;line-height:1.5}.rfProjectExplorer footer{padding:8px 10px;border-top:1px solid #d7e2e7;background:#f5f9fa;color:#6d8793;font-size:8px}.rfProjectExplorerCollapsed{position:fixed;z-index:82;top:176px;left:0;width:42px;height:72px;border:1px solid #aebfc8;border-left:0;border-radius:0 7px 7px 0;background:#fff;color:#075f78;box-shadow:0 5px 16px rgba(15,52,70,.15);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;cursor:pointer}.rfProjectExplorerCollapsed span{font-size:19px}.rfProjectExplorerCollapsed strong{font-size:8px}
`