'use client'

import { useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { supabase } from '../../lib/supabase'

function parsePoints(value){return String(value||'').trim().split(/\s+/).map(pair=>{const[x,y]=pair.split(',').map(Number);return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null}).filter(Boolean)}
function geometryKey(points){return points.map(point=>`${point.x.toFixed(4)},${point.y.toFixed(4)}`).join('|')}
function parseMeasurementLabel(label){const text=String(label?.textContent||'').trim(),match=text.match(/^([0-9]+(?:\.[0-9]+)?)\s+(.+)$/);if(!match)return null;const quantity=Number(match[1]);return Number.isFinite(quantity)?{quantity,unit:match[2]}:null}
function readAreaTakeoffs(){return Array.from(document.querySelectorAll('svg g')).map(group=>{const polygon=group.querySelector('polygon[stroke="#0f9f91"]'),label=group.querySelector('text');if(!polygon||!label)return null;const points=parsePoints(polygon.getAttribute('points'));if(points.length<3)return null;const measurement=parseMeasurementLabel(label);return measurement?{key:`area:${geometryKey(points)}`,points,...measurement,measurementType:'area',element:polygon}:null}).filter(Boolean)}
function readPolylineTakeoffs(){return Array.from(document.querySelectorAll('svg g')).map(group=>{const polyline=group.querySelector('polyline[stroke="#ea580c"], polyline[data-ritsucad-smart-takeoff="true"]'),label=group.querySelector('text');if(!polyline||!label)return null;const points=parsePoints(polyline.getAttribute('points'));if(points.length<2)return null;const measurement=parseMeasurementLabel(label);return measurement?{key:`polyline:${geometryKey(points)}`,points,...measurement,measurementType:'polyline',element:polyline}:null}).filter(Boolean)}
function smartGeometry(item,smart,context){if(!smart)return{points:item.points,source:`ritsucad-${item.measurementType}-takeoff`,scopeContext:scopeGeometryContext(context)};return{points:item.points,source:'ritsucad-smart-takeoff',scopeContext:scopeGeometryContext(context),smartTakeoff:{typeId:smart.typeId||smart.id||null,label:smart.label||smart.typeLabel||null,discipline:smart.discipline||null,category:smart.category||null,measurementTool:smart.measurementTool||item.measurementType,quantityBasis:smart.quantityBasis||null,primaryUnit:smart.primaryUnit||smart.unit||item.unit,secondaryUnit:smart.secondaryUnit||null,layer:smart.layer||smart.properties?.layer||null,name:smart.name||smart.properties?.name||null,height:smart.height||smart.properties?.height||null,lineColor:smart.lineColor||smart.properties?.lineColor||null,lineThickness:smart.lineThickness||smart.properties?.lineThickness||null,properties:smart.properties||{},semanticVersion:1}}}
function scopeGeometryContext(context){return{projectScopeId:context?.projectScopeId||null,scopeCode:context?.scopeCode||null,scopeName:context?.scopeName||null,scopeItemType:context?.scopeItemType||null,scopeUnit:context?.scopeUnit||null}}
function isWallSmartTakeoff(smart){return String(smart?.typeId||smart?.id||'').toLowerCase()==='wall'}
function applySmartAppearance(item,smart){if(!item?.element||!isWallSmartTakeoff(smart))return;const color=smart.lineColor||smart.properties?.lineColor;const thickness=Number(smart.lineThickness||smart.properties?.lineThickness);item.element.setAttribute('data-ritsucad-smart-takeoff','true');item.element.setAttribute('data-ritsucad-smart-type','wall');if(smart.layer)item.element.setAttribute('data-ritsucad-layer',String(smart.layer));if(smart.name)item.element.setAttribute('data-ritsucad-name',String(smart.name));if(smart.height)item.element.setAttribute('data-ritsucad-height',String(smart.height));if(color&&item.element.getAttribute('stroke')!==color)item.element.setAttribute('stroke',color);if(Number.isFinite(thickness)&&thickness>0&&item.element.getAttribute('stroke-width')!==String(thickness))item.element.setAttribute('stroke-width',String(thickness));item.element.style.setProperty('stroke',color||'#0f766e','important');if(Number.isFinite(thickness)&&thickness>0)item.element.style.setProperty('stroke-width',String(thickness),'important')}

export default function TakeoffPersistenceBridge(){
 const searchParams=useSearchParams(),projectId=searchParams.get('projectId'),documentId=searchParams.get('documentId'),mappingMode=searchParams.get('mode')==='location-mapping'
 const[context,setContext]=useState(null),[smartTakeoff,setSmartTakeoff]=useState(null);const knownRef=useRef(new Set()),initializedRef=useRef(false),busyRef=useRef(false),styledRef=useRef(new Set())
 useEffect(()=>{function onContext(event){setContext(event.detail||null)}window.addEventListener('ritsucad:takeoff-context',onContext);setContext(window.__RITSUCAD_TAKEOFF_CONTEXT__||null);return()=>window.removeEventListener('ritsucad:takeoff-context',onContext)},[])
 useEffect(()=>{function onSmart(event){setSmartTakeoff(event.detail?.metadata||null)}window.addEventListener('ritsucad:smart-takeoff-selected',onSmart);setSmartTakeoff(window.__RITSUCAD_ACTIVE_SMART_TAKEOFF__||null);return()=>window.removeEventListener('ritsucad:smart-takeoff-selected',onSmart)},[])
 useEffect(()=>{if(!projectId||!documentId||mappingMode)return;let cancelled=false
  async function reconcile(){if(cancelled||busyRef.current)return;const visible=[...readAreaTakeoffs(),...readPolylineTakeoffs()];if(!initializedRef.current){const{data}=await supabase.from('ritsucad_takeoffs').select('source_entity_id').eq('project_id',projectId).eq('document_id',documentId);if(cancelled)return;knownRef.current=new Set((data||[]).map(row=>row.source_entity_id).filter(Boolean));initializedRef.current=true}const fresh=visible.filter(item=>!knownRef.current.has(item.key));if(isWallSmartTakeoff(smartTakeoff)){fresh.filter(item=>item.measurementType==='polyline').forEach(item=>{if(!styledRef.current.has(item.key)){applySmartAppearance(item,smartTakeoff);styledRef.current.add(item.key)}})}if(!context?.ready||!context.locationId)return;if(!fresh.length)return;busyRef.current=true;try{const{data:{user}}=await supabase.auth.getUser();if(!user||cancelled)return;for(const item of fresh){const isSmartMatch=smartTakeoff&&(smartTakeoff.measurementTool===item.measurementType||(smartTakeoff.measurementTool==='polyline'&&item.measurementType==='polyline'));const semantic=isSmartMatch?smartTakeoff:null;if(semantic)applySmartAppearance(item,semantic);const payload={project_id:projectId,document_id:documentId,page_number:Number(searchParams.get('page')||1),location_id:context.locationId,project_scope_id:context.projectScopeId||null,project_service_id:context.projectServiceId||null,measurement_type:semantic?.typeId?`smart:${semantic.typeId}`:item.measurementType,quantity:item.quantity,unit:item.unit,geometry:smartGeometry(item,semantic,context),source_entity_id:item.key,created_by:user.id,updated_at:new Date().toISOString()};const{error}=await supabase.from('ritsucad_takeoffs').insert(payload);if(!error){knownRef.current.add(item.key);window.dispatchEvent(new CustomEvent('ritsucad:takeoff-saved',{detail:{...payload,locationName:context.locationName,scopeName:context.scopeName,scopeCode:context.scopeCode,scopeItemType:context.scopeItemType,serviceName:context.serviceName,smartTakeoff:semantic}}))}else console.error('RitsuCAD takeoff persistence failed.',error)}}finally{busyRef.current=false}}
  const observer=new MutationObserver(()=>window.setTimeout(reconcile,0));observer.observe(document.body,{subtree:true,childList:true,attributes:true,characterData:true});reconcile();return()=>{cancelled=true;observer.disconnect()}
 },[projectId,documentId,mappingMode,context,smartTakeoff,searchParams]);return null
}
